### ISSUE TITLE
Resource Viewer visual appearance

### ISSUE THREAD

**Issue by mklanjsek** [vmware-tanzu/octant#1009]
**Describe the problem/challenge you have**

Currently new Resource Viewer is using simple wireframes for all resource types. We need to work with design to improve visual appearance and usability. Some of the things to consider:
- Use different shapes, colors, borders and connector types for different resources,
- Add headers with resource labels,
- Add color to indicate resource status,
- Implement user interaction (single click - show properties in Info Panel, double - open resource page)

**Comment by mklanjsek** [comment]
I started working on this with @rossfenrick, will get back and implement code changes after design is finalized.

**Comment by wwitzel3** [comment]
Something we need to think about visually is what does it look like if there are many ReplicaSets , this can happen during rolling deployments for example. How will we indicate there are two. How will be show that one is coming online and the other is draining/going offline.

**Comment by wwitzel3** [comment]
The original scope of this issue is completed.
