### ISSUE TITLE
Create an octant blog post for dev portal based on CNCF webinar.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#1062]
We want to create a blog post for the tanzu dev portal based on the CNCF webinar that was done on June 18th.

https://www.youtube.com/watch?v=XoFDIjRxmUw

**Comment by wwitzel3** [comment]
I keep getting pinged on this, anyone interested in taking this on?

**Comment by wwitzel3** [comment]
Process for submitting content is here: https://source.vmware.com/portal/pages/RnD/tanzu-dev-portal-content

**Comment by GuessWhoSamFoo** [comment]
@wwitzel3 I'll take this - when do we need this submitted?

**Comment by bryanfriedman** [comment]
@GuessWhoSamFoo Thanks for grabbing this. As soon as you can get to something would be great. Maybe shoot for publishing in 2 weeks or so, if that's doable.

**Comment by GuessWhoSamFoo** [comment]
@bryanfriedman @wwitzel3 
Here is the initial draft: https://hackmd.io/ECizgqA9Qk-RqeouuPLmJw
Let me know any feedback and we can aim to have this submitted by the the of week.

**Comment by bryanfriedman** [comment]
Awesome, will take a look and shoot to publish soon. Thank you! (Also, never used HackMD but it seems awesome...)

**Comment by GuessWhoSamFoo** [comment]
https://tanzu.vmware.com/developer/blog/debugging-a-kubernetes-workload-with-octant/
