### ISSUE TITLE
Using --namespace with custom namespace shows an empty Overview

### ISSUE THREAD

**Issue by jaimegag** [vmware-tanzu/octant#1086]
**What steps did you take and what happened:**
When starting Octant on a Windows machine and `--namespace` at runtime (with a custom namespace), with no access to list namespaces, Octant displays an empty Overview.
Left side controls are accessible and when clicking on them we see information with no issue.
When using `--namespace-list` we avoid the `namespace does not exist` error but still the Overview on the landing page is empty.

**What did you expect to happen:**
I expect the landing page to display an overview including information from the namespace the user has access to and specified at launch.

**Anything else you would like to add:**
User only has (edit) access to that custom namespace.
With a similar scenario launching Octant from a Mac I don't experience the same issue.
This is tied to issue #838 but specific to Windows in our tests

**Environment:**
Windows Server 2019. Chrome.

- Octant version (use `octant version`): 0.13.1
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows Server 2019

**Comment by wwitzel3** [comment]
I tested this under Windows 10 Insiders, using Chrome Version 83.0.4103.116 (Official Build) (64-bit) and was not able to replicate the issue.

Can you check the browser console for any errors?

**Comment by jaimegag** [comment]
Console error reads:
```
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:7777/assets/css/clr-ui.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE
```

**Comment by jaimegag** [comment]
We have reproduced the same issue with another user that has read/view permissions on all namespaces. But when selecting that namespace launching Octant the Overview is empty.
To add more confusions, it does not happen with other namespaces. The namespace in question has a lot of pods/svcs/deployments/sts, etc. Maybe there is something that breaks rendering the Overview.

**Comment by GuessWhoSamFoo** [comment]
Try running octant with `-vv` then navigating to that namespace and see if there is some relevant logging that can help us debug

**Comment by wwitzel3** [comment]
I would like to validate this with a RBAC restricted account that has access to a namespace, but no permissions to list namespaces. And ensure Octant does the right thing when provided a `--namespace`

**Comment by wwitzel3** [comment]
I attempted to verify this on current Octant running under Windows with an account that had access to a single namespace and no ability to list namespaces and Octant loaded correctly with the namespace populated in the Namespace drop down.

Please retry with a more recent version of Octant and re-open if you are still having issues.
