### ISSUE TITLE
How to access to a cluster from outside with a pre-build binary on windows?

### ISSUE THREAD

**Issue by phantomlsh** [vmware-tanzu/octant#1095]
Following is my circumstance:

I am currently on windows locally, and I want to use the octant locally to access and administer a remote cluster. I have the kubeconfig file locally.

I have tried `./octant --kubeconfig=[path of kubeconfig]` , but it keep saying that "unable to start runner: failed to init cluster client: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"

And I have tried to set environment variable as it says, but nothing different happens.

**Comment by GuessWhoSamFoo** [comment]
Hi @phantomlsh ! Can you try instead `./octant --kubeconfig "/path/to/kubeconfig"` and remove the equal sign?
