### ISSUE TITLE
Support sorting pods by age

### ISSUE THREAD

**Issue by JavierHernandezMontes** [vmware-tanzu/octant#1107]
**Describe the problem/challenge you have**
The order of the pods can't be sorted by date and can't be filtered by name.

**Describe the solution you'd like**
The pods to appear in chronological desc order and being able to filter by pod name in the pods menu

**Environment:**

- Octant version (use `octant version`):  0.13.1
- Kubernetes version (use `kubectl version`): 1.16.9
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):  Windows 10

**Comment by wwitzel3** [comment]
Support for filtering (#986) will be in our next release 0.14, which is likely happening sometime today. I'll leave this open to track the request of being able to sort pods in descending chronological order.
