### ISSUE TITLE
Dark mode not loading consistently with YAML editor

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#1130]
This can be seen from the TGIK on 07/17/2020

**Comment by GuessWhoSamFoo** [comment]
Also see this on current master when opening editor via apply yaml

**Comment by scothis** [comment]
@GuessWhoSamFoo do you have steps to reproduce? I'm not having any luck

**Comment by GuessWhoSamFoo** [comment]
Yes, I see this issue on firefox. Chrome looks okay. Haven't tried other browsers

**Comment by scothis** [comment]
This is caused by the default theme being dark for octant, but the default theme for the editor being light. Once the user interacts with the theme switcher then octant and the editor's themes are synchronized.
