### ISSUE TITLE
 flyouts are not sensitive to the bounds of the viewport

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#1154]
**Describe the problem/challenge you have**
Unable to access flayout menu when using browser scaling and the menu extend beyond the bottom of the browser frame.

**Anything else you would like to add:**
![image](https://user-images.githubusercontent.com/27317/88419548-67a61880-cdb3-11ea-883f-24eed4514041.png)

**Environment:**
Chrome on Windows

**Comment by scothis** [comment]
This is an issue any time the height of the browser window is smaller than the height of the navigation. It's unrelated to browser scaling. The flyouts are not sensitive to the bounds of the viewport. We also have issues where the top-level nav items can extend beyond the bottom of the viewport (or be covered by the theme toggle)

For users, a workaround is to use the expanded navigation which can scroll vertically.

**Comment by wwitzel3** [comment]
I'm going to close this and leave #1402 open since it is reported by a plugin author.
