### ISSUE TITLE
Octant truncates context name 

### ISSUE THREAD

**Issue by the-gigi** [vmware-tanzu/octant#1170]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I recently upgraded octant and the new UI truncates context names to 16 characters. I work with tens of clusters and the context names use this format `<cloud provider>-<project>-<region>-<environment>`. Those names are much longer than 16 characters and now I can't see my current context fully and I can't switch contexts from the dropdown.

This makes octant much less useful.

**What did you expect to happen:**

To see the full context name

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 

```
$ octant version
Version:  0.14.1
Git commit:  51ce7f6a7e87c9cfcabc9bf402dff7eda5d6986b
Built:  2020-07-20T23:52:37Z
```

- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by GuessWhoSamFoo** [comment]
Duplicate of #909 

This is an issue with the clarity component. While it is possible to modify the css to allow a few more characters to fit, the better approach is to implement a new component instead.

**Comment by the-gigi** [comment]
Missed #909.
