### ISSUE TITLE
Get blank contents in overview page and repeating exception in error log.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/octant#1172]
**What steps did you take and what happened:**

Am running Octant inside of a container for training purposes. It has a restricted RBAC. Neither of these appear to be the issue, as mostly it works, but in certain cases it fails when initially showing the Overview page for the namespace.

From various tests it seems that if Octant is started against an empty namespace (just default service account, token secret, some role bindings), it works fine from that point on. If however you deploy a workload before accessing Octant web interface (although Octant was started before the workloads were created), then it fails to display the overview page.

The URL directly targeted when accessing Octant the first time is of the form:

```
https://xxx/#/overview/namespace/lab-octant-testing-w01-s015
```

An explicit URL to the namespace was used when accessing it the first time, as on older versions if you used the root of the site it was being hit by rate limiting as it would query all namespaces and the contents of them, which would fail because of the restricted RBAC.

Result in the web interface is:

![image](https://user-images.githubusercontent.com/507637/88629715-f8059580-d0f2-11ea-9783-8f75e5bf3a5f.png)

The error logs are filled with:

```
2020-07-28T06:43:22.732Z        ERROR   api/content_manager.go:130      generate content        {"client-id": "9fbca94d-d09d-11ea-825e-0242ac110009", "err": "generate content: scheme convert: Object 'Kind' is missing in 'unstructured object has no kind'", "content-path": "overview/namespace/lab-octant-testing-w01-s015"}
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1
        /__w/octant/octant/internal/api/content_manager.go:130
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
        /__w/octant/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
        /__w/octant/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start
        /__w/octant/octant/internal/api/content_manager.go:106
```

Tried switching back to connecting the first time by using root URL for site to see if makes a difference, but it doesn't and still fails in the way described.

For the purposes of the training/demo, as a workaround, means have to tailor content to ensure people access Octant before deploying a workload. If this is done, and the workload only deployed after Octant is accessed the first time, then it works okay.

**What did you expect to happen:**

Expect the overview for the namespace to be shown.

**Anything else you would like to add:**

Am using ``--namespace`` option to have it start up against specific namespace as well.

**Environment:**

```
[~/exercises] $ octant version
Version:  0.14.1
Git commit:  51ce7f6a7e87c9cfcabc9bf402dff7eda5d6986b
Built:  2020-07-20T23:52:37Z
[~/exercises] $ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
[~/exercises] $ uname -a
Linux lab-octant-testing-w01-s017-65f9bb66cf-s7qmk 4.19.107 #1 SMP Thu Mar 26 11:33:10 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wwitzel3** [comment]
Can you share YAML for the RBAC setup for the account that is accessing Octant.

**Comment by wwitzel3** [comment]
From OP

```The service account used to access it has namespaced RoleBinding of "admin" for the single namespace it has access to, plus "get", "list" and "watch" on namespaces for cluster. Nothing else.```

**Comment by GrahamDumpleton** [comment]
Just dumping this here for now. Another consequence of restricted RBAC seems to be that on overview page, when trying to show details of a PVC, you are in turn trying to query something about the PV associated with it. With restricted RBAC this fails. The result is lots of noise in logs as it keeps polling trying to get the information about the PV.

```
│ 2020-07-28T23:34:18.153Z    ERROR    api/content_manager.go:130    generate cont │
│ ent    {"client-id": "d9c95a9d-d12a-11ea-b6d1-0242ac11000a", "err": "generate co │
│ ntent: get volume for key CacheKey[APIVersion='v1', Kind='PersistentVolume', Nam │
│ e='pvc-7fb42545-3bb9-46d3-bbfa-cd692c19a5c6']: check access for get to CacheKey[ │
│ APIVersion='v1', Kind='PersistentVolume', Name='pvc-7fb42545-3bb9-46d3-bbfa-cd69 │
│ 2c19a5c6']: get: CacheKey[APIVersion='v1', Kind='PersistentVolume', Name='pvc-7f │
│ b42545-3bb9-46d3-bbfa-cd692c19a5c6']", "content-path": "overview/namespace/lab-o │
│ ctant-testing-w01-s050"}                                                         │
│ github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1    │
│     /__w/octant/octant/internal/api/content_manager.go:130                       │
│ github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1     │
│     /__w/octant/octant/internal/api/poller.go:86                                 │
│ github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run           │
│     /__w/octant/octant/internal/api/poller.go:95                                 │
│ github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start              │
│     /__w/octant/octant/internal/api/content_manager.go:106
```

Possibly should not log details at all or otherwise work out not got sufficient RBAC to do query and in that case don't bother logging.

**Comment by GrahamDumpleton** [comment]
Don't know if this is related, but if start with ``--verbose`` I don't get the first error above repeating, but I do get the following message immediately after.

```
2020-07-29T02:16:46.588Z        INFO    objectstore/dynamic_cache.go:209        backing off for apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition (1.029518121s)
```

The role of the service account it runs as does not have the ability to read CRDs.

I'll try and set up a special role which greats read on ``crd`` type to see if it changes anything.

**Comment by GrahamDumpleton** [comment]
Giving it read access to CRDs, just cascades to a new error in logs since it can't read any of the actual different CR resources.

```
2020-07-29T02:36:01.559Z        INFO    objectstore/dynamic_cache.go:209        backing off for training.eduk8s.io/v1alpha1, Kind=WorkshopEnvironment (8.060322444s)  {"component": "websocket-client", "client-id": "36a11d94-d144-11ea-be3b-0242ac11000c", "poller-name": "navigation", "poller-instance": "a8055150-a52f-47e2-932e-5f4bc44a3cdb"}
2020-07-29T02:36:01.559Z        ERROR   api/navigation_manager.go:97    load namespaces {"component": "websocket-client", "client-id": "36a11d94-d144-11ea-be3b-0242ac11000c", "poller-name": "navigation", "poller-instance": "a8055150-a52f-47e2-932e-5f4bc44a3cdb", "err": "unable to generate navigation for module cluster-overview: generate entries for Custom Resources: listing custom resources for \"workshopenvironments.training.eduk8s.io\": check access to list CacheKey[APIVersion='training.eduk8s.io/v1alpha1', Kind='WorkshopEnvironment']: list: CacheKey[APIVersion='training.eduk8s.io/v1alpha1', Kind='WorkshopEnvironment']"}
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).runUpdate.func1
        /__w/octant/octant/internal/api/navigation_manager.go:97
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
        /__w/octant/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
        /__w/octant/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).Start
        /__w/octant/octant/internal/api/navigation_manager.go:86
```

This time rather than blank content in overview page, the spinner did at least show.

So very much looks like is connected to how it behaves when run with restricted RBAC and it can't read cluster level resources which only a cluster admin could read. In other words, where might only have access that a developer would have.

FWIW, this problem didn't exist with 0.12.1, which was the previous version being used. So something changed after that version.

**Comment by wwitzel3** [comment]
I don't know that this will fix this problem, but you can start Octant with the `--disable-cluster-overview` flag which will remove a lot of the noise around failing to load cluster scoped content and won't start the cluster level watchers.

**Comment by GrahamDumpleton** [comment]
The ``--disable-cluster-overview`` option appears that it may avoid the overview page coming up with empty content, but it doesn't eliminate that original error message coming up every second. Thus the error message would appear to be unrelated as far as what causes it isn't what was stopping the overview page showing content.

**Comment by GrahamDumpleton** [comment]
I wrongly posted a comment saying ``--disable-cluster-overview`` helped. I have deleted the comment now as it doesn't actually help. I was testing with the wrong version.

Using ``--disable-cluster-overview`` is different though, in that rather than being blank workshop content, get spinner instead.

**Comment by wwitzel3** [comment]
Was able to sync up with @GrahamDumpleton yesterday and debug this issue further. As hinted at here in the discussion, the issue was with trying to fetch the bound PV details for a PVC - where the client has view access to the PVC, but not to the bound PV. The result is Octant not seeing this as an access error and attempting to call `FromUnstructured` on an not-nil, but uninitialized `*unstructured.Unstructured` (meaning that `Unstructured.Object` was nil) which caused the Scheme code to throw an error (`Object 'Kind' is missing in 'unstructured object has no kind'"`).

**Comment by wwitzel3** [comment]
An experimental build was created for testing on the eduk8s instance (https://storage.googleapis.com/octant-nightlies/builds/experimental/octant-eduk8s-pv-fix). When using that binary, the Octant eduk8s training is able to run the latest version of Octant.

Working on getting a proper fix in to master.
