### ISSUE TITLE
Make context menu show the whole context name

### ISSUE THREAD

**Issue by fheinonen** [vmware-tanzu/octant#1183]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
The context name is truncated so much, that it isn't useful with an EKS context.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Don't truncate the context name, there is plenty of horizontal space to show the whole context name.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
<img width="514" alt="Screenshot 2020-07-30 at 10 13 38" src="https://user-images.githubusercontent.com/43732976/88892397-5cd50300-d24d-11ea-8c78-4e1e272a0fd4.png">

**Environment:**

- Octant version (use `octant version`): 0.14.1
- Kubernetes version (use `kubectl version`): 1.14.9
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.15.6 , Safari  13.1.2 (15609.3.5.1.3)

**Comment by wwitzel3** [comment]
duplicate #909

**Comment by wwitzel3** [comment]
There is a fix in master #1181
