### ISSUE TITLE
Context name is cut off when it is wider than the menu

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#1187]
<img width="583" alt="Screen Shot 2020-08-02 at 3 55 11 PM" src="https://user-images.githubusercontent.com/240/89131148-a1c09a00-d4d8-11ea-9183-5a5a42b5f9e6.png">

**Comment by GuessWhoSamFoo** [comment]
This should be fixed on master with #1181 

Duplicate with #1183 and #1170 - we should probably cut a release with this soon
