### ISSUE TITLE
Key#Selector should support searching for objects where a label exists, regardless of label value

### ISSUE THREAD

**Issue by ipsi** [vmware-tanzu/octant#1201]
**Describe the problem/challenge you have**
Currently, when using `Key` with the `Selector` field, you have to set a value for the key. This is a problem when you want to fetch _all_ objects where that label exists.

**Describe the solution you'd like**
This is supported by the K8s API, but in a part of the API that isn't directly used by `Key`.

Currently, `Key` uses `labels.Set` (which is defined as `type Set map[string]string`), and later on, in, e.g., `DynamicCache#listFromInformer` (`internal/objectstore/dynamic_cache.go:281`), we do this:

```
var selector = kLabels.Everything()
if key.Selector != nil {
    selector = key.Selector.AsSelector()
}
```

If it was possible to use [`kLabels.Selector`](https://pkg.go.dev/k8s.io/apimachinery@v0.18.6/pkg/labels?tab=doc#Selector) directly, it would be possible to do something like this:

```
newSelector := kLabels.NewSelector()
requirement, err := kLabels.NewRequirement("app", selection.Exists, []string{})
if err != nil {
	return nil, false, err
}
newSelector.Add(*requirement)
```

I'm not sure if the ideal solution is refactoring `Key` to use `kLabels.Selector` directly in `Key`, or if we should build a `Selector` from `Key#Selector`, and make assumptions that if, e.g., the value is an empty string, that means we're intending to use `selection.Exists` in the query.

**Anything else you would like to add:**
N/A

**Environment:**

- Octant version (use `octant version`): `2e4446a6`
- Kubernetes version (use `kubectl version`): `v0.19.0-alpha.3`
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.15.6

**Comment by wwitzel3** [comment]
extend store.Key to add the new selector type to support Exist/NotExist lookup semantics
consider adding support for all of the lookup options for selectors Equals, Contains, etc..
