### ISSUE TITLE
provide a breadcrumb navigation to other pages in a plugin

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#1212]
**Describe the problem/challenge you have**
Inside the [octant-jx](https://github.com/jenkins-x/octant-jx) we have a number of links to other pages (some inside the octant-jx plugin, some inside octant itself; e.g. the pod view for a tekton pipeline) - it would be nice to have quick way to navigate to them from the breadcrumb bar.

Similarly it'd be nice to be able to link to other pages; maybe a right aligned drop down menu for related views. e.g. when viewing a Pipeline in octant-jx it'd be nice to navigate to the Logs, the Pod, the Step definition, the Pull Request that triggered the pipeline, the preview application etc. There's not an obvious easy canonical way to have menus/links on a page to other related areas.

**Describe the solution you'd like**
Allowing a breadcrumb bar to have a little pull down menu so you can quickly navigate from one resource to another. E.g. on Workloads it might be nice to navigate to Deployments / Jobs quickly from a down arrow next to Workloads (without having to find where you are in the big left hand nav bar)?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by jstrachan** [comment]
here's an example screen shot - to switch to other octant-jx views you have to scroll all the way to the bottom of the nav bar to find the current plugin; sometimes the plugin icon is off the bottom of the screen. If you installed lots of plugins this could take you a while to find. Having some way to navigate from the top of the page on the nav bar would be awesome

<img width="585" alt="screenshot" src="https://user-images.githubusercontent.com/30140/89575378-9695a300-d825-11ea-8971-e3c72e29b031.png">

**Comment by wwitzel3** [comment]
This could be done by adding the Clarity Dropdown component to Octant https://clarity.design/documentation/dropdowns 
Then, in the same way we allow you to add Text / Link items to the title you could add a Dropdown which could contain Link items.
