### ISSUE TITLE
Request to view CRDs

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/octant#1250]
Octant only shows the custom resources but not the actual specs.

For example: in Velero, we have CRD for backups (and other things), but I can't only see the the backup after a backup is created, and even then I don't see the CRD itself, only the actual resource.

As a developer, as I change fields in my CRDs and deploy these changes to my cluster, it would be very useful to be able to verify the changes were properly deployed and also inspect the changes with Octant.

**Comment by scothis** [comment]
The general issue is that Octant doesn't know how to render the spec and status (assuming there is a spec and status) for the custom resource. If you want to see the raw YAML for the resource, click on the YAML tab. It will render fields described as additionalPrinterColumns on the CRD.

It would be interesting to see how far we could get with dynamically generating a view based on the content of the resource of the Open API schema. But I don't expect this to be very friendly.

Ultimately, we need to make it as dead simple as possible to register declarative views for CRDs. The current plug-in model is still too complex for simple use cases.

**Comment by scothis** [comment]
The ability to view history is tracked in #1132

**Comment by carlisia** [comment]
> If you want to see the raw YAML for the resource, click on the YAML tab.

That is what I want to see. However, unless there's an existing resource for that CRD, the CRD won't be listed so I can't.

**Comment by scothis** [comment]
> That is what I want to see. However, unless there's an existing resource for that CRD, the CRD won't be listed so I can't.

Ah yes. The navigation scheme around CRDs needs to be reconsidered. I typically have 50+ CRDs in my cluster, so a menu item per CRD is a bit much. Subgrouping the navigation items by api group before individually listing each kind may work.

**Comment by carlisia** [comment]
Hey y'all added a view for the CRDs, so I'm closing this. Thank you!

![image](https://user-images.githubusercontent.com/16508/95667680-33263b00-0b1e-11eb-84a4-e8403beb5657.png)
