### ISSUE TITLE
Move timestamp formatting to backend

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#1253]
The logic inside `relative.pipe.ts` should in handled from the backend and send a human readable timestamp in addition to the unix timestamp.

This allows removing dayjs from frontend dependencies and avoid running a pipe for each timestamp.

**Environment:**

- Octant version (use `octant version`): 0.15.0

**Comment by scothis** [comment]
What's the driver for this?

Generally it's a best practice to render timestamps as absolute values from APIs and convert them to relative, human friendly values in the client. This aids cacheability and unnecessary data transfer as well a locale specific date formatting. Granted, Octant retransfers the whole view currently, but we know that's not ideal.

**Comment by bryanl** [comment]
I believe we should continue sending times as numbers up to the frontend and letting it render. Believe it or not, rendering timestamps takes almost no time and we can do other things like enabling OnPush in components to ensure they aren't constantly updating. I would not make this change as it limits the flexibility of the frontend.

**Comment by GuessWhoSamFoo** [comment]
Closing this. Seems like the performance gains don't seem to be worth the tradeoffs.
