### ISSUE TITLE
Header should grow to fit content in narrow windows

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1268]
**What steps did you take and what happened:**

Open Octant in a narrow, but not tiny window. The header content overflows into the body area. This looks strange in dark mode and the content is nearly invisible in light mode.

**What did you expect to happen:**

All of the header content should be in the header.

**Anything else you would like to add:**

<img width="1025" alt="Screen Shot 2020-08-20 at 4 52 37 PM" src="https://user-images.githubusercontent.com/302992/90825780-69f28880-e307-11ea-9a76-bada094d2611.png">
<img width="1025" alt="Screen Shot 2020-08-20 at 4 52 34 PM" src="https://user-images.githubusercontent.com/302992/90825783-6a8b1f00-e307-11ea-87fd-b59d3cc973d0.png">

**Environment:**

- Octant version (use `octant version`): 0.15 and HEAD
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Safari (macOS 10.15)

**Comment by alexbarbato** [comment]
Unable to reproduce this on master. 

The header appears to be using clarity's default flex-basis to determine the height of the header so it automatically is causing the header to expand as things wrap for me.

Running locally, MacOS / Firefox (current on both).

**Comment by scothis** [comment]
Firefox works for me. Safari is still broken

**Comment by alexbarbato** [comment]
Derp.. helps if I read the bug report location. I just assumed it was a global bug - apologies!

Pushing a fix here momentarily.

**Comment by scothis** [comment]
> helps if I read the bug report location.

I edited the description to add Safari after you said it worked in Firefox. 😄

**Comment by alexbarbato** [comment]
Haha great I feel less crazy now!
