### ISSUE TITLE
Publish JS plugin types and apis on npm

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1271]
**Describe the problem/challenge you have**

When creating a new JS plugin, TypeScript definitions for component and the plugin API are included within the plugin. As new components and APIs are exposed to plugins, these files will need to be updated in every plugin.

**Describe the solution you'd like**

These types and other supporting libraries should be published on npm so they can be consumed and updated like any other module.

**Comment by wwitzel3** [comment]
Done https://www.npmjs.com/package/@project-octant/plugin
Repo for PRs/Issues: https://github.com/vmware-tanzu/plugin-library-for-octant
