### ISSUE TITLE
Feature request: Octant can be deployed in kubernetes cluster

### ISSUE THREAD

**Issue by warmchang** [vmware-tanzu/octant#134]
First of all, thanks to the developers of Octant.

Does the development team have plans to deploy Octant in the kubernetes cluster, the same as the kubernetes/dashboard?

**Comment by tomweston** [comment]
@warmchang Please see [examples](https://github.com/vmware/octant/blob/master/examples/in-cluster/) for in-cluster deployments. However, you will be required to build and publish your own Docker image as the one referenced in the `kustomization.yml` is not public.

Im working on a Helm chart for this, but have been super busy this week.. Will keep you posted 😀

**Comment by warmchang** [comment]
@tomweston thank you! :smile:

**Comment by pdbogen** [comment]
It'd be nice if octant supported in-cluster config (https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration) rather than _needing_ an explicit kubeconfig.

**Comment by 3r1co** [comment]
Hello,
we're facing the same issue and I wrote the little helper script below that uses the service account credentials before starting Octant. For sure the in-cluster config would be much better, but just for playing around it worked also like that :)

**launch.sh**
```
#! /bin/sh
server=https://kubernetes.default:443

ca=$(base64 -w 0 < /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

mkdir -p /root/.kube

echo "
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: ${namespace}
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: ${token}
" > /root/.kube/config
octant
```
**Dockerfile**
```
FROM alpine

ENV DOWNLOAD_URL https://github.com/vmware/octant/releases/download/v0.5.1/octant_0.5.1_Linux-64bit.tar.gz

RUN apk add --update curl tar && \
    curl -L $DOWNLOAD_URL | tar xz && apk del curl tar && \
    mv ./octant_0.5.1_Linux-64bit/octant $APP_BIN && \
    rm -rf ./octant_0.5.1_Linux-64bit

COPY launch.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/launch.sh

ENTRYPOINT ["launch.sh"]
```

**Comment by pvdvreede** [comment]
It would also be good if it can support forwarding a OIDC JWT passed in thru the `Authorization` header like the official k8s dashboard.

We use this method to integrate a user's access via our Org Auth system by putting a oidc client container in front that will get a JWT via OIDC and then just pass that thru on each request.

This means that the access level is dynamic per request so that people with different access levels can just use the single instance of the dashboard.

Does anyone know if that would be hard to implement here, given the setup seems pretty tied to a single auth context for the life of the instance?

**Comment by bryanl** [comment]
Octant requires the single auth to maintain the informers it uses to keep the frontend snappy. If we used a token per call, we couldn't take advantage of this.

**Comment by pvdvreede** [comment]
Thanks for the quick reply @bryanl ! Thought it might be the case we couldn't do it, so thanks for confirming 👍

**Comment by mengdie-song** [comment]
We have met the same issue here and thought it would be better for octant to support in-cluster config.

**Comment by wwitzel3** [comment]
See #450

**Comment by aleveille** [comment]
For what it's worth, I've made a ready-to-use published Docker image and Helm chart to deploy to Kubernetes: https://github.com/aleveille/octant-dashboard-turnkey

For anyone looking to deploy to Kubernetes, you can hop over there as I will likely maintain that repo for a couple months/years.
