### ISSUE TITLE
Feature request: Terminal connect to running container

### ISSUE THREAD

**Issue by cdan** [vmware-tanzu/octant#135]
Thanks for this great tool!
Is it possible to add a terminal tab to connect to running container to execute some scripts inside?

**Comment by bryanl** [comment]
This sounds like a great feature. The team is currently brainstorming how this would work. It's fairly complex as we don't currently have a terminal tab component.

**Comment by wwitzel3** [comment]
I put together some thoughts on this. I'm still thinking about this and will have some more edits later, but wanted to get this out so we could start the conversation.

https://hackmd.io/@wwitzel3/octant-container-exec

**Comment by GuessWhoSamFoo** [comment]
Some notes:
 - Browser terminal should support clipboard events
 - Where in the UI should be tracking all the existing terminals?
 - When do the terminal connection close?
 - Notifying user if terminal disconnects for other reasons
 - Look into xterm support for resizing

**Comment by wwitzel3** [comment]
I added some details about handling terminals in the UI and how we are going to deal with timeouts and disconnects. xtermjs supports resizing and clipboard/mouse support.
