### ISSUE TITLE
Octant does not start if cannot reach the current cluster

### ISSUE THREAD

**Issue by dsosedov-vmw** [vmware-tanzu/octant#1380]
**Describe the problem/challenge you have**
When the cluster from the current context is behind VPN and the user is not connected to that VPN, or the cluster is not reachable for any other reason, Octant fails to start with the following error:

```bash
unable to start runner: failed to start service api: unable to start CRD watcher: crd watcher has failed: check access to watch CacheKey[APIVersion='apiextensions.k8s.io/v1beta1', Kind='CustomResourceDefinition']: unable to get resource for group kind CustomResourceDefinition.apiextensions.k8s.io: Get "https://sc-stg-coreos-master.eng.vmware.com:6443/api?timeout=32s": dial tcp: lookup sc-stg-coreos-master.eng.vmware.com: no such host
```

**Describe the solution you'd like**
I would expect the app to still start but report the issue in the UI instead. I might have other clusters that are reachable but not in the current context that I would still want to view in the app.

**Environment:**

- Octant version (use `octant version`): 0.15.0
- Kubernetes version (use `kubectl version`): 1.15
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.15

**Comment by wwitzel3** [comment]
Thank you for reporting this, this is an interesting case. My initial thoughts are to do something like this:

- Log the error in to the error tab after #43 is closed out (currently being worked on)
- Create a modal or /failed-to-connect view that allows the user to retry the connection to the selected context

**Comment by dsosedov-vmw** [comment]
Sounds like a good solution. Thanks, @wwitzel3!

**Comment by wwitzel3** [comment]
This has been fixed in the latest version of Octant.
