### ISSUE TITLE
Events first/last seen can be null

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#1386]
**What steps did you take and what happened:**
Currently this shows as `737689d`.

**What did you expect to happen:**
Show `<unknown>` or null.

**Environment:**

- Octant version (use `octant version`): 0.15

**Comment by sladyn98** [comment]
@GuessWhoSamFoo would love to start on this. Any tips on how to begin

**Comment by wwitzel3** [comment]
I think the place I would start exploring is https://github.com/vmware-tanzu/octant/blob/master/internal/printer/event.go

I'd add a test to https://github.com/vmware-tanzu/octant/blob/master/internal/printer/event_test.go that provides null values for the first/last seen, then work in event.go to convert that in to a display value instead like `<uknown>` of `737689d`

**Comment by GuessWhoSamFoo** [comment]
Protip: use dev tools on chrome/firefox (ctrl + shift + i) > Network > stream. See what the server is returning for events in the json blob. The timestamp component converts a unix timestamp into a human readable format so there is likely some bad input causing an expected conversion.
