### ISSUE TITLE
Feature request: Disable cluster level menus and requests

### ISSUE THREAD

**Issue by moderation** [vmware-tanzu/octant#141]
We run very restricted clusters where developers only have access to their own namespaces. Access to default or system namespaces is not allowed via RBAC. Similarly access to cluster information is all blocked.

Feature request is to provide a flag or configuration to disable "Cluster Overview" menu and requests.

Related: https://github.com/vmware/octant/issues/142

**Comment by bryanl** [comment]
Hi, can your users see nodes? You can always collapse the menu. Perhaps we could explore this as a configuration option, but we would need to think through it since there is useful items in there. I brought up nodes because pods have a link to the node they run on.

**Comment by moderation** [comment]
Users cannot see nodes. My concern with having this menu enabled is that when  developer clicks it  it may SPAM our auth system that makes additional calls to external systems unnecessarily.

**Comment by mhoshi-vm** [comment]
Hi I see this issue closed but what is the fix for this ?
I also want to disable the cluster view

**Comment by moderation** [comment]
https://github.com/vmware-tanzu/octant/commit/1da294a450f4b77d6df235b524c0de6d14c3a916 added a `disable-cluster-overview` command line flag
