### ISSUE TITLE
Supplied initial namespace flag launches into 'default' namespace

### ISSUE THREAD

**Issue by moderation** [vmware-tanzu/octant#142]
We run very restricted clusters where developers only have access to their own namespaces. Access to default or system namespaces is not allowed via RBAC. Similarly access to cluster information is all blocked.

When launching with `./octant -n specific-namespace-name` the browser launches to the URL `http://127.0.0.1:<port>/#/content/overview/namespace/default/?`. The expected behavior would be to launch to `http://127.0.0.1:<port>/#/content/overview/namespace/specific-namespace-name?`

Related: https://github.com/vmware/octant/issues/33, https://github.com/vmware/octant/issues/141

**Comment by wwitzel3** [comment]
Thank you for reporting this issue. We have merged a fix in to master (#165) that will be available in the next binary release ~ August 20th.

**Comment by moderation** [comment]
Fantastic. Thanks very much.

**Comment by GuessWhoSamFoo** [comment]
Fixed via 3ebca1c696e3321f256c23e27cc3ded55fad0786
