### ISSUE TITLE
Allow plugins to specify a custom icon

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1422]
**Describe the problem/challenge you have**

Clarity has a nice generic set of computing related icons, but the odds of Clarity having an icon appropriate for a plugin, which are often tied to a specific project, is unlikely.

**Describe the solution you'd like**

Plugins should be able to define a custom navigation icon. For example, a Knative plugin should use the Knative logo, and not a generic cloud icon.

**Anything else you would like to add:**

Data URIs are a good way to avoid plugins needing to reference external assets. To aid theming and visual consistency, a single SVG stroke could be allowed that is then styled by the client to match the current theme.

**Comment by ftovaro** [comment]
I can take a look at this one, If I require more info I'll be posting it here
