### ISSUE TITLE
Updating a JS plugin should send a content event to the client

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1423]
**What steps did you take and what happened:**

When viewing a page that contains content contributed by a plugin, and the plugin is updated, the content on the page becomes stale until a content event refreshes it.

**What did you expect to happen:**

Loading a new or updated plugin should also trigger a content event to ensure the client has the updated view.

**Anything else you would like to add:**

This may be a side effect of no longer polling for updated content.

**Environment:**

- Octant version (use `octant version`): 0.16

**Comment by GuessWhoSamFoo** [comment]
As of 3913c2ff8a3cb75d56385423ea8dd6497a8c869c, it doesn't look like this is a problem anymore. I've added `Date().toLocaleString()` across a few components and updates are shown through new content events.

If there is a specific case (e.g. something like change detection not handled properly for a given component), feel free to re-open and I can take a look.

**Comment by wwitzel3** [comment]
This was specific to the hot reloading of JavaScript plugins right? That commit referenced doesn't seem to be related?

**Comment by GuessWhoSamFoo** [comment]
I meant based off the latest commit. Probably could bisect for the exact commit that ended up fixing this inadvertently but going to move on unless there's something missing here.
