### ISSUE TITLE
Allow plugins to contribute multiple tab responses

### ISSUE THREAD

**Issue by danielpacak** [vmware-tanzu/octant#1440]
**Describe the problem/challenge you have**

Octant is great and the extensions API allows me to add a single new tabs for the specified Kubernetes object. For example, in [Starboard plugin](https://github.com/aquasecurity/starboard-octant-plugin) we add the **Vulnerabilities**, which contains vulnerability reports for the given workload containers.

![plugin_multi_tabs](https://user-images.githubusercontent.com/1322923/94816267-dcbd4c00-03fb-11eb-9208-c289af33969c.png)

**Describe the solution you'd like**

Starboard also checks deployment descriptors for insecure configurations and we'd like to add another tab, next to the Vulnerabilities tab, which contains config audit report and is called **Configuration Audit**. 

**Anything else you would like to add:**

- We could always add a single generic tab called maybe Starboard, which contains tabbed pane inside, but this hides the intention of the tab or UI component contributed by the plugin.
- Support for multiple top level tabs will allow users to spot new items they can click and experiment with.
- It would be nice to have it in Go and Typescript APIs as we haven't migrated to Typescript yet

**Environment:**

- Octant version (use `octant version`): 0.16.0
- Kubernetes version (use `kubectl version`): any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): any

**Comment by GuessWhoSamFoo** [comment]
This is going to be a breaking API change if the tab response is to return a list of tabs. Another aspect to start considering is tab order across one or more plugins.
