### ISSUE TITLE
In Go extensions API provide utility method to create the Link ref for the specified Kubernetes object

### ISSUE THREAD

**Issue by danielpacak** [vmware-tanzu/octant#1444]
**Describe the problem/challenge you have**

In our Starboard plugin, which is implemented in Go, we are displaying custom resources that have owner references set. To create the UI Link components we'd have to reverse-engineer the logic to build such URL refs. For example, we'd like to link to a Deployment or ReplicaSet with the given name in the specified namespace.

![plugin_go_link_builder](https://user-images.githubusercontent.com/1322923/94941972-f3d06c80-04d5-11eb-9f2b-2d9dd0e502e4.png)

**Describe the solution you'd like**

Go API method to construct `Link` components for the specified `ObjectMeta` and/or `OwnerReference`. A similar method exists for JS/TS: https://github.com/vmware-tanzu/octant/blob/master/pkg/plugin/javascript/dashboard_ref_path.go

**Anything else you would like to add:**

N/A

**Environment:**

- Octant version (use `octant version`): 0.16.0
- Kubernetes version (use `kubectl version`): any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): any

**Comment by ftovaro** [comment]
I'll be working on this issue
