### ISSUE TITLE
cannot upgade to 0.16.0 of octant in Jenkins X plugin

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#1457]
I tried to upgrade to 0.16.0 of octant for the Jenkins X plugin and all requests for data fail. I see this in the log...

```
2020-10-06T08:50:01.874+0100	ERROR	api/content_manager.go:154	generate content	{"client-id": "7ebc357a-07a8-11eb-8f98-acde48001122", "err": "generate content: grpc client content: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (10784 vs. 0)", "content-path": "jx/repositories"}
```

Doesn't matter what request I try; they all think that 0 is the maximum payload. 

I guess somewhere there's a way to set this to a non-zero value? Tried the octant CLI arguments to set it large and it makes no difference. 

Anyone any idea how to get things to work again on 0.16?

**Comment by wwitzel3** [comment]
Fixed by https://github.com/vmware-tanzu/octant/pull/1441/files

If you grab a nightly and test it out, that should verify the fix for the JX plugin.
We are cutting 0.16.1 tomorrow which will include that fix.

**Comment by wwitzel3** [comment]
https://console.cloud.google.com/storage/browser/octant-nightlies

**Comment by jstrachan** [comment]
@wwitzel3 many thanks - thats awesome & super fast!
