### ISSUE TITLE
clarity icons stopped working in go plugin; is there alternative markup/markdown?

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#1460]
we've been using the lovely clarity icons inside markdown for things like ticks/crosses for indicating pipeline status. After upgrading to 0.16.x these get stripped out and do nothing now.

I wonder is there any way around this; or alternative markdown / markup we can use going forward? 

e.g. we were using markup like...

```html
<clr-icon shape="check-circle" class="is-solid is-success" title="Succeeded"></clr-icon>
or
<clr-icon shape="warning-standard" class="is-solid is-danger" title="Failed"></clr-icon>
```
though it looks like we can still use badges or spinners...

```html
<span class="spinner spinner-inline" title="Running"></span>
```

**Comment by wwitzel3** [comment]
Oh interesting, I would still expect that to work. We'll take a look and get that in to the next release as well.

**Comment by wwitzel3** [comment]
Likely this happened when we rev'd our packages https://github.com/vmware-tanzu/octant/commit/b2e5c124c3b98490ccc5a81f339ed3f150fde28d we went from ngx-markdown 8 to 10. I'll dig in to the why.

**Comment by jstrachan** [comment]
BTW more than happy to change to whatever markup/html we can find that works

**Comment by wwitzel3** [comment]
Nope, the way you are doing it now is just fine, in fact, it is a pattern that we want to continue to enable, fix #1463 will be in the next bug fix release (tomorrow)

**Comment by jstrachan** [comment]
@wwitzel3 many thanks!

**Comment by wwitzel3** [comment]
I made another pass at fixing this that would require some changes on the plugin side, you'd have to set the `trustedContent`. See #1469
