### ISSUE TITLE
In Custom Resources view the Resource Age column is not formatted properly

### ISSUE THREAD

**Issue by danielpacak** [vmware-tanzu/octant#1462]
**What steps did you take and what happened:**

1. Define a CR and create an instance of it. For example:
   ```
   $ kubectl apply -f https://github.com/aquasecurity/starboard/blob/master/kube/crd/vulnerabilityreports-crd.yaml
   $ kubectl apply -f https://github.com/aquasecurity/starboard/blob/master/kube/examples/vulnerabilities.yaml
   ```
2. Navigate to the CR instance in Octant UI
   <img width="1534" alt="octant_resource_age" src="https://user-images.githubusercontent.com/1322923/95220572-e6c5bd00-07f6-11eb-84ad-8b1df911be08.png">
3. As you can see the **Resource Age** column is not formatted as date. What's more even if the CR defines Age as additional printer column the CR views renders the redundant **Resource Age** column

**What did you expect to happen:**

1. If a CRD does not define Age as additional printer column then format **Resource Age** column as date. BTW, I'd probably rename **Resource Age** to **Age** to be consistent with kubectl output
2. If a CRD defines Age as additional printer column then format **Age** column as date and do not display **Resource Age** column.

**Anything else you would like to add:**

N/A

**Environment:**

- Octant version (use `octant version`):  0.16.0
- Kubernetes version (use `kubectl version`): 0.19.1
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.15

**Comment by lenriquez** [comment]
@wwitzel3 if you don't mind I can take this one
