### ISSUE TITLE
Support search capability in YAML windows

### ISSUE THREAD

**Issue by chipzoller** [vmware-tanzu/octant#1485]
**Describe the problem/challenge you have**
When attempting to live edit a YAML definition when there are many lines, it can be difficult to pinpoint the exact one desired.

**Describe the solution you'd like**
Add a simple search field in all YAML editor tabs that can allow searching for a given string. The matches should be highlighted in the YAML definition.

**Anything else you would like to add:**
Octant rules.

**Environment:**

- Octant version (use `octant version`): 
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by wwitzel3** [comment]
If you have the YAML viewer/editor active, Ctrl-F will open the Monaco find dialog.

![image](https://user-images.githubusercontent.com/27317/95667922-ab9af500-0b3a-11eb-8df2-7a382ac53140.png)

**Comment by chipzoller** [comment]
Thank you, did not know this! Closing request.
