### ISSUE TITLE
Configuration is not loaded properly

### ISSUE THREAD

**Issue by MOZGIII** [vmware-tanzu/octant#150]
I got this error:
```
failed to init cluster client: invalid configuration: [context was not found for specified context: c1-admin@c1, cluster has no server defined]
```

Context for my `c1` cluster is defined at a separate file, and it's referenced via `KUBECONFIG`:

```shell
$ echo $KUBECONFIG 
/home/me/.kube/config:/home/me/.kube/config.d/c1
```

`kubectl` wotks properly with this setup.

**Comment by bryanl** [comment]
This issue has been resolved in #164. Please reopen if this is not the case.

**Comment by peterrosell** [comment]
This worked in version 0.6.0-0.8.0, but not anymore. Tested in version 0.9.0 and 0.9.1. I'm running on Ubuntu 18.04 and have two files specified via the environment variable KUBECONFIG.

**Comment by wwitzel3** [comment]
Fixed in master, will be apart of the nightly build tomorrow.
