### ISSUE TITLE
Normalize form capabilities

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1504]
**Describe the problem/challenge you have**

The `form` component is used by the `modal` and `summary` components to render forms. The `stepper` component has its own form renderer that adds support for things like placeholders and validation.

**Describe the solution you'd like**

There should be a single system for defining forms so that experience can port between modals, summaries and steppers. 

**Environment:**

- Octant version (use `octant version`): 0.16.1

**Comment by lenriquez** [comment]
I am working on this one

**Comment by wwitzel3** [comment]
Currently we have forms embedded across many different components. For example the Modal, Stepper, and Cards all have form elements, but don't use a unified `FormComponent`.

Investigate what it would take to create a standard FormComponent and then use that component in the various places we want to render forms.

**Comment by wwitzel3** [comment]
Created #2223 to track the creation of the form component which will then be used to normalize the behavior.
