### ISSUE TITLE
Use OpenAPI schemas for validation and completion in editor

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1505]
**Describe the problem/challenge you have**

The editor component has basic understanding of content types (like yaml), but has no understanding of the semantic structure of a kubernetes resource.

**Describe the solution you'd like**

Many resources now have an OpenAPI schema that can be used to validate the document before submitting to the API Server, and more importantly, can provide contextual help and hints as the user is editing the document.

**Comment by wwitzel3** [comment]
duplicate see #520 Epic and https://github.com/vmware-tanzu/octant/issues/526
