### ISSUE TITLE
Automatically fold .metadata.managedFields in editor

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1506]
**Describe the problem/challenge you have**

Kubernetes introduced a new data structure to track which client is managing specific fields of a resource. This structure is near the top of the document, can be very large and is typically of little interest to users.

**Describe the solution you'd like**

When the editor is displaying a yaml document, the content of `.metadata.managedFields` should be folded by default. A user can expand the folding if they desire to see the content.

**Anything else you would like to add:**

https://kubernetes.io/docs/reference/using-api/api-concepts/#field-management

**Comment by GuessWhoSamFoo** [comment]
xref: #2388
