### ISSUE TITLE
Allow plugins to get the current label filter and observe changes

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1512]
**Describe the problem/challenge you have**

Similar to how namespace changes can be observed in plugins to change the queries and data rendered, plugins also need to observe the label filters applied in Octant.

**Describe the solution you'd like**

When a `addFilter`, `removeFilter` or `clearFilter` action is fired, a new action `setFilter` should be fired containing the updated aggregate filter state in its payload. There should also be a way to lookup the current filter state without observing changes.

**Environment:**

- Octant version (use `octant version`): 0.16.1

**Comment by wwitzel3** [comment]
Has some cross over with #1513 , with this being specific to labels. Who ever ends up implementing either of these will likely find it easy to both at the same time.
