### ISSUE TITLE
Wrong navigation items are selected for deep paths in a plugin

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#1535]
**What steps did you take and what happened:**

When navigating to a deeply nested link managed by a plugin, the wrong navigation item is highlighted and the wrong sub nav is shown. I don't see this behavior with the built-in navigation items.

Paths like `/knative` and `/knative/serving`, show the correct navigation, but deeper paths like `/knative/serving/services` show the wrong navigation menu.

<img width="1029" alt="Screen Shot 2020-10-21 at 11 14 36 AM" src="https://user-images.githubusercontent.com/302992/96741043-6921b580-138f-11eb-98e8-371ca22381c1.png">

**What did you expect to happen:**

The plugins navigation items and menu should be shown when viewing a page defined by that plugin

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): HEAD

**Comment by scothis** [comment]
#1536 improves the situation, but doesn't solve the root issue. Now the navigation correctly works one level deeper, but still breaks with deep paths.

**Comment by wwitzel3** [comment]
Fixed by #1584
