### ISSUE TITLE
Pods running on each node

### ISSUE THREAD

**Issue by bbgobie** [vmware-tanzu/octant#1540]
**Describe the problem/challenge you have**
Currently when you do kubectl describe node <nodename>
At the end you get a list of pods running on the node along with the resources they're using.
It would be great if this info was available under the node view as well.
Even better if the resource usage had nice graphs

**Describe the solution you'd like**
An easy way to see what pods are using up resources on a node

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version : Version:  0.16.1
Git commit:  8aebb34922f83894fb02ad393740e96ee1b3d8fe
Built:  2020-10-07T23:36:32Z
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}    
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10

**Comment by alexbrand** [comment]
I'll pick this up if no one is working on it.

**Comment by alexbrand** [comment]
I've got a branch with an implementation (https://github.com/alexbrand/octant/tree/node-pods), but I need the ability to sort a table by multiple columns, which is being worked on here: https://github.com/vmware-tanzu/octant/pull/1566

**Comment by bbgobie** [comment]
Thanks for taking a look at this so quickly

**Comment by zparnold** [comment]
Well crap, I saw this a bit too late...I too made a PR 😂
