### ISSUE TITLE
A lot of resources aren't shown in Resource view of deployments and probably others

### ISSUE THREAD

**Issue by bbgobie** [vmware-tanzu/octant#1541]
**Describe the problem/challenge you have**
Under resource viewer, I don't currently see config maps, pvcs/pvs etc

**Describe the solution you'd like**
Under the resource view of say a Deployment or Service I would expect to see resources such as PVCs/PVs, configmaps etc. Everything required for that resource, similar to doing a kubectl describe

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`):  Version:  0.16.1
Git commit:  8aebb34922f83894fb02ad393740e96ee1b3d8fe
Built:  2020-10-07T23:36:32Z
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10

**Comment by alexbrand** [comment]
Gonna look into this 
/assign
