### ISSUE TITLE
Terminal keeps crashing, High cpu usage when that happens

### ISSUE THREAD

**Issue by akshaysgithub** [vmware-tanzu/octant#1558]
Hello, 

I am using Octant for Kubernetes dashboard. For most part it's working good, except we are expereincing issues with the terminal. When we use it for 5-10 minutes, we get this error in console and terminal crashes. Also, there is a High cpu usage at this point. I am using nginx proxy pass to proxy_pass connection to port-7777. We also have basic auth. 

Error log : 
`

Source map error: Error: request failed with status 404
Resource URL: https://kube.dashboard.roobeo.io/lib/vs/editor/editor.main.js
Source Map URL: ../../../min-maps/vs/editor/editor.main.js.map

received websocket unknown message of type handlerError with 
Object { error: "action path \"action.octant.dev/setNamespace\" not found", requestType: "action.octant.dev/setNamespace" }
`

What am I missing? Kindly let me know. Thank you. :-)

**Comment by wwitzel3** [comment]
Is there any error output in the terminal where you started Octant?

**Comment by akshaysgithub** [comment]
> Is there any error output in the terminal where you started Octant?

No, it's actually successful, I am starting without the browser open... This is the command I use : 

OCTANT_DISABLE_OPEN_BROWSER=true KUBECONFIG=/home/ubuntu/.kube/config OCTANT_LISTENER_ADDR=0.0.0.0:7777 octant

Then from nginx, I am using reverse proxy via proxy_pass http://localhost:7777/;

**Comment by wwitzel3** [comment]
Can you replicate this behavior to your cluster running Octant locally with the `-v` flag enabled and share the log file.

**Comment by akshaysgithub** [comment]
@wwitzel3 I tried that approach, nothing. It just goes slow... The logs are displayed on screen directly.

**Comment by akshaysgithub** [comment]
@wwitzel3 I have found this when the issue happens

`constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1910 clients constructed calling "aws-iam-authenticator"
`

nohup.out is filled with this

**Comment by ankitm123** [comment]
This is actually related to this: https://github.com/kubernetes/kubernetes/issues/91913, most probably not an octant issue, and a kubectl one, may be the warning (it's not an error) can be removed from the octant log ...

**Comment by billinghamj** [comment]
It really would be lovely to see this getting fixed: <img width="1792" alt="Screenshot 2021-01-23 at 00 24 41" src="https://user-images.githubusercontent.com/905772/105562249-64172e00-5d11-11eb-860c-372bb947eec7.png">

**Comment by GuessWhoSamFoo** [comment]
Haven't tried it yet, but https://github.com/kubernetes/kubernetes/pull/97857 fixes this. 1.21 doesn't come out until April though

**Comment by lenriquez** [comment]
Is this issue resolved?

**Comment by GuessWhoSamFoo** [comment]
Closed via #2678
