### ISSUE TITLE
Show image manifest for containers

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#156]
Show image manifest for containers, so users can know exactly which
image they are running. This will be helpful if you are using 
images with `latest` tag.

**Comment by wwitzel3** [comment]
Manifest Schema https://docs.docker.com/registry/spec/manifest-v2-2/

**Comment by wwitzel3** [comment]
Tools that can extract image information without needing `docker`
https://github.com/containers/skopeo
