### ISSUE TITLE
Mistakes in log representation (xml tags are removed) 

### ISSUE THREAD

**Issue by popfalushi** [vmware-tanzu/octant#1582]
Hi!
I read logs through octant and see smth like this:
`{"@timestamp":"2020-11-01T11:56:45.909Z","level":"INFO","class":"rs.jms.message.received.from.mq","message":"GenericMessage [payload=2020-11-01T14:56:45BrokerCreateOpty100B2F2E5E64EDB65E6E0533CA0A8C03EDD4c020f7acfd84c2d8af05dfbd1404e1cSIEBELSIEBELmcs-posbroker-api1.002-1OGXGXFW0, headers={JMS_IBM_Character_Set=UTF-8, errorChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@b8364f77, JMS_IBM_MsgType=8, jms_destination=queue://WMB02PQM/POS_CBCREATEOPTY_SIEBEL_RES, JMSXUserID=siebel , JMS_IBM_Encoding=273, priority=4, jms_timestamp=1604231805837, JMSXAppID=WebSphere MQ Client for Java, JMS_IBM_PutApplType=28, JMS_IBM_Format=MQSTR , replyChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@b8364f77, jms_redelivered=false, JMS_IBM_PutDate=20201101, JMSXDeliveryCount=1, jms_correlationId=784b0c72-8937-4615-b911-54b656e82460, ws_soapAction=\"document/http://siebel.com/CustomUI:CreateOpty_spcv2\", JMS_IBM_PutTime=11564589, jms_type=SiebelJMSMessage, id=fa092de7-e6c7-a00e-3647-d3c6a8eae2fe, jms_messageId=ID:414d5120574d42303250514d20202020667e9e5f298f3623, timestamp=1604231805909}]","trace":"","span":"","parent":"","thread":"http-nio-8080-exec-9"}`

When I look at the same log with Lens or download log file manually and look into it with Notepad++, I see this:
`2020-11-01T11:56:45.910889701Z {"@timestamp":"2020-11-01T11:56:45.909Z","level":"INFO","class":"rs.jms.message.received.from.mq","message":"GenericMessage [payload=<?xml version=\"1.0\" encoding=\"UTF-8\"?><ns:Message\n xmlns:ns=\"http://otpbank.ru/Message\"\n><MessageHeader\n><MessageDate\n>2020-11-01T14:56:45</MessageDate\n><ProcessID\n>Broker</ProcessID\n><MessageType\n>CreateOpty</MessageType\n><MessageID\n>100B2F2E5E64EDB65E6E0533CA0A8C03EDD</MessageID\n><IntegrationID\n>4c020f7acfd84c2d8af05dfbd1404e1c</IntegrationID\n><InitiatorSystem\n>SIEBEL</InitiatorSystem\n><SourceSystem\n>SIEBEL</SourceSystem\n><TargetSystemList\n><TargetSystem\n>mcs-posbroker-api</TargetSystem\n></TargetSystemList\n><Version\n>1.0</Version\n><ResultInfo\n><Code\n>0</Code\n><Description\n></Description\n><Exception\n></Exception\n></ResultInfo\n></MessageHeader\n><MessageBody\n><CreateOptyResponse\n><Opty_Id\n>2-1OGXGXFW</Opty_Id\n><Error_Code\n>0</Error_Code\n><Error_Message\n></Error_Message\n></CreateOptyResponse\n></MessageBody\n></ns:Message\n>, headers={JMS_IBM_Character_Set=UTF-8, errorChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@b8364f77, JMS_IBM_MsgType=8, jms_destination=queue://WMB02PQM/POS_CBCREATEOPTY_SIEBEL_RES, JMSXUserID=siebel      , JMS_IBM_Encoding=273, priority=4, jms_timestamp=1604231805837, JMSXAppID=WebSphere MQ Client for Java, JMS_IBM_PutApplType=28, JMS_IBM_Format=MQSTR   , replyChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@b8364f77, jms_redelivered=false, JMS_IBM_PutDate=20201101, JMSXDeliveryCount=1, jms_correlationId=784b0c72-8937-4615-b911-54b656e82460, ws_soapAction=\"document/http://siebel.com/CustomUI:CreateOpty_spcv2\", JMS_IBM_PutTime=11564589, jms_type=SiebelJMSMessage, id=fa092de7-e6c7-a00e-3647-d3c6a8eae2fe, jms_messageId=ID:414d5120574d42303250514d20202020667e9e5f298f3623, timestamp=1604231805909}]","trace":"","span":"","parent":"","thread":"http-nio-8080-exec-9"}
`

It seems like all tags are removed from log and it is not right. Seems like too careful XSS protection )

**Environment:**

- Octant version (use `octant version`): 

`Version: 0.16.1
Commit: 8aebb34922f83894fb02ad393740e96ee1b3d8fe
2020-10-07T23:32:09Z`

- Kubernetes version (use `kubectl version`):
`
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}`

- OS: Windows 10

**Comment by mklanjsek** [comment]
Cherry picked to 0.16.2
