### ISSUE TITLE
Provide APIs to create and delete resources for plugins to use

### ISSUE THREAD

**Issue by mengdie-song** [vmware-tanzu/octant#1599]
**Describe the problem/challenge you have**
I would like to switch to DashboardClient for antrea-octant-plugin, so that the plugin can pick up context switches from octant dashboard. My plugin needs to create and delete specific CRDs which can be supported by plugin self-generated client using client-go and kubeconfig previously. However, there are no APIs for create and delete resources defined in Dashboard interface (https://github.com/vmware-tanzu/octant/blob/master/pkg/plugin/service/dashboard.go#L16) which I can invoke. It would be great if octant can provide create and delete resources APIs for plugin to use.

**Describe the solution you'd like**
Add Create and Delete APIs to Dashboard interface with their implementations, so that plugins can use to create and delete resources of their own.

**Environment:**

- Octant version (use `octant version`): 0.16.1
- Kubernetes version (use `kubectl version`): v1.18.5
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):Ubuntu 18.04.3

**Comment by wwitzel3** [comment]
Got another request for this on the Go plugin side of things, adding this to our 0.19 release.

**Comment by xtreme-vikram-yadav** [comment]
Picking it up
