### ISSUE TITLE
Duplicate resources for CRDs with multiple conversionReviewVersions

### ISSUE THREAD

**Issue by pianohacker** [vmware-tanzu/octant#1715]
**Describe the problem/challenge you have**
I have a lot of custom resources in my cluster from Knative, and a lot of them are duplicated under both ...knative.dev/v1 and ...knative.dev/v1beta. I'm guessing this is due to the CRDs specifing multiple conversionReviewVersions, but it's a bit odd. (It would probably be a lot more aggravating if I had more of these resources.)

What's more frustrating is trying to edit these resources. If I try to edit any of the copies of the resource that isn't the most recent version, I get an error that the api version was not the expected one.

**Describe the solution you'd like**
Would it be feasible to either indicate that the most recent version is the only editable and "correct" version, or hide the old versions completely?

**Environment:**
- Octant version (use `octant version`): Git commit:  06f530e0
- Kubernetes version (use `kubectl version`): v1.19.4
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Debian testing

**Comment by wwitzel3** [comment]
> Jesse Weaver  9 minutes ago
If I'm being completely selfish about my use case, I don't want to see the old API versions at all. For these CRDs, it seems like I can view the resources as any version but only edit them as the most recent version. This makes the old versions strictly duplicative.
That being said, I didn't create those objects then upgrade the CRDs. No idea what that experience looks like :)
