### ISSUE TITLE
Not able to traverse through the logs, only one page of logs able to see

### ISSUE THREAD

**Issue by gopaltirupur** [vmware-tanzu/octant#1735]
**What steps did you take and what happened:**
Goto workloads -> pods and click Logs tab and select  "1 Hour" in Since. This gives only one page of log not the entire one.

**What did you expect to happen:**
Need to see the entire logs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Octant : 
0.16.3
656c7404e529262861eacb13e88d33dccd6035bf
2020-12-09T23:54:58Z

minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5-dirty

Linux version 4.4.0-21-generic (buildd@lgw01-21) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016

**Comment by wwitzel3** [comment]
Hi @gopaltirupur ,

Does the `Since Creation` option not show you the entire log?
![image](https://user-images.githubusercontent.com/27317/102093084-c0239400-3dee-11eb-9ea9-00f6e5426f16.png)

**Comment by wwitzel3** [comment]
I'm going to close this out, but if you are still having issues seeing all of the logs please re-open and we'll try to help.
