### ISSUE TITLE
Remove rice box from build tools

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#1750]
https://tip.golang.org/doc/go1.16#library-embed

Go 1.16 offers support for embedded files. This should simplify build steps and reduce friction for a development environment. As part of the dependency bump, we should:

- Clean rice-box.go (which is currently ignored by git)
- Update Github action workflows
- Remove reference from `tools.go`; update `go.mod`
- Re-bundle `dist/dash-frontend` currently handled in `web/web.go`

**Comment by wwitzel3** [comment]
Blocked by the official release of Go 1.16.

If someone wants to try this against 1.16 beta and put it as a draft PR while we wait for the release, that would be great.

**Comment by xtreme-vikram-yadav** [comment]
I picked this issue today
