### ISSUE TITLE
Not able to start Octant with supervisor 

### ISSUE THREAD

**Issue by akshaysgithub** [vmware-tanzu/octant#1777]
Hello,

I am using Octant for our daily Kubernetes dashboard usage. It's working out good, many thanks for that. For our testing environments I would like to automate the startup and shutdown for Octant. Currently we are using supervisor for our other services, but after trying for Octant, it's not working out, I tried various combinations, but it keeps failing. Is there anyway I can run Octant in background always, via a service-manager like supervisor. 

Supervisor.conf 

```
[supervisord]
nodaemon=true

[program:octant]
user=ubuntu
numprocs=1
autostart=true
autorestart=true
startsecs=1
command=OCTANT_DISABLE_OPEN_BROWSER=true KUBECONFIG=/home/ubuntu/.kube/config OCTANT_LISTENER_ADDR=0.0.0.0:7777 octant
killasgroup=true
redirect_stderr=true

```

Few other combinations for command I tried: 

`
OCTANT_DISABLE_OPEN_BROWSER=true KUBECONFIG=/home/ubuntu/.kube/config OCTANT_LISTENER_ADDR=0.0.0.0:7777 nohup octant`

/home/ubuntu/octant.sh which basically contained the commands with nohup. 

Any idea. THanks a lot. I also was wondering why Octant takes parameters in reverse order, why not application_name first and then the commands.

**Comment by GuessWhoSamFoo** [comment]
Although not officially supported (see roadmap on electron), this should be possible. What does `supervisord.log` look like? Can you run Octant as a standalone binary in that environment? What does failing mean here? (e.g. maybe it's a misconfigured proxy or is octant not starting?)

All of the environment variables can also be written as flags (e.g. `octant --disable-open-browser`).

**Comment by akshaysgithub** [comment]
> Although not officially supported (see roadmap on electron), this should be possible. What does `supervisord.log` look like? Can you run Octant as a standalone binary in that environment? What does failing mean here? (e.g. maybe it's a misconfigured proxy or is octant not starting?)
> 
> All of the environment variables can also be written as flags (e.g. `octant --disable-open-browser`).

Where can I find these command line parameters u mentioned, I will just add it as a service then

**Comment by GuessWhoSamFoo** [comment]
```
$ octant --help
octant is a dashboard for high bandwidth cluster analysis operations

Usage:
  octant [flags]
  octant [command]

Available Commands:
  help        Help about any command
  version     Show version

Flags:
      --context string                 initial context
      --disable-cluster-overview       disable cluster overview
      --enable-feature-applications    enable applications feature
      --kubeconfig string              absolute path to kubeConfig file
  -n, --namespace string               initial namespace
      --namespace-list strings         a list of namespaces to use on start
      --plugin-path string             plugin path
  -v, --verbose                        turn on debug logging
      --client-max-recv-msg-size int   client max receiver message size (default 16777216)
      --accepted-hosts string          accepted hosts list [DEV]
      --client-qps float32             maximum QPS for client [DEV] (default 200)
      --client-burst int               maximum burst for client throttle [DEV] (default 400)
      --disable-open-browser           disable automatic launching of the browser [DEV]
  -c, --enable-opencensus              enable open census [DEV]
      --klog-verbosity int             klog verbosity level [DEV]
      --listener-addr string           listener address for the octant frontend [DEV]
      --local-content string           local content path [DEV]
      --proxy-frontend string          url to send frontend request to [DEV]
      --ui-url string                  dashboard url [DEV]
      --browser-path string            the browser path to open the browser on
  -h, --help                           help for octant

Use "octant [command] --help" for more information about a command.
```

**Comment by GuessWhoSamFoo** [comment]
Closing as stale. Feel free to re-open is this is still an issue.
