### ISSUE TITLE
Installing a plugin requires restart of main octant process.

### ISSUE THREAD

**Issue by n3wscott** [vmware-tanzu/octant#178]
I installed the sample plugin and it did not show up until I restarted.

**Comment by ImJasonH** [comment]
+1, This also makes plugin development a bit more painful, since I have to rebuild my plugin and restart Octant to see changes.

**Comment by jdolitsky** [comment]
Hi, I ran into the same issue. Needing to restart octant to check plugin changes during development etc.

I put together this script to autobuild the plugin and restart octant on source changes: https://gist.github.com/jdolitsky/34b67113afe515e096064a4d01fd4dd6

**Comment by jdolitsky** [comment]
Would it be useful to add some flag like `--watch-plugins`  that periodically re-checks/re-loads the plugin directory?

**Comment by bryanl** [comment]
Octant should be able to restart a plugin or plugins. Or perhaps you kill the plugin and Octant could could restart registered plugins. We will draft upma solution and tag the issue.

**Comment by ImJasonH** [comment]
Just heard of this script to help with plugin development, which looks promising: https://gist.github.com/jdolitsky/34b67113afe515e096064a4d01fd4dd6

I haven't tried it yet, but I plan to when I have time to play with plugin development again.

**Comment by jdolitsky** [comment]
> Octant could restart registered plugins

That would work great. I just tried to kill the plugin process manually, and Octant falls into a bad state, w/ this in the logs over and over:
```
err in navigation: grpc client response: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /var/folders/51/0bdn93qj1s98v438m1y357lw0000gn/T/plugin228550586: connect: connection refused"2019-11-16T23:37:51.773-0600	ERROR	api/navigation_manager.go:97	load namespaces	{"poller-name": "navigation", "err": "grpc client response: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: error while dialing: dial unix /var/folders/51/0bdn93qj1s98v438m1y357lw0000gn/T/plugin228550586: connect: connection refused\""}
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).runUpdate.func1
	/go/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:97
github.com/vmware-tanzu/octant/internal/api.(*job).run.func1
	/go/src/github.com/vmware-tanzu/octant/internal/api/poller.go:111
```

The webapp remains available, but the lefthand menu then disappears:
![Screen Shot 2019-11-16 at 11 44 03 PM](https://user-images.githubusercontent.com/393494/69003645-89b5d580-08cb-11ea-9d6f-205b47863f06.png)

Problem resolved by restarting octant

**Comment by wwitzel3** [comment]
My initial thought for doing something like this is to extend the existing process launcher to have a bit more management to it.

- add fsnotify/fswatch to the plugin folder
- compare the filename that changed to our filename list in our process management
- kill/restart the plugin with a matching filename that has changed

Related reading:
- https://github.com/hashicorp/go-plugin/issues/31
- https://github.com/vmware-tanzu/velero/pull/710
