### ISSUE TITLE
Getting error in generating content: preferred resources: unable to retrieve the complete list of server APIs` 

### ISSUE THREAD

**Issue by mklanjsek** [vmware-tanzu/octant#1790]
After switching to master, I started seeing this error on our development cluster:

```2021-01-04T11:03:26.210-0700`	ERROR	api/content_manager.go:154	generate content	{"client-id": "34d14e10-4eb5-11eb-98b7-f45c89abd6ef", "err": "generate content: preferred resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request", "content-path": "overview/namespace/milan"}
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1
	/Users/milanklanjsek/workspace/octant/internal/api/content_manager.go:154
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
	/Users/milanklanjsek/workspace/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
	/Users/milanklanjsek/workspace/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start
	/Users/milanklanjsek/workspace/octant/internal/api/content_manager.go:128```

Based on brief discussion from todays standup, it might be related to #1721

**Comment by wwitzel3** [comment]
This was re-introduced here: https://github.com/vmware-tanzu/octant/commit/dcb101861ff11cd521317464d29d81ed1b9047eb

**Comment by wwitzel3** [comment]
This error is coming from https://github.com/vmware-tanzu/octant/blob/master/internal/printer/customresourcedefinition.go#L113

We've fixed similar errors in the past by explicitly checking for the metrics failure explicitly, https://github.com/vmware-tanzu/octant/blob/master/internal/queryer/queryer.go#L319

I'm not sure if that is the correct approach we want to also use here, or if there is some better way to more generically solve this problem.
