### ISSUE TITLE
Changing kube context in octant should change kubeconfig file

### ISSUE THREAD

**Issue by mstergianis** [vmware-tanzu/octant#1793]
**Describe the problem/challenge you have**
Octant currently watches the filesystem to monitor for changes to the kubeconfig in order to automatically change contexts when the user modifies their kubeconfig (`~/.kube/config`). However, if you change contexts in the octant UI, it will not propagate this change back to the filesystem.

**Describe the solution you'd like**
When changing contexts in the top bar of octant, a change would be issued to the kubeconfig that octant is using.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): master as of Tue Jan 5 15:58:12 2021
```
Version:  (dev-version)
Git commit:  5a68afb3
Built:  2021-01-06T17:05:48Z
```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7+vmware.1", GitCommit:"7be6fd53a1c9885bf9f470673f1c14280aab6386", GitTreeState:"clean", BuildDate:"2020-02-13T23:24:07Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Linux 5.9.14-arch1-1

**Comment by GuessWhoSamFoo** [comment]
In some cases, this behavior is desirable with interoperability with other tools like kubectl to work across multiple contexts at once.

**Comment by mstergianis** [comment]
Oh okay, no problem. I can close, I was just thinking that if octant was respecting what context you chose on cli, that it was desirable to have it go both ways.

Let me know if I should close

**Comment by GuessWhoSamFoo** [comment]
We should check some of the other tooling in the ecosystem to see if there is an informal standard. I don't have strong opinions on this one - fine with changing this behavior if it solves a specific problem.

**Comment by mstergianis** [comment]
No specific problem

**Comment by wwitzel3** [comment]
The desired behavior is to not change or persist context switches to the filesystem. Eventually we may have some mechanism in Octant that allows for having a different "default" context stored as part of the application settings and configuration, but we don't want to modify the filesystem.
