### ISSUE TITLE
Invert Hierarchy

### ISSUE THREAD

**Issue by ibagha** [vmware-tanzu/octant#1798]
On some views, the hierarchy of objects in inverted, showing bottom-level information at the top and top-level information at the bottom. This can make it more difficult for users to consume, or they will have to rearrange the graph to have the correct top-down view.

Example: Pods, secrets, and service accounts and laid out above deployments
<img width="1555" alt="Screen Shot 2021-01-07 at 12 28 59 PM" src="https://user-images.githubusercontent.com/54036938/104047267-39b46500-5196-11eb-95d8-42edefa1cd11.png">

**Comment by GuessWhoSamFoo** [comment]
Closed via #2343
