### ISSUE TITLE
Representative Page Titles

### ISSUE THREAD

**Issue by govindjeevan** [vmware-tanzu/octant#1838]
**Describe the problem/challenge you have**
Not able to identify browser tabs easily when working with multiple octant tabs open

**Describe the solution you'd like**
Change the page title from generic Octant to the indicate the resource or actual page being displayed in the tab.
eg. Orchestrator-3 | Octant

**Comment by GuessWhoSamFoo** [comment]
Unlikely to be implemented as the electron build will receive full support in the near future. PR's are welcomed
