### ISSUE TITLE
configure the default items per page via preferences

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#1850]
it would be awesome if via preferences (maybe stored in `localStorage`?) we could configure the default items per page thats then inherited by all pages by default. (I guess configuring each page's default item count separately some day could be useful too)

10 items per page is pretty small for lots of views so I'd love to be able to configure once, to show say 20 or 50 and not have to keep doing it each time I move to a page

**Comment by lenriquez** [comment]
@wwitzel3 I can work on this issue as @mklanjsek suggested

**Comment by mklanjsek** [comment]
Done with #2047
