### ISSUE TITLE
Electron contextMenu / system tray

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#1866]
Octant should close itself to the system tray.
The first time you close Octant, prompt the user to minimize to system tray OR exit the application.
Provide a check box to remember this choice.
Expose that choice in preferences so it can be changed later.

Basic context menu:

- Open Octant
- View Logs
- Exit

**Comment by GuessWhoSamFoo** [comment]
@ibagha What else should be in this menu? Do we need more octant status icons dependent on cluster state? What about notifications?
