### ISSUE TITLE
Kubeconfig location on windows

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/octant#1893]
**Describe the problem/challenge you have**
Currently when octant on widows and starting without a kubeconfig, it pops up with the text area to paste a kubeconfig content. this content is then saved in the users AppData\Local\Temp\1 folder as a file named kubeconfig and then a number sequence.
the issue is the location of that file is not trivial for many users and i haven't seen it documented so updating that kubeconfig becomes difficult. also as that kubeconfig is loaded again at every start up of octant it becomes very difficult and problematic for users when they provision a new cluster etc.

**Describe the solution you'd like**
there are a few possible options isee:
1. this is also in my opinion the best option from my side - add a menu option to edit that kubeconfig or paste a new kubeconfig content from a running instance of octant. basically allow a user to request the enter kubeconfig form to pop up on demand.
2. Save the file in a easier to find location C:\Users\<USERNAME>\.octant\kubeconfig maybe?
3. document where the file is saved so at least it would be easier to find.

**Anything else you would like to add:**
This issue seems to be only really relevant for windows however if solution 1 was implemented i could see it being beneficial cross OS.

**Environment:**

- Octant version (use `octant version`): nightly electron build for windows
- Kubernetes version (use `kubectl version`): 1.17-1.20
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10

**Comment by wwitzel3** [comment]
I created a PR which will ensure the temporary file always gets created in an `octant` sub-folder of the temp directory. This is the same location as the logs that get generated. This will make it a bit easier to find the file. This is just a short-term solution for 0.17.

We will look to make a proper kubeconfig management experience in a later release.
