### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by nicoclau** [vmware-tanzu/octant#1901]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Some links are broken

![image](https://user-images.githubusercontent.com/16133485/106300022-39b7fa00-6256-11eb-89f7-023caa988dda.png)

when we click on pods, the link is wrong.

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Octant Release Information

- Octant version (use `octant version`): Version:  0.16.3 Git commit:  656c7404e529262861eacb13e88d33dccd6035bf Built:  2020-12-09T23:59:19Z
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- OS windows 10

**Comment by mklanjsek** [comment]
@nicoclau thanks for reporting - the issue with links on windows will be included in 0.17, you can use nightly builds in the mean time.
