### ISSUE TITLE
Use electron-store for preferences and consolidate storage.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#1923]
#1906 introduces electron-store.
#1538 adds preference UI.
#941 introduced server side preference `Frontend Proxy URL`
#1885 uses a `state.json` file to store the last known x,y,w,h for the application window.

Let's consolidate these storage locations. I think storing everything using `electron-store` makes a lot of sense here.

I think due to some points raised in #1538 this work should happen before we release 0.17.

cc: @GuessWhoSamFoo @mklanjsek

**Comment by mklanjsek** [comment]
I agree that `electron-store` is a way to go.  It stores data as JSON, supports migrations and can be accessed from both main and renderer process.  At this point we have enough usage scenarios listed above to test it against so it's a good time to consolidate persistence.

**Comment by mklanjsek** [comment]
Also relevant for issues like #1850 which also brings to the table how will preferences be exposed to plugin users

**Comment by mklanjsek** [comment]
The only remaining issue here is preference for `Frontend Proxy URL`, everything else is covered in #1957
