### ISSUE TITLE
octant.dev Documentation links are confusing.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#1924]
When visiting https://octant.dev the links for the documentation from the Header and Footer link to the same `/docs` page.

![image](https://user-images.githubusercontent.com/27317/106489291-9c8dd900-6482-11eb-9652-6ece00c752c8.png)

On that page, the Documentation footer looks like it should link out to our Getting Started content, but it just links back to `/docs`.

We should consider redoing that page and the footer to be more clear.
Our docs now live at https://reference.octant.dev

cc: @ibagha

**Comment by ftovaro** [comment]
Hey, I'm gonna be working on this issue.

Two things:

1. I'm gonna be working on fixing the link
2. The issue also says something about a redesign, we still not have any of that, so, I'm gonna to talk with Isha if she has any ideas, if not, we can separate the PRs of redesign and the link's issue.

🚀
