### ISSUE TITLE
octant capitalization on Mac 

### ISSUE THREAD

**Issue by mklanjsek** [vmware-tanzu/octant#1945]
For some reason Octant is capitalized with small `o` in main window caption bar on Mac, see screenshot:
![Screen Shot 2021-02-03 at 11 24 00 AM](https://user-images.githubusercontent.com/34245594/106792138-03da9300-6613-11eb-9f94-597354477d25.png)

Although some apps like zoom do that as well, I think we should probably fix that.

**Comment by GuessWhoSamFoo** [comment]
See if setting a title directly helps: https://www.electronjs.org/docs/api/tray#traysettitletitle-options-macos

**Comment by lenriquez** [comment]
I think this is already solved on https://github.com/vmware-tanzu/octant/commit/c9738199daa38d0d4e7277b6b689f54e957549ea
