### ISSUE TITLE
Cursor should not always be pointer when modal is open

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#1952]
Seems to be affecting electron only, and not the preferences modal

**Comment by xtreme-vikram-yadav** [comment]
picking it up.

**Comment by xtreme-vikram-yadav** [comment]
Picking it up.

**Comment by xtreme-vikram-yadav** [comment]
This issue is fixed by https://github.com/vmware-tanzu/octant/pull/2328.
