### ISSUE TITLE
Make Mac menu item useful, or remove it

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/octant#2012]
**Describe the problem/challenge you have**

The Octant electron app is adding a menu bar item. These icons are typically used for quick access to common functions while in any other application and quick status (volume, wifi signal strength, time, etc).

The current icon provides no status and the menu provides no meaningful actions.

<img width="119" alt="Screen Shot 2021-02-16 at 8 03 21 PM" src="https://user-images.githubusercontent.com/302992/108141990-e1288f80-7092-11eb-9bcd-9d4bf49c4930.png">

**Describe the solution you'd like**

Minimally, remove **all** color to match the silhouette style of other icons.

Better is to make the menu useful, or remove it. The current menu options are more appropriate on the Dock icon.

**Environment:**

- Octant version (use `octant version`): 0.17.0
- Kubernetes version (use `kubectl version`): n/a
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 11.2.1

**Comment by wwitzel3** [comment]
Agreed, we have some plans for 0.18 to make this actually have some status of the current cluster/namespace. We'll use this issue to track that.

**Comment by xtreme-vikram-yadav** [comment]
Hey @wwitzel3, can you confirm what status(es) from a cluster should be shown in the menu?

**Comment by GuessWhoSamFoo** [comment]
There isn't a definitive answer for this. Maybe the tray icon can have colors as a status indicator is any object status items are in warning/error state. Or perhaps a list of context names to quickly pull down from?

**Comment by scothis** [comment]
> Maybe the tray icon can have colors as a status indicator

For mac OS the icon should not have color, unless something is very wrong. The only color on the built-in menu items is when the battery is about to die, otherwise they are all silhouettes.

**Comment by xtreme-vikram-yadav** [comment]
Keeping the icon in greyscale sounds good. Taking a hint from docker desktop, we can consolidate the two ideas and show the status indicator and context/namespace switcher as a menu item.
![Screen Shot 2021-04-22 at 12 23 15 PM](https://user-images.githubusercontent.com/5066253/115751741-7849e600-a367-11eb-8df4-23e3b6b0bb9e.png)

**Comment by xtreme-vikram-yadav** [comment]
Keeping the icon in greyscale sounds good. Taking a hint from docker desktop, we can consolidate the two ideas and show the status indicator and context/namespace switcher as a menu item.
![Screen Shot 2021-04-22 at 12 43 42 PM](https://user-images.githubusercontent.com/5066253/115752753-69176800-a368-11eb-8420-c78ea1611870.png)

**Comment by xtreme-vikram-yadav** [comment]
picking it up.

**Comment by GuessWhoSamFoo** [comment]
Let's start by duplicating some of the current menu items under the helper menu on the top right. Eventually when we move away from a binary, we can remove the duplicate menu items from front end once we fully move to electron.

For this issue, add:
 - Open an issue button
 - Contexts (which could duplicate the kubectl method rather than changing contexts in memory)
 - Possibly a `Restart` (for use cases with installing go plugins)
