### ISSUE TITLE
octant.dev site moving to Hugo

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#2014]
@jonasrosland reached out and let me know there was a new site template and that the site was moving to Hugo. I wanted to create an issue to track any work related to getting that update in place.

When I spoke to Jonas I expressed my concerns that I have around or current site, how we mix user documentation, with plugin author documentation, with contributor documentation and I would like to re-organize all of that eventually.

**Comment by GuessWhoSamFoo** [comment]
I've done some work on this about a year ago: https://github.com/GuessWhoSamFoo/octant-website

Things that were to-do on this branch:
 - Continue removing templating duplication where possible
 - Shortcodes for notes, warnings
 - Remove jquery library
 - Bug where a related blog post can be itself

**Comment by GuessWhoSamFoo** [comment]
Closing as no longer valid
