### ISSUE TITLE
Add row detail from Clarity

### ISSUE THREAD

**Issue by piachakra** [vmware-tanzu/octant#2019]
As a plugin author,
Given that I create a table
I would like to let the user expand and collapse each row
So that they can see row details

![Screen Shot 2021-02-17 at 2 22 04 PM](https://user-images.githubusercontent.com/48967925/109195584-8e646d00-774f-11eb-8830-d00c82570641.png)

**Comment by wwitzel3** [comment]
This is adding the ability to expand a row to show detail, Clarity supports this, we'll want to add it to our component API and template.

https://clarity.design/angular-components/datagrid/#expandable-rows

**Comment by wwitzel3** [comment]
Hey @GuessWhoSamFoo  would we be able to include the detail pane as part of this change too? Or do you think those things are too different and requires a separate PR?

**Comment by wwitzel3** [comment]
https://clarity.design/angular-components/datagrid/#detail-pane

**Comment by GuessWhoSamFoo** [comment]
I will add it.

**Comment by GuessWhoSamFoo** [comment]
Update: there are issues with the detail pane. Either the pane does not expand from the toggle or it is stuck without displaying any content. Not sure if it is an upstream or user error, but it will be skipped as not technically part of the design spec.
