### ISSUE TITLE
Horizontal stacking of fields

### ISSUE THREAD

**Issue by piachakra** [vmware-tanzu/octant#2020]
As a plugin author
Given that I am creating a table of input fields
I would like to be able to stack them horizontally
So that I have more visual options to provide the user

Currently input fields are stacked vertically

<img width="460" alt="Screen Shot 2021-02-24 at 12 18 58 PM" src="https://user-images.githubusercontent.com/48967925/109195421-56f5c080-774f-11eb-82d5-cbf9d90a80b8.png">

**Comment by GuessWhoSamFoo** [comment]
More specifically, we are looking to use [vertical inline](https://clarity.design/core-components/form/#vertical-vertical-inline) of the core form component so part of this PR will need to migrate off the angular component.
