### ISSUE TITLE
Allow the dashboard to be embedded in another program

### ISSUE THREAD

**Issue by ledor473** [vmware-tanzu/octant#204]
I started to check if it was possible to embed Octant inside another Go application but right now a large portion of the code sits inside the `internal/` folder which prevents it do be imported.

The goal would be to automatically start/stop Octant when starting something else. It would allow things like an embedded Octant inside a Grafana plugin for instance.

I think moving `internal/dash` to `pkg/dash` would be enough by looking at this: https://github.com/vmware/octant/blob/d52b4b0286f865a3d2ad7d3ffb8d6e8bc1eb48ea/internal/commands/dash.go#L68-L92

Would you be open to that change? I'm happy to drive that change and the testing related to it 🙂

**Comment by bryanl** [comment]
While we determine what API stability looks like, we most likely won’t be moving anything else out of internal. What kind of app are you trying to embed it in?

**Comment by ledor473** [comment]
I'm thinking of an application very similar to the `kubectl wrapper` presented in [Airbnb keynote during KubeCon 18](https://kccna18.sched.com/event/GsxY/keynote-developing-kubernetes-services-at-airbnb-scale-melanie-cebula-software-engineer-airbnb). It reduces the amount of typing needed to do common tasks, from `kubectl apply` to `helm upgrade`.
I feel that Octant would be a good candidate to bundle as well since it's built to use the user's credentials and run locally.

Considering it's in Go as well, I'd rather import it than making it an external dependency that needs to be installed in the `PATH` and having to start the binary directly.

I can totally see why the API stability is a concern, but the instability is something one should expect from any project that follows [SemVer and is pre-1.x](https://semver.org/spec/v2.0.0.html#spec-item-4).
Various projects (including [early Kubernetes](https://github.com/kubernetes/kubernetes/blob/7e0798989746c2f5f0dafa1bd09739a4983ddbfe/docs/api.md#api-changes)) include a warning in the documentation to make it clear that breaking change should be expected.
