### ISSUE TITLE
Plugins can enrich calls to custom object stores with arbitrary metadata

### ISSUE THREAD

**Issue by jamieklassen** [vmware-tanzu/octant#2042]
(co-written with @chinigo)

**Describe the problem/challenge you have**
We're developing a custom `store.Store` implementation that retrieves Kubernetes API data through an authenticated proxy. The results of these API calls may vary based on the authenticated user making the query.  The auth flow is handled in the web browser and tokens are short-lived, so the frontend needs some way to propagate its credentials back to the store.

**Describe the solution you'd like**
First, we'll call out the fact that our use case involves a plugin which makes use of the Javascript runtime, but will mention Go/GRPC plugins later.
​
[`octant.DashboardClient`](https://github.com/vmware-tanzu/plugin-library-for-octant/blob/7b9e6ad4dc1cd303d92ed3e0a906a7cbfc058f8a/plugin/octant.d.ts#L109-L158) could be modified such that each method has an extra metadata parameter, e.g.
​
```typescript
export interface DashboardClient {
  List(key: Key, metadata?: {[key: string]: string}) : any[];
  // ... other methods would add a similar optional metadata parameter
}
```
​
Then we could create a plugin that registers [a custom action](https://github.com/vmware-tanzu/octant/blob/v0.17.0/pkg/action/doc.go#L13) to keep track of the state of the client's authentication, and passes that data to its `dashboardClient` using the new optional metadata parameter:
​
```typescript
export default class TokenHandlingPlugin implements octant.Plugin {
  dashboardClient: octant.DashboardClient;
  httpClient: octant.HTTPClient;
  // ... plugin boilerplate ...
​
  tokens : {[clientID: string]: string};
​
  capabilities = {
    actionNames: ["action.mycompany.org/setAuthToken"],
  };
​
  actionHandler(request: octant.ActionRequest): octant.ActionResponse | void {
    if (request.actionName === "action.mycompany.org/setAuthToken") {
      this.tokens[request.clientID] = request.payload.token;
      return;
    }
    return;
  }
​
  contentHandler(request: octant.ContentRequest): octant.ContentResponse {
    let metadata = {};
    metadata["auth_token"] = this.tokens[request.clientID];
    let pods = this.dashboardClient.List(
      {apiVersion: 'v1', kind: 'Pod'},
      metadata // <----------------------------------------- NEW PARAMETER
    );
    return {content: {viewComponents: [], title: []}};
  }
}
```
​
Then the [corresponding function in the javascript plugin runtime](https://github.com/vmware-tanzu/octant/blob/fcd6330a1af86a0be57ed05e70c3104403192dc8/pkg/plugin/javascript/dashboard_list.go#L38-L67) could be modified to inject these values into the `context.Context` that gets passed to its associated `store.Store`, something like:
​
```go
func (d *DashboardList) Call(ctx context.Context, vm *goja.Runtime) func(c goja.FunctionCall) goja.Value {
	return func(c goja.FunctionCall) goja.Value {
		md := map[string]interface{}{}
		mdObj := c.Argument(1).ToObject(vm)
		_ = vm.ExportTo(mdObj, &md)
		for key, val := range md {
			ctx = context.WithValue(ctx, key, val)
		}
		// ... followed by the usual implementation
	}
}
```
​
Finally, our custom `store.Store` implementation could read the auth token from the context passed to its `List` method with `ctx.Val("auth_token")` and use it to authenticate with the aforementioned proxy.
​
In the case of GRPC plugins, a slightly different implementation would be required, where perhaps consumers of [`pkg/plugin/api.Client`](https://github.com/vmware-tanzu/octant/blob/master/pkg/plugin/api/client.go#L87-L107) could expect metadata values placed in the `context.Context` parameter to be serialized by the client, perhaps as GRPC headers, on the RPC backing each method. Then the [server's implementation](https://github.com/vmware-tanzu/octant/blob/fcd6330a1af86a0be57ed05e70c3104403192dc8/pkg/plugin/api/server.go#L87-L92) of those RPCs would be responsible for deserializing the metadata values and packing them into the `context.Context` passed to the associated `store.Store` in a similar manner to that described for the javascript runtime above.

**Anything else you would like to add:**

Our use case is for authentication, but we can imagine other scenarios where it would be useful for a plugin to coordinate with a custom object store:
- Transport-layer concerns like correlation IDs, proxy configuration, or cache busting.
- As per discussion @wwitzel3, you could imagine an object store backed by a database, where the frontend client would need to manage cursor position in a result set.

**Environment:**

- Octant version (use `octant version`): 0.17.0
- Kubernetes version (use `kubectl version`): N/A
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): a [`golang`](https://hub.docker.com/_/golang) (i.e. Debian buster)-based container running on kubernetes. AWS is providing the infrastructure, but I'm unsure of whether it's an EKS cluster or maybe [Tanzu Kubernetes Grid](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.0/vmware-tanzu-kubernetes-grid-10/GUID-install-tkg-aws.html).

**Comment by wwitzel3** [comment]
@xtreme-vikram-yadav can you take a look at this after your current set of issues.

**Comment by xtreme-vikram-yadav** [comment]
picking it up.

**Comment by xtreme-vikram-yadav** [comment]
Since grpc sets other headers for its use, it will be useful to use namespaced keys(perhaps with a prefix such as 
X-OCTANT-{keyName}) which will make the extraction easier on the grpc server side.
