### ISSUE TITLE
Unable to see all tags for a k8s object

### ISSUE THREAD

**Issue by tibin-mfl** [vmware-tanzu/octant#2044]
**Issue**
When a component/object has more tags cannot see all the tags, only 7 - 8 logs are visible on window.

https://user-images.githubusercontent.com/51317257/108492309-01429380-72cb-11eb-9fce-fb89dea87ff8.mov

**Solution Required*
Add a vertical scrolling option so that tags above that window is visible

**Environment:**

- Octant version: 0.16.3
- Kubernetes version: 1.17.
- OS: Ubuntu 18.04

**Comment by GuessWhoSamFoo** [comment]
This isn't really a vertical scrolling problem. The top of the tooltip is hidden by the datagrid because it doesn't have intelligent popovers implemented. See https://github.com/vmware/clarity/issues/1757

**Comment by lenriquez** [comment]
@GuessWhoSamFoo actually, the solution is on this link https://github.com/vmware/clarity/issues/4891 (found on vmware/clarity#1757). Removing `position: relative`  looks like solve the problem
