### ISSUE TITLE
No option to choose the interpreter on the terminal

### ISSUE THREAD

**Issue by csib** [vmware-tanzu/octant#2164]
**Describe the problem/challenge you have**
Can't change the terminal interpreter for a POD (SH/BASH). 
![image](https://user-images.githubusercontent.com/24816101/111294149-4fd51a80-864a-11eb-8004-698579d22801.png)

**Describe the solution you'd like**
Dynamically set SH/BASH which works on a pod.

**Environment:**

- Octant version (use `octant version`): 0.17.0 -  (dev-version) Built: 2021-02-11T23:48:58Z 
- Kubernetes version (use `kubectl version`):
- OS: Windows 10

**Comment by xtreme-vikram-yadav** [comment]
picking this up.

**Comment by lloydchang** [comment]
To Whom It May Concern:

Consider upgrading to Octant [v0.19.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.19.0) if you're using Octant [v0.17.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.17.0) and [v0.18.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.18.0).

**Why:** Feature [Change default shell to bash #1533](https://github.com/vmware-tanzu/octant/issues/1533)'s initial implementation, [Add support for windows shells and bash #1749](https://github.com/vmware-tanzu/octant/pull/1749) released in [v0.17.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.17.0) and [v0.18.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.18.0), has a bug of:
```
OCI runtime exec failed: ...
(process exited)
```
with operating systems without `bash`, e.g. Alpine Linux with `sh` only.

A bug fix [increase timeout for remote cmd stream setup #2258](https://github.com/vmware-tanzu/octant/pull/2258) released in [v0.19.0](https://github.com/vmware-tanzu/octant/releases/tag/v0.19.0), fixed a similar bug [No option to choose the interpreter on the terminal #2164](https://github.com/vmware-tanzu/octant/issues/2164).

After the bug fix, operating systems without `bash`, such as Alpine Linux, can start `sh` successfully

Thank you.
