### ISSUE TITLE
Configurable form field width in stepper

### ISSUE THREAD

**Issue by tomkennedy513** [vmware-tanzu/octant#2178]
**Describe the problem/challenge you have**
I am trying to create a stepper and the form fields inside that stepper are too narrow. I cannot see the entire placeholder value (which I am using as a description basically)

**Describe the solution you'd like**
I would like to be able to configure the width of the form field in relation tot he stepper width

**Anything else you would like to add:**

**Environment:**

- Octant version (use `octant version`): 0.17.0
- Kubernetes version (use `kubectl version`): server = v1.18.12-gke.1210 client= v1.20.4-dirty 
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): mac os 11.2.3

**Comment by wwitzel3** [comment]
related #2223

**Comment by GuessWhoSamFoo** [comment]
Closed via #2376
