### ISSUE TITLE
Buttons should be able to link

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#2183]
**Describe the problem/challenge you have**
Currently buttons are only used to perform actions.

**Describe the solution you'd like**
Ability to create a button which is really a `Link` component in disguise. Alternatively, redirecting to a certain path based on an action seems like a common use case.

**Comment by wwitzel3** [comment]
Ideally, we would have the `LinkComponent` be able to have a `component` field and that component would be wrapped in an anchor tag.

**Comment by ftovaro** [comment]
Hey guys, I'm gonna be working on this issue
