### ISSUE TITLE
Allow styling configuration for buttons 

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#2184]
**Describe the problem/challenge you have**
Buttons in Octant are currently styled based on CSS rules from the frontend.

**Describe the solution you'd like**
For a given button, add the ability to:

- choose between solid, outlined, flat (no outline) styles
- disable a button
- create a [block button](https://clarity.design/angular-components/button/#block)
- show a button as loading
- allow setting colors to red, green, blue (error, success, info)

**Comment by ftovaro** [comment]
Since @GuessWhoSamFoo did a big progress of this issue on this PR #2208 , I can take it from there and finish it
