### ISSUE TITLE
npm run electron:build fails

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#2211]
After merging in the latest changes for the Resource Viewer, running `npm run electron:build` fails because it directly calls `ng build` and does not run the `pre-install` and `post-install` steps that happen when running `npm install`.

Running `go run build.go web-build` also fails for this same reason.

A quick fix is to ensure `npm install` is run before the main `build` command is run, but also, I would like us to audit our usage of build.go and our pipeline to make sure we aren't duplicating efforts and preferring and using `build.go` when we can.

**Comment by wwitzel3** [comment]
We want to do an audit of what we run in our pipeline checks vs. what we do for local development.
We want to remove duplication of commands and clean up any processes that might be left over from our old build pipeline.
We want to ensure that we add tests to our pipeline for our build.go script so that future changes do not prevent it from breaking

**Comment by xtreme-vikram-yadav** [comment]
picking this up.
