### ISSUE TITLE
Create FormComponent

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#2223]
Create a formal `FormComponent` to represent forms in Octant.

Investigate how to handle the forms we currently display in Octant in the Stepper, Modal, and Card editable views.
Also consider how we might address the request in #2020 for allowing grid layout / vertical stacking.

Vertical stacking is part of clarity.
Grid layout is normally a manual / per-application decision, but if we can support it nicely, that seems like a good thing to do.

Related: #2020 #1504

**Comment by GuessWhoSamFoo** [comment]
Closed via #2376
