### ISSUE TITLE
Feature to see previous logs for crashed pods

### ISSUE THREAD

**Issue by ld-singh** [vmware-tanzu/octant#223]
It would be super helpful if we can see previous logs for pods in case they crash and restarts and will help in debugging a lot. It can be done with kubectl with --previous option

**Comment by bryanl** [comment]
Octant will gain support to see pods that have been terminated. This will allow you to see previous logs.

**Comment by wwitzel3** [comment]
You can now do this, added when we added support for seeing terminated pods in #274
