### ISSUE TITLE
Expandable row feature

### ISSUE THREAD

**Issue by sbanoth-vmw** [vmware-tanzu/octant#2242]
**Describe the problem/challenge you have**
We are trying to expandable feature of row, which was added recently(0.18). Problem with this feature is, component is added to first column only. When we click on expandable button, row(s) should be added below the original row. There could be multiple rows for display.

**Describe the solution you'd like**
We are trying to expandable feature of row, which was added recently(0.18). Problem with this feature is, component is added to first column only. When we click on expandable button, multiple row should be added below the original row.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by wwitzel3** [comment]
@GuessWhoSamFoo this was the issue I mentioned in standup.

**Comment by lenriquez** [comment]
I am working on this
