### ISSUE TITLE
Calls to object store do not succeed in first attempt

### ISSUE THREAD

**Issue by xtreme-vikram-yadav** [vmware-tanzu/octant#2256]
**What steps did you take and what happened:**
While calling object store methods via Dashboard interface in a plugin, calls to K8s fail in the first attempt but succeed on the subsequent call.

Code to reproduct and inspect this issue is available here: https://github.com/xtreme-vikram-yadav/octant/commit/483683669ac643dfd25695a3d34a794a0bf5c451

Example call to create a namespace from the plugin:
```
request.DashboardClient.Create(request.Context(), &unstructured.Unstructured{
	Object: map[string]interface{}{
		"apiVersion": "v1",
		"kind":       "Namespace",
		"metadata": map[string]interface{}{
			"name":      "foo",
			"namespace": "",
		},
	},
})
```

Results:
1st attempt: 
```
GVR:  /, Resource=  
(The above GRV is missing the resource name)
Error: the server could not find the requested resource
```

2nd attempt:
```
GVR: /v1, Resource=namespaces
Error: <nil>
```
---

Example call to get a Pod:
```
request.DashboardClient.Get(request.Context(), store.Key{
	APIVersion: "v1",
	Kind:       "Pod",
	Name:       "nginx-deployment-66b6c48dd5-2x5th",
	Namespace:  "default",
})
```
Results:
1st attempt: 
`Error: "nginx-deployment-66b6c48dd5-2x5th" not found`

2nd attempt:
`Error: "nginx-deployment-66b6c48dd5-2x5th" not found`

3rd attempt:
`Error: <nil>`

**What did you expect to happen:** Calls to object store should return results successfully the first time.

**Anything else you would like to add:**
May be it is an issue with the cluster itself and not octant but might be worth investigating.

**Environment:**

- Octant version (use `octant version`): https://github.com/vmware-tanzu/octant/commit/9b658f64342cb6cb8388f689dc61a39cb79de4e5
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): `macOS 10.14.6`

**Comment by wwitzel3** [comment]
This would be expected behavior while waiting for the cache to sync. We intentionally did this.
