### ISSUE TITLE
Problem with usage --namespace-list flag

### ISSUE THREAD

**Issue by aleksandrgudo** [vmware-tanzu/octant#2259]
When I try to use this option by adding several such namespaces "--namespace-list pf-personal-finance,pf-personal-lifestyle,pf-investment", I see only one of them in the octant interface, the first one
Using command like this: octant --kubeconfig /home/aleksandr/kubeconf_test --namespace-list pf-personal-finance,pf-personal-lifestyle,pf-investment
In the drop-down list of namespaces I see only default and pf-personal-finance
I use  restricted clusters

![Screenshot_20210403_025509](https://user-images.githubusercontent.com/81835872/113462129-1b25d900-9428-11eb-8fcc-ce8bfa14696d.png)

**Environment:**

- **Octant version**:
Version:  0.17.0
Git commit:  7fded9570239df80f75fa6cf9f4a6ec17945a7e3
Built:  2021-02-12T00:45:19Z
- **Kubernetes version**:
- Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- **OS**:
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04

- **Web browser**: Firefox 85

**Comment by wwitzel3** [comment]
Using restricted RBAC with only access to certain namespaces without the ability to list them can reproduce this bug.
