### ISSUE TITLE
Add standard alerts component

### ISSUE THREAD

**Issue by pivotal-mikegresham** [vmware-tanzu/octant#2303]
**Describe the problem/challenge you have**
We would like to present various types of in-context alerts to the user.

**Describe the solution you'd like**
Implement clarity's standard alerts. Standard alerts are for use in the context of an application either in the content area itself or within components (as opposed to app level alerts that show up at the very top of the screen)

Alerts consist of 1) a color & icon to indicate the type of alert, message text, a call to action button, and an X button to dismiss the alert

**Anything else you would like to add:**
Clarity docs: https://clarity.design/core-components/alert/#standard-alerts-2

**Comment by wwitzel3** [comment]
Extending the alert component to support standard alerts.
https://github.com/vmware-tanzu/octant/blob/577caf3704b91977ff0270d797d2860cedd24c4d/pkg/view/component/alert.go

Currently all alerts are app level alerts that get sent over the websocket and rendered at the top of Octant. We should allow the creation and usage of standard alerts as components within Octant itself.

**Comment by xtreme-vikram-yadav** [comment]
picking it up.

**Comment by xtreme-vikram-yadav** [comment]
Seems like we already have alerts(https://github.com/vmware-tanzu/octant/blob/master/pkg/view/component/alert.go) which can be rendered inside summary components. 
We can update the alerts to behave more like current clarity alerts (by adding a close button), but there is already a construct to allow for contextual alerts. An example can be seen when we delete a pod (https://github.com/vmware-tanzu/octant/blob/d91a8d32031e67b280deade7b762bc99a334f2a9/internal/printer/pod.go#L155):
![Screen Shot 2021-04-20 at 5 05 19 PM](https://user-images.githubusercontent.com/5066253/115464233-c7263d00-a1fa-11eb-95dd-32292376e3e5.png).
