### ISSUE TITLE
Add horizontal tabs clarity component

### ISSUE THREAD

**Issue by pivotal-mikegresham** [vmware-tanzu/octant#2304]
**Describe the problem/challenge you have**
We want to present horizontal tabs to the user. Worth noting that the specific implementation we have in mind involves putting the tabs inside of an accordion component

**Describe the solution you'd like**
Implement horizontal tabs from the clarity tabs component. 

**Anything else you would like to add:**
Clarity Docs: https://clarity.design/angular-components/tab/#horizontal

**Comment by wwitzel3** [comment]
Note for folks looking to take this issue:

Octant doesn't have a formal TabComponent at the moment. This could be the issue that we use to track adding a `TabComponent` that is intended for use by plugin authors.

Some things to consider with this are that we currently have a two different ways to add tabs now, one is implicitly by adding content to the content response and the other is explicitly through the tab handler.

We don't want to confuse those with this Tab component which would be for adding arbitrary tab views to the content itself. One of the biggest issues with adding a tab component would be the nested active tab tracking when using a tab component inside an already tabbed view.

**Comment by ftovaro** [comment]
I'm going to be working on this one
