### ISSUE TITLE
Extend IconComponent to support Tooltip

### ISSUE THREAD

**Issue by pivotal-mikegresham** [vmware-tanzu/octant#2307]
**Describe the problem/challenge you have**
Teams want to be able to use tooltips to help onboard and inform users about taxonomy and topology

**Describe the solution you'd like**
Implement the tooltips component from clarity

**Anything else you would like to add:**
Clarity docs: https://clarity.design/angular-components/tooltip/#tooltip-right

**Comment by wwitzel3** [comment]
Implementing this would involve extending the existing IconComponent. We'll want to support Size and Placement configuration options.
