### ISSUE TITLE
Approver Request

### ISSUE THREAD

**Issue by lenriquez** [vmware-tanzu/octant#2308]
### GitHub Username
@lenriquez 

### Requirements
- [X] I have read the [contributor guide](https://github.com/vmware-tanzu/octant/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Kubernetes Slack workspace](slack.k8s.io) and the [#octant channel](https://kubernetes.slack.com/archives/CM37M9FCG)
- [X] I am actively contributing to Octant 
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @wwitzel3 
- @mklanjsek
- @GuessWhoSamFoo 

### List of contributions to the Octant project
-  PRs reviewed / authored 
https://github.com/vmware-tanzu/octant/pull/2281, https://github.com/vmware-tanzu/octant/pull/2254, https://github.com/vmware-tanzu/octant/pull/2221, https://github.com/vmware-tanzu/octant/pull/2186, https://github.com/vmware-tanzu/octant/pull/2166, https://github.com/vmware-tanzu/octant/pull/2067, https://github.com/vmware-tanzu/octant/pull/2046
- Issues responded to
https://github.com/vmware-tanzu/octant/issues/2170, https://github.com/vmware-tanzu/octant/issues/1944, https://github.com/vmware-tanzu/octant/pull/2047, https://github.com/vmware-tanzu/octant/issues/1945

**Comment by wwitzel3** [comment]
Please edit `e.g. (at)example_user` to be your actual github username `@lenriquez`
