### ISSUE TITLE
Ablity to run in virtual machine

### ISSUE THREAD

**Issue by isdzulqor** [vmware-tanzu/octant#232]
Dear Octant Team, 

Thanks for Octant! I recently attempted to install octant on my virtual machine which has no GUI. And I got this error 
```
2019-08-29T12:53:34.227Z	WARN	dash/dash.go:336	unable to open browser: exec: "xdg-open": executable file not found in $PATH
github.com/vmware/octant/internal/dash.(*dash).Run
	/go/src/github.com/vmware/octant/internal/dash/dash.go:336
github.com/vmware/octant/internal/dash.Run.func1
	/go/src/github.com/vmware/octant/internal/dash/dash.go:186
```
I hope octant is able to start on VM, not limited in GUI based 
Thanks,

**Comment by GuessWhoSamFoo** [comment]
Setting `OCTANT_DISABLE_OPEN_BROWSER` to a non-empty value when running octant should resolve this.

XR #174

**Comment by isdzulqor** [comment]
Thanks for your answer. I already tried it. It threw no error. But it didn't expose the port

**Comment by GuessWhoSamFoo** [comment]
Octant runs on `localhost:7777` by default and does not expose any ports. Can you share what you're trying to accomplish?

**Comment by wwitzel3** [comment]
See #450 about the direction of Octant as an application.
