### ISSUE TITLE
Can't get editor component to show value

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/octant#2354]
**What steps did you take and what happened:**

I can't seem to get the editor component to render the text value

```
editor := component.NewEditor(component.TitleFromString("Edit Yaml"), "foobar", false)
```

Renders:

<img width="912" alt="Screen Shot 2021-04-21 at 2 45 52 PM" src="https://user-images.githubusercontent.com/7309317/115605400-76711b80-a2b0-11eb-9f9c-cbc268fb7081.png">

**Anything else you would like to add:**

I've tried a few configurations for the editor component.

**Environment:**

- Octant version (use `octant version`): 0.19.0 binary, 0.19.0 imported
- Kubernetes version (use `kubectl version`): 1.17
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): mac 10.14

**Comment by GuessWhoSamFoo** [comment]
There's a CSS bug where the editor doors not show height if it is in a flexlayout section which may be relevant here

**Comment by tylerphelan** [comment]
> There's a CSS bug where the editor does not show height if it is in a flexlayout section which may be relevant here

fwiw I tried the editor in a button's modal with no flexbox and it rendered the same way
