### ISSUE TITLE
Approver Request

### ISSUE THREAD

**Issue by xtreme-vikram-yadav** [vmware-tanzu/octant#2355]
### Requirements
- [x] I have read the [contributor guide](https://github.com/vmware-tanzu/octant/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Kubernetes Slack workspace](slack.k8s.io) and the [#octant channel](https://kubernetes.slack.com/archives/CM37M9FCG)
- [x] I am actively contributing to Octant 
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @wwitzel3 
- @GuessWhoSamFoo 

### List of contributions to the Octant project
- PRs reviewed / authored: #2045  #2099 #2140 #2244 #2257 #2258 #2275 #2325 #2165 #2222 #
- Issues responded to: #1513 #1750 #1952 #2063 #2211 #2303 #2305 #2042 #1721

**Comment by GuessWhoSamFoo** [comment]
/approve

Way overdue!

**Comment by wwitzel3** [comment]
/approve

🎉
