### ISSUE TITLE
Auto Generate Breadcrumbs

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#2472]
- Allow breadcrumbs to be generated based on the path a user has taken through the application
- Allow the number of breadcrumbs to be auto-generated to be configurable.
- Add breadcrumb metadata for when auto generating breadcrumbs e.g: title, since it maybe different from the display title
- Add a service that holds the stack of visits as a user navigates the application

I don't think we can mix and match. I think if auto generate the breadcrumbs, then we turn off the statically rendered breadcrumbs.

**Comment by mklanjsek** [comment]
I think we should use back/forward buttons in electron header for that. That is a place to navigate the history, while breadcrumbs are used to navigate the hierarchy.  Even browser back/forth buttons would accomplish that if we are setting the meaningful page titles.

**Comment by wwitzel3** [comment]
The scenario:
click Deployment, Pod, Plugin-Link .. now I want to go back to the Deployment ..

 so I'm back button until I get there OR the plugin has to hard code the breadcrumbs. I think both of these fail to be really useful and we need a scenario where the breadcrumbs are a reflection of the history so I can easily jump back N pages

**Comment by mklanjsek** [comment]
Long press on back would open the list of visited pages and get you there quickly.

Again, it's important not to mix history and hierarchy, for effective navigation we need both.

**Comment by wwitzel3** [comment]
I think that would be an acceptable outcome as well .. some intuitive way to quickly move around the history.

**Comment by nwpappas** [comment]
I'll add a little UX insight into the options, if this is still being investigated.

Breadcrumbs should represent site hierarchy, not navigational history. A good review of best practices can be found here: https://www.nngroup.com/articles/breadcrumbs/. Among the other points is:

> 2. Breadcrumbs should display the current location in the site’s hierarchical structure, not the session history.
> 
> Breadcrumbs are not intended to show the history of pages traversed during a session on the site (a la a browser’s native Back button); they are intended to show the hierarchical structure of the site. We’ve noted this for many years, but it still bears repeating; attempting to show a list of the pages a user has accessed, in order, will quickly become long and confusing, with a lot of repetition, and won’t provide any benefit for users who arrive on a deep page directly from an external link, which is one of the key uses of breadcrumbs.

Not mentioned in the above article; accessibility is also a primary function of breadcrumbs. Users with low/no vision benefit from the readout of a breadcrumb, to understand where they are, and its navigational function in a much deeper way.

**Comment by xtreme-vikram-yadav** [comment]
@nwpappas This issue has evolved into adding a history of visits to the UI. The breadcrumbs which currently exist in the UI capture the hierarchy in the app. Although, adding accessibility would be a nice addition to breadcrumbs. Are there any general guidelines  for the order in which the breadcrumbs with dropdowns would read out?
![dropdown-breadcrumbs](https://user-images.githubusercontent.com/5066253/123468051-40595c00-d5bf-11eb-8cbe-76f6c9d956ea.png)
