### ISSUE TITLE
Unable to view cluster resources

### ISSUE THREAD

**Issue by jpreese** [vmware-tanzu/octant#2526]
**What steps did you take and what happened:**
Using a Kubernetes context as a user who only has access to a single namespace. Some cluster-wide permissions are enabled, such as listing CRDs.

**What did you expect to happen:**
To be able to view the resources within that namespace

**Anything else you would like to add:**

Have tried both the `--disable-cluster-overview` and `--namespace` flags
Have verified I have `list` permissions within the namespace

Log:
```text
2021-06-04T08:55:31.607-0400    WARN    objectstore/dynamic_cache.go:446        unable to start watcher %!(EXTRA string=failed to list *unstructured.Unstructured: deployments.apps is forbidden: User "test user"@domain.com" cannot list resource "deployments" in API group "apps" at the cluster scope: requires one of ["container.deployments.list"] permission(s).)
github.com/vmware-tanzu/octant/internal/objectstore.(*DynamicCache).watchErrorHandler.func1
        /private/tmp/octant-20210513-13479-11rfxlz/src/github.com/vmware-tanzu/octant/internal/objectstore/dynamic_cache.go:446
k8s.io/client-go/tools/cache.(*Reflector).Run.func1
        /private/tmp/octant-20210513-13479-11rfxlz/src/github.com/vmware-tanzu/octant/vendor/k8s.io/client-go/tools/cache/reflector.go:210
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /private/tmp/octant-20210513-13479-11rfxlz/src/github.com/vmware-tanzu/octant/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /private/tmp/octant-20210513-13479-11rfxlz/src/github.com/vmware-tanzu/octant/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156
k8s.io/client-go/tools/cache.(*Reflector).Run
        /private/tmp/octant-20210513-13479-11rfxlz/src/github.com/vmware-tanzu/octant/vendor/k8s.io/client-go/tools/cache/reflector.go:208
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1
        /private/tmp/octant-20210513-13479-11rfxlz/src/github.com/vmware-tanzu/octant/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1
        /private/tmp/octant-20210513-13479-11rfxlz/src/github.com/vmware-tanzu/octant/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73
2021-06-04T08:55:31.607-0400    DEBUG   objectstore/dynamic_cache.go:390        stopping informer for apps/v1, Resource=deployments     {"dynamicCache": "forResource"}
```

It looks like it may be trying to view _all_ deployments, and then removing the listener because it failed to do so?

Additional logs:

![image](https://user-images.githubusercontent.com/6980197/120866467-ffd96600-c55d-11eb-907a-c73ee87c31e5.png)

**Environment:**

- Octant version (use `octant version`): 
Version:  0.20.0
Git commit:  b716185f5d9f85eeec5284a760d7f04dd0c03ab5
Built:  2021-05-13T18:19:29Z

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-gke.4900", GitCommit:"2812f9fb0003709fc44fc34166701b377020f1c9", GitTreeState:"clean", BuildDate:"2021-03-19T09:19:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
macOS

**Comment by GuessWhoSamFoo** [comment]
Fixed via 776b1c452b8cbba0881ea5c056f6f26080eacc8d
