### ISSUE TITLE
Change number of replicas of a deployment does not work via Summary --> Edit

### ISSUE THREAD

**Issue by psoppe** [vmware-tanzu/octant#2541]
Go to Workloads --> Deployments and select one,
In the summary tab click edit
Change the number of replicas.
Nothing happens. (Not even a http call)

If I go to the YAML tab and edit the replicas there, then the cluster is changed.

**Environment:**

- Octant version (use `octant version`): 
Version:  0.20.0
Git commit:  b716185f5d9f85eeec5284a760d7f04dd0c03ab5
Built:  2021-05-11T17:40:32Z

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
CentOS Linux release 8.4.2105

**Comment by GuessWhoSamFoo** [comment]
Fixed via 753b5df5fa8828a9b7a52a3ada76bb083b03baf6
