### ISSUE TITLE
Enhance list of namespaces

### ISSUE THREAD

**Issue by mashbrno** [vmware-tanzu/octant#2548]
**Describe the problem/challenge you have**

Having over 50 namespaces breaks the UI.

**Describe the solution you'd like**

- Scrollbar within the dropdown (now is whole page scrolling)
- Alphabetically sorted namespaces (now by age maybe)
- Allow filtering
- Show resources from all / multiple namespaces

**Environment:**

- Octant version (use `octant version`): 1.16-1.20
- Kubernetes version (use `kubectl version`): v1.21.0
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows

**Comment by mklanjsek** [comment]
@mashbrno thank you for opening this issue!  Would adding `Show more` at the bottom of than scrollable list, like we do for breadcrumb dropdowns, solve this problem for you?

**Comment by mashbrno** [comment]
Sure a *Show more* button can solve the scrolling point. Unfortunatelly I haven't found any example of a too long breadcrumb in my environment.

**Comment by minus7** [comment]
The *Show more* button, as it is now, makes little sense. If you need to access any of the later namespaces, it just adds an extra click. The list still expands to whatever length it was before. It'd be different if the list was sorted by most recently used namespaces (though that'd be a nightmare to find less often used namespaces in the list), but it isn't. Please consider reverting this change.

**Comment by mklanjsek** [comment]
@minus7 thank you for your feedback, opened #2762 to address remaining issues.
