### ISSUE TITLE
Windows hacking instructions.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#256]
Extend our HACKING.md to include specific instructions for Windows.

We may want to also consider adding a Windows specific Makefile?

**Comment by nopjmp** [comment]
Would a PowerShell script suffice here? Arguments could be similar to the make arguments to run functions in the PowerShell script as a dirty re-implementation of make.

**Comment by wwitzel3** [comment]
I think that would be fine, yes. @nopjmp let me know if this is something you are going to work on and I'll assign it to you.
