### ISSUE TITLE
Support for magefile

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#260]
By running mage out of vendor, makefile targets can be replaced by a series of `go run` commands and reduce tools needed for windows builds

See https://magefile.org/zeroinstall/

**Comment by wwitzel3** [comment]
@GuessWhoSamFoo do we still want to do this now that #408 is merged?

**Comment by GuessWhoSamFoo** [comment]
mage does remove the need for worrying about CLI code and have graph dependencies so the build script can be simplified. I think it is okay to leave open
