### ISSUE TITLE
NewFormFieldSelect cannot be retrieved by request.Payload.StringSlice in octant 0.21.0

### ISSUE THREAD

**Issue by mengdie-song** [vmware-tanzu/octant#2623]
**What steps did you take and what happened:**
I want to upgrade antrea-octant-plugin by using the latest 0.21.0 octant plugin API. However, I met an issue in the latest 0.21.0 octant but the same code can work in octant 0.16.1. 

I used component.NewFormFieldSelect for desTypeCol which is defined here https://github.com/antrea-io/antrea/blob/main/plugins/octant/cmd/antrea-octant-plugin/traceflow.go#L635. Now when I use 
request.Payload.StringSlice(dstTypeCol), it returns the error that shows payload does not contain this field. 

I did not meet this issue in previous 0.16.1 release, so I would like to know if there is any change in recent releases for this part which may cause this issue? Is there anything that my plugin needs to update?
Thanks a lot for your information!

**What did you expect to happen:**
request.Payload.StringSlice() can get the value defined in component.NewFormFieldSelect()

**Anything else you would like to add:**
Found some warning logs like below:
W0707 09:51:31.637535   18983 reflector.go:424] /__w/octant/octant/internal/objectstore/dynamic_cache.go:389: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding

**Environment:**
- Octant version (use `octant version`): 0.21.0
- Kubernetes version (use `kubectl version`):1.19
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):Ubuntu 18.04.3

**Comment by wwitzel3** [comment]
Sorry you ran in to this, we will take a look.

**Comment by wwitzel3** [comment]
This is fixed and will be part of the next nightly build and our 0.23 release which is coming out 03-Aug-2021
