### ISSUE TITLE
Unbound PVC still shown as "OK"

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/octant#2641]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I deployed a workload in a local cluster and introduced an error: the PVC spec calls a Storage Class that doesn't exist. The workload is not working, the PVC is not bound but Octant shows it in a "OK" state which can be confusing for troubleshooting.

![image](https://user-images.githubusercontent.com/82604841/125345989-d3fc8d80-e31e-11eb-9aef-52a9ca7cb160.png)

**What did you expect to happen:**
Octant should reflect the accurate status of a PVC
**Anything else you would like to add:**

**Environment:**

- Octant version (use `octant version`): 0.21.0
- Kubernetes version (use `kubectl version`): 1.21
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 11.3.1

**Comment by wwitzel3** [comment]
We may benefit from doing #381 first? If we had the list of storage classes, this would let us hint that it was non-existent.

**Comment by wwitzel3** [comment]
Extend the PVC printer to look at status and explicitly inform the user that their PVC is Unbound and potentially corelate that with recent events.

**Comment by wwitzel3** [comment]
3 areas for UI
- resource viewer
- summary
- list

**Comment by ftovaro** [comment]
To be honest this one looks really interesting, if is possible I'd like to take it and work it together with @mklanjsek if he's ok with it

**Comment by davidmirror-ops** [comment]
This is what i see from kubectl:

davidespejo@daespejo-a01 code % kubectl get pvc
NAME        STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS       AGE
www-web-0   Pending                                      my-storage-class   16s

**Comment by wwitzel3** [comment]
@ftovaro Checking to make sure you have all the info you need to start on this issue?

**Comment by ftovaro** [comment]
@davidmirror-ops is it possible to share the config file of the pvc?

**Comment by davidmirror-ops** [comment]
sure @ftovaro 

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: www-web-0
  
spec:
 storageClassName: "my-storage-class"
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 2Gi
```
