### ISSUE TITLE
Set user agent for octant

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#273]
User agent is `User-Agent: octant/v0.0.0 (darwin/amd64) kubernetes/$Format`. At the minimum, it should
contain the current version of Octant.

**Comment by rajatjindal** [comment]
Hi Bryan,

I am almost done with the changes for this, and will submit the PR in a short while.

**Comment by rajatjindal** [comment]
The instructions in Hacking.md does not seem to work for me. I am running it with minikube and keep getting error "api handler not found: /api/v1/namespace"

any pointers what I could be doing wrong?

**Comment by rajatjindal** [comment]
it started to work after I ran "make ui-server" a couple of times, and I tested it and it seems to be working as expected.
