### ISSUE TITLE
Pods don't know logs after they are exited

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#2840]
**What steps did you take and what happened:**

Created a job that spawned a pod. The pod exited successfully, but I can no longer see the logs in the pod view.

**What did you expect to happen:**

The logs for a non-running pod should be available. They are available using kubectl.

**Environment:**

- Octant version (use `octant version`): 

```
Version:  0.23.0
Git commit:  fbe2be3b687b3e2199ea32753281c9de1f334171
Built:  2021-08-02T21:52:01Z
```

- Kubernetes version (use `kubectl version`): 1.20.5
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.something

**Comment by wwitzel3** [comment]
I wonder if this is a bug with the duration? When you set the duration to since "Creation" if they show up?

**Comment by bryanl** [comment]
This was likely user error. I'm going to close this.
