### ISSUE TITLE
Hugo not rendering Markdown tables correctly

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/octant#2846]
**What steps did you take and what happened:**

Using this Markdown code:

```
|Value|Description|
|:----:|-----|   
|Pending|Configuration accepted by the server but not ready to run (e.g. init containers, pending image fetching, among others)|
|Running | All of the Pod's containers created, at least one of them is running|
| Succeeded | All containers successfully completed their task and then exited, especially true in the presence of OnFailure [restartPolicy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) |
| Failed | All containers terminated and at least one terminated in failure|
| Unknown| Most likely the node is offline |
```
Hugo renders it as a table but with no horizontal or vertical lines:

![image](https://user-images.githubusercontent.com/82604841/132769785-a6f6c33e-f204-48e5-a8cd-108fb21faced.png)

**What did you expect to happen:**
Table should have both vertical and horizontal lines, like the tables on this site: http://docs.paket.id/API/Versi_2.html

**Anything else you would like to add:**

I tried to use a Hugo custom shortcode with no success
**Environment:**

- Octant version (use `octant version`): 0.23
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by GuessWhoSamFoo** [comment]
Closed via #2848

**Comment by davidmirror-ops** [comment]
Thanks

How should i use the styling in the Markdown file?

What I currently do is to wrap the table in:
```
{{<table "table table-striped table-bordered">}}
...
{{</table>}}
```

**Comment by GuessWhoSamFoo** [comment]
You don't have to wrap the table in anything
