### ISSUE TITLE
clicking a pod heptigon doesn't load pod summary

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#303]
When using the resource view and selecting a pod (which may be many pods), clicking an individual pod heptigon from the side nav changes the URL but no pod summary is rendered.

**Comment by wwitzel3** [comment]
This is due to the namespace being reset to `default` when you follow the link.

**Comment by GuessWhoSamFoo** [comment]
Turns out the fix is a one-liner, but e2e testing resource viewer is more difficult. Visual testing via something like Percy seems to be the way to go but researching this a little further
