### ISSUE TITLE
Port Forwarding Not Available in v0.25.0

### ISSUE THREAD

**Issue by tetricky** [vmware-tanzu/octant#3057]
Used the .deb v0.24.0 installer to remove v0.24.0, then used the v0.25.0 .deb installer to install v0.25.0

Port forwarding is now greyed out, and unavailable

I expected port forwarding to function as per the previous version. I have read the changelogs and the documentation, and can't see any identifiable other steps I should have taken. I may be wrong.

Reverting to v0.24.0 restores the functionality.

On ubuntu 21.10, connecting to a remote cluster, using kubeconfig to connect directly to the cluster (debian bullseye operating system on the nodes).

- Octant version: v0.25.0
- Kubernetes version:  k3s (v1.21.5+k3s2)
- OS: ubuntu 21.10

**Comment by delcerrocristian** [comment]
The same problem:

- Octant version: v0.25.0
- Kubernetes version: v1.21.2
- Docker version 20.10.7
- MacOs version: 10.15.7

**Comment by rashid4lyf** [comment]
+1

**Comment by lerytke** [comment]
Same on Windows 11
