### ISSUE TITLE
bump version in chocolately

### ISSUE THREAD

**Issue by benjarrell** [vmware-tanzu/octant#3155]
**What steps did you take and what happened:**
If I run `choco install octant` I get version 0.24

**What did you expect to happen:**

It should install the newest version, right now is 0.25.

**Environment:**

- Octant version 0.24
- Kubernetes version: `v1.23.3`
- OS: Windows 10

**Comment by GuessWhoSamFoo** [comment]
https://community.chocolatey.org/packages/octant/0.25.1
