### ISSUE TITLE
Expose launch command in public api

### ISSUE THREAD

**Issue by GarySmith** [vmware-tanzu/octant#324]
In airshipui we are trying to distribute our ui as a single go executable. But before launching directly into octant there is some pre-launch logic that needs to be executed. So the plan is to write a small amount of wrapper code that imports octant and launches it octant by calling internal/commands/dash/newOctantCmd. But since this is in an internal package, it is not callable by another package. 
If this were exposed in the public api (pkg/...), then it would enable this usage.

**Comment by wwitzel3** [comment]
I think this should be possible, we'll need to consider the public API of an OctantCmd and look at what we currently are exposing as part of that.

**Comment by wwitzel3** [comment]
We will be tracking and doing this work on issue #204.
