### ISSUE TITLE
Support kubernetes 1.16 API for function pkg/store/get_as.go#L71

### ISSUE THREAD

**Issue by mengdie-song** [vmware-tanzu/octant#345]
For kubernetes 1.16 API, Object has no field or method SetInitializers/GetInitializers.
So I have got compile issues when trying to import octant module to my project.
The issue exists in this line https://github.com/vmware-tanzu/octant/tree/master/pkg/store#L71

**Comment by wwitzel3** [comment]
We do some conversions with Unstructured objects. Finalizers were removed from Unstructured. We need to update our calls to reflect this.

https://github.com/kubernetes/apimachinery/commit/724b2a96076bf3ad4aae4c1e7f814d561ed85a16#diff-da08a78cec0f5fdb7eaadef2a7a4261d

**Comment by wwitzel3** [comment]
This is fixed in master now.
