### ISSUE TITLE
Octant website review and content

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#357]
- [x] Move files from `/docs` to `site`
 - [x] Deep linking slack URL
 - [x] Dollar sign must be followed by output to keep linter happy (Adding linting tool to CI?)
 - [x] Linking to headers
 - [x] Update ruby gems
 - [x] Move hacking and roadmap to site
 - [x] Remove master from sidebar
 - [x] Fix code wrap for console output

**Comment by jonasrosland** [comment]
Are we all set with this? Anything else that needs changed?
