### ISSUE TITLE
Add a Storage Class page to list the existing storage classes

### ISSUE THREAD

**Issue by zedtux** [vmware-tanzu/octant#381]
AFAIK there is no page where to see existing Storage classes, so adding one would be nice.

**Comment by zedtux** [comment]
A page for the Persitent Volumes would be great too !

**Comment by wwitzel3** [comment]
Hard part about this is finding the various storage class providers. Depending on the Kubernetes flavor you may have to add a big switch statement for all the various providers.

It is unknown if there is a way to get this information directly from the API without having to know the endpoints explicitly.

**Comment by wwitzel3** [comment]
Look at existing printers for how to implement a new printer for a resource type in Octant, for example https://github.com/vmware-tanzu/octant/blob/master/internal/printer/mutatingwebhookconfiguration.go

**Comment by wwitzel3** [comment]
Fixed by https://github.com/vmware-tanzu/octant/pull/2059
