### ISSUE TITLE
Event messages are sorted inconsistently

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#404]
![event-sort](https://user-images.githubusercontent.com/10288252/68255951-8aa15a00-ffe3-11e9-959e-d1acf8e992f6.gif)

Emitted events should appear chronologically and should not move around on a table component.

**Comment by alexbrand** [comment]
Was this fixed by #419?

**Comment by wwitzel3** [comment]
Yes.
