### ISSUE TITLE
Write up a 0.10 release blog post

### ISSUE THREAD

**Issue by jonasrosland** [vmware-tanzu/octant#406]
Write up a blog post for 0.10, with information about:

* What major news are included in 0.10 - application view?
* Big changes that has happened to Octant since initial open source release (perhaps a quick plugin overview? maybe that should be it's own blog post, but is worthwhile mentioning quickly here) - last blog post was in August
* The new release cadence, and why that will happen
* Nightly builds! You want them, we have them. They might be broken, they might be awesome :)

A draft in Google Docs or similar at least 2 days before 0.10 release would be great, so we can fine-tune it before things go live.

**Comment by wwitzel3** [comment]
started drafting this, https://hackmd.io/752FdXlpRBmaUba6TtUdQQ?both
