### ISSUE TITLE
Expose octant events to plugins

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#425]
From slack: https://kubernetes.slack.com/archives/CM37M9FCG/p1573802430117600

Example use case: allowing querying namespaces to generate more specific keys for use with printers.

**Comment by wwitzel3** [comment]
Done #844 

The specific case referenced in the slack link is to know when a user has changed the current namespace.

Plugins can handle the `action.octant.dev/setNamespace` action to get the new namespace via the action payload.
