### ISSUE TITLE
wrong mode on in-cluster configuration

### ISSUE THREAD

**Issue by sigmonsays** [vmware-tanzu/octant#426]
the default mode of 256 on the volume secret does not work correctly for the user in the container to read the secret.

I built the image using the dockerfile from https://hub.docker.com/repository/docker/sigmonsays/octant.

snippet from https://github.com/vmware-tanzu/octant/blob/master/examples/in-cluster/deployment.yaml#L39

fix is this
```
       volumes:
         - name: kubeconfig
           secret:
             secretName: octant-kubeconfig
-            defaultMode: 256
+            defaultMode: 292 # 0444
```

**Comment by wwitzel3** [comment]
Hi @sigmonsays 

We are removing the in-cluster example from the repo, see #450.
