### ISSUE TITLE
octant-plugin K8s API compatibility issue

### ISSUE THREAD

**Issue by mengdie-song** [vmware-tanzu/octant#432]
Hi octant team,

When I am writing the octant plugin for antrea, I need to import octant to antrea project.
However, these two projects have been using different K8s API versions.

Currently, I have upgraded antrea K8s version to 1.15.0 to import octant@v0.8.0, since octant K8s API version is 1.15.0. 
But for octant master branch and v0.9.0, K8s version is kubernetes-1.18.0-alpha.0.
I have already got an issue (https://github.com/vmware-tanzu/antrea/issues/111) regarding this.

As a result, I would like to know what the K8s version that octant will use in your later release. Is there any plan to use K8s official API version, like 1.16.0? Or do you have any suggestion for me to make octant-plugin to be compatible with antrea project?

Thanks for your help!

**Comment by wwitzel3** [comment]
Right now we currently have no plans around this. I think we can do a better job here though. I will give this some thought and work with @bryanl and @GuessWhoSamFoo to determine what we want our official versions to be and what it looks like when we plan to change those versions between releases.

**Comment by mengdie-song** [comment]
Thanks Wayne! 
It will be very helpful for antrea-octant-plugin. Antrea will upgrade K8s API automatically when I import octant. For now, we have to keep these to projects K8s API consistent.  Looking forward to know official K8s API version for your future release.

**Comment by mengdie-song** [comment]
@wwitzel3 Hi Wayne, is there any update for this issue? I am wondering which version of K8s API that Octant is going to use in the later release? Is it going to be an official version of K8s API?

**Comment by wwitzel3** [comment]
@mengdie-song So we plan on fixing this so that you no longer need to import octant to write a plugin. We are going to extract the plugin library to avoid things just like this.

**Comment by mengdie-song** [comment]
@wwitzel3  That will be great, thanks!

**Comment by mengdie-song** [comment]
Hi @wwitzel3, could I know the status of plugin library extraction?
Both Antrea and Octant now have imported K8s related repositories and Antrea has to use the same K8s libraries with Octant when we import Octant module. 
Some of Antrea features depend on K8s repositories which are different from what Octant currently uses. These features are pending on this issue fix.

**Comment by wwitzel3** [comment]
Octant moving forward will pin to official releases of the Kubernetes libraries and if we need fixes in a beta/alpha version we will explicitly vendor those in. This should prevent this type of scenario in the future.

We will also happily work to enable Plugin API capabilities that are not currently available to allow plugin authors to get things done. As of this writing we have added Delete, Create/Update, and SendEvent, which I know were all on the teams list of wants previously.
