### ISSUE TITLE
Container's attributes formatting for long values and command

### ISSUE THREAD

**Issue by zedtux** [vmware-tanzu/octant#433]
![Screenshot 2019-11-19 at 09 41 34](https://user-images.githubusercontent.com/478564/69130561-005ff800-0ab1-11ea-99df-d6e182ccf347.png)

There are container's attributes that will always be too long for the block to be displayed correctly, so they have to be treated differently.

## Command & Args

The very first one that needs a lot more love is the `command` one, which could be a bash script so could be very long.

I took a small example here, but obviously it can be much more longer.

This one should be embed in `<code>` tags (`<pre>` too perhaps ?) so that is can fit the block and scrollbars will allow to easily scroll in the command.

Code coloration would be awesome, but that would be quite hard as it could be any kind of language, excepted if you decide that `command` can only be Shell/Bash.

## Docker ID

This one will always be that long, so it should be in a div with horizontal scrollbar only enabled.

## Environment & Volumes

Using a table here doesn't work well as the environment variable names could be quite long, and their values too, same for the volumes.

I would suggest to switch to a vertical table per attributes so that it has a lot of length to print the values like that:

![Screenshot 2019-11-19 at 10 13 21](https://user-images.githubusercontent.com/478564/69132907-3ef7b180-0ab5-11ea-8b36-09f2d6c3cf21.png)

The style should be a little bit more compact and perhaps in a scrollable div.

**Comment by zedtux** [comment]
This is also true for the ConfigMap's **Data** block where the content could be much better formatted.

**Comment by wwitzel3** [comment]
@rossfenrick some of issues you're creating I think solve some, if not all of this?

**Comment by rossfenrick** [comment]
@wwitzel3 It does solve some of it but not all. I'll go through and make designs for these

**Comment by GuessWhoSamFoo** [comment]
Long config map blocks are now better formatted via f29e294517357683ef64d03cde78da462ca50b70

![image](https://user-images.githubusercontent.com/10288252/76650025-07f35300-651f-11ea-959a-89f93ab19ac4.png)

Readability is also improved with improved scrolling in 3341e3ac4c00d15e15907675e39162c92d1cf008

![image](https://user-images.githubusercontent.com/10288252/76650140-35d89780-651f-11ea-9458-be248e7ba6c2.png)

**Comment by wwitzel3** [comment]
The latest versions of Octant address the core of the original issue. I'm going to close this, but feel free to open a new issue if you would like to see further updates to the container card we display in Octant.
