### ISSUE TITLE
Feature Request: octant start and octant stop

### ISSUE THREAD

**Issue by danielhelfand** [vmware-tanzu/octant#436]
**Version:** 0.9.1

It would be nice to have the ability to start up octant without leaving it hanging from the command line. Are there plans to add `octant start` and `octant stop` commands to make it simple to leave octant running and stop it?

**Comment by GuessWhoSamFoo** [comment]
Where would logs be expected to go with start and stop commands?

**Comment by danielhelfand** [comment]
For my particular case, I would not want to see any logging after running start. However, there could be a flag associated with the command (e.g. —show-logs) that could support showing logs instantly after starting. 

There could also be a completely separate logs command that could be run to show logs if you don’t run —show-logs after starting octant.

**Comment by mikeroySoft** [comment]
What if we had ~/.octant/logs/ ?

**Comment by bryanl** [comment]
There are no current plans. Is it not possible to background octant and redirect stderr?

**Comment by wwitzel3** [comment]
Though Octant uses a built-in webserver and browser to serve its UI, at this time it is primarily designed to be a single binary, local application. Eventually Octant will better abstract away the details of how it is functioning (for example using Electron), but for now, those details are exposed.

If you find yourself wanting to do process control of the Octant binary you may consider using something like http://supervisord.org/ or other tools that exist for this purpose.
