### ISSUE TITLE
Octant Error on Windows

### ISSUE THREAD

**Issue by jungopro** [vmware-tanzu/octant#437]
```bash
Error command/dash.go:96 dashboard failed {"err": failed to init cluster client: invalid configuration: no configuration has been provided"}...
```

**Environment**

- Windows 10
- Dark site (no internet)
- Octant 0.9.1

**More Info**

- I'm able to access cluster using kubectl
- I have multiple kubeconfig files (1 for each cluster)
- KUBECONFIG is configured and verified via kubectl
- I tried running octant with --kubeconfig flag and got the same error

**Comment by alexbrand** [comment]
@jungopro Can you try getting more logs by passing `-v=10` to octant?

**Comment by wwitzel3** [comment]
If you're still having this issue on the latest version of Octant please feel free to re-open and we will take a look.
