### ISSUE TITLE
Include kube-system namespace in drop-down

### ISSUE THREAD

**Issue by glyn** [vmware-tanzu/octant#442]
`kube-system` does not seem to be included in the namespace dropdown. I installed `tiller` into `kube-system`, so it would be helpful to be able to use `octant` to probe objects in that namespace, same as any other.

Not sure what version of `octant` I'm running, but I installed it using homebrew a few minutes ago.

**Comment by GuessWhoSamFoo** [comment]
Do you have permissions to the `kube-system` namespace from the current context?

**Comment by glyn** [comment]
> Do you have permissions to the `kube-system` namespace from the current context?

Yes. For example, `kubectl get pods -n kube-system` lists all the pods in that namespace.

**Comment by GuessWhoSamFoo** [comment]
Can you post the console output of `octant -v`? This case should be handled (e.g. can't reproduce this on a kind cluster) so there might be a bug somewhere or cluster configuration that we haven't considered.

**Comment by glyn** [comment]
`octant -v` seems to keep on going, but I've captured a [prefix](https://gist.github.com/glyn/b81b230ed581b3131ff09223d3cf103d) of it. Hope that's sufficient.

**Comment by glyn** [comment]
I'm using a GKE cluster.

**Comment by wwitzel3** [comment]
I tried the latest Octant against a GKE cluster and I was able to access the kube-system namespace. What version of kubernetes is your GKE cluster and what version of octant (`octant version`) are you running?

**Comment by glyn** [comment]
The GKE master version is 1.14.8-gke.17. I updated to octant 0.9.1 and can now access the kube-system namespace.
