### ISSUE TITLE
Octant crashing

### ISSUE THREAD

**Issue by hellobhaskar** [vmware-tanzu/octant#447]
Our octant instance is running behind nginx reverse proxy. We have RP configured with below settings. our octant is running as pod inside kubernetes cluster. 

 proxy_set_header HOST $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwaded-For $scheme;

        proxy_pass http://octant.utils.svc.cluster.local:8080;
        proxy_read_timeout 300;
        proxy_connect_timeout  300;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        keepalive_timeout 30;

Frequently the pod crashes when request is fired from browser  with below stack trace. any suggestions ?

`github.com/vmware-tanzu/octant/internal/api.serveWebsocket
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:42
github.com/vmware-tanzu/octant/internal/api.websocketService.func1
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:34
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/vmware-tanzu/octant/internal/api.rebindHandler.func1.1
	/go/src/github.com/vmware-tanzu/octant/internal/api/middleware.go:52
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
github.com/gorilla/handlers.(*cors).ServeHTTP
	/go/pkg/mod/github.com/gorilla/handlers@v1.4.0/cors.go:135
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1890
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1463d85]`

**Comment by wwitzel3** [comment]
Hi @hellobhaskar 

I apologize for the confusion as we have let some of the features we have added to aid in development leak out in to the usage of Octant.

Though Octant currently uses a web browser for the client UI currently, it is a local application that isn't really designed or currently intended to be run a remotely hosted fashion. Eventually Octant will ship with a client built using Electron.

I've created a PR which updates the documentation and clearly marks flags as for development purposes. (#450)
