### ISSUE TITLE
Add option to allow overriding base URL for hosting at sub URL of site.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/octant#449]
Currently the web application is hosted at the root of the site. Provide an option such as ``--app-base-url`` so that you can host it at a sub URL. This would be useful when needing to use a front end proxy, but where the proxy wants to host it at a sub URL on ``/console``. If this is supported using existing options or environment variables, I can't find a way of doing it.

You also can't have the proxy use ``/console`` but then strip the prefix from the URI path and send through as ``/`` because all the generated URLs in pages appear to be absolute because of use of ``<base href="/">``. Thus paths are evaluated as ``/...`` rather than ``/console/...`` if there were processed as being relative.

**Comment by wwitzel3** [comment]
Hi @GrahamDumpleton,

We've done a poor job of letting flags and variables that were intended to aid development leak out to the user level, I apologize for that. With that said, Octant is an application and is intended as a single client tool and at this time we have no plans to support hosted versions of Octant.

Currently we use the default web browser on the system as our UI client. Octant will eventually be packaged with a client, probably using Electron or similar. This will further abstract away the details of the internals and hopefully remove the confusing messaging around how to run Octant.

There is possibly that in the future, we would add some ability to remotely share/view another Octant, but that would look more like what you see with vscode live share or tmate sharing.

I've created a PR that updates our documentation a bit and clearly labels flags and environment variables as being intended for development purposes. (#450).
