### ISSUE TITLE
Documentation on Removing a Plugin

### ISSUE THREAD

**Issue by danielhelfand** [vmware-tanzu/octant#464]
Not sure if this is documented or shown somewhere already, but wanted to ask if there's any information on removing a plugin from Octant? If not available, it would be nice to add some information with the [plugin documentation](https://octant.dev/docs/master/plugins/).

**Comment by wwitzel3** [comment]
To remove a plugin, you would delete the binary for the plugin from the octant plugin folder. Which defaults to `~/.config/octant/plugins`. I think added a note to the plugin documentation that to remove a plugin, you delete the binary is a good idea.
