### ISSUE TITLE
Overall services view in Octant

### ISSUE THREAD

**Issue by texanraj** [vmware-tanzu/octant#466]
Is there a way in Octant to see the connection between various services? Right now I can see only individual services. Thanks.

**Comment by wwitzel3** [comment]
Hi @texanraj , I was wondering if you could expand on this some.

Where are you expecting to see these connections? How are you making these connections, can you provide some examples of configurations you are trying to visualize?

**Comment by wwitzel3** [comment]
Closing this out, but feel free to reopen with some more detail of what you're hoping to see.
