### ISSUE TITLE
Community Development Around Plugins

### ISSUE THREAD

**Issue by danielhelfand** [vmware-tanzu/octant#468]
What are the thoughts at this time around developing plugins and contributing them so that others can use these plugins? How would one go about using a plugin that has been contributed?

**Comment by wwitzel3** [comment]
We are encouraging folks to use the `octant-plugin` topic for their repos. See: https://github.com/topics/octant-plugin

As of right now we don't maintain a curated list of "official" octant plugins. This maybe something we will look in to doing as we get closer to 1.0.

**Comment by danielhelfand** [comment]
@wwitzel3 Thanks! I'll check out what's available under the topic.
