### ISSUE TITLE
Quick-Switcher event key (k) is too greedy.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#474]
Anytime the `k` key is typed the quick switcher is activated. Field edits / typing in to the TTY terminal on the issue-135 feature branch.

Place the quick switcher behind a more complex key sequence to avoid conflicts with data entry.

**Comment by alexbrand** [comment]
Ah yeah. The naked `k` is definitely going to conflict with just regular typing. Thanks @wwitzel3 .

I think I am gonna go with `ctrl + k`. Open to other suggestions.
