### ISSUE TITLE
Resources usage information

### ISSUE THREAD

**Issue by jnavarro86** [vmware-tanzu/octant#482]
Thanks for developing this awesome tool guys!

I was wondering if there are plans to add resources usage info in the widgets of K8s resources like pods or nodes. Would it be useful to see things like % of  CPU/Memory that the resources are using from the allocated requested/limits?.

**Comment by bryanl** [comment]
This is currently in process. The first PR is https://github.com/vmware-tanzu/octant/pull/452. There will be a couple of follow on PRs to link this new view to a new resource viewer that will include all the resources in a workload.
