### ISSUE TITLE
Update Chocolatey Package to 0.9.1

### ISSUE THREAD

**Issue by danielhelfand** [vmware-tanzu/octant#485]
The [package](https://chocolatey.org/packages/octant) is still on version 0.8.0. Would be nice to get the latest version in.

**Comment by GuessWhoSamFoo** [comment]
Updated 0.9.1 submission with the new requested package metadata from maintainers. Pending approval.

**Comment by danielhelfand** [comment]
@GuessWhoSamFoo Thanks!
