### ISSUE TITLE
Feature request: log aggregation

### ISSUE THREAD

**Issue by yujunz** [vmware-tanzu/octant#486]
It would be nice to aggregate the logs by deployment/daemonset/statefulset/service and etc since It is common in Kubernetes that a workload is served from multiple replicas of pods.

When an end user checks log *for an application*, he is not looking for an arbitrary pod but the exact pod serving the request or several pods if there is some kind of load balancer. However there is no quick way to do it in octant as mentioned in [the slack thread](https://kubernetes.slack.com/archives/CM37M9FCG/p1576462345009500)

Practically, octant may select pods with the same selector described in the parent object (e.g. `Deployment/spec/selector`), tail the logs, and aggregate them to the same console. 

Example output as below:

```
kube-proxy-zhqtm:kube-proxy I1216 08:34:13.443176       1 graceful_termination.go:93 lw: remote out of the list: 10.233.0.1:443/TCP/10.0.1.198:6443
kube-proxy-zhqtm:kube-proxy I1216 08:35:13.443660       1 graceful_termination.go:93 lw: remote out of the list: 10.233.0.3:53/TCP/10.233.92.70:53
kube-proxy-rq22z:kube-proxy I1216 08:10:13.863016       1 node.go:135 Successfully retrieved node IP: 10.0.1.101
kube-proxy-rq22z:kube-proxy I1216 08:10:13.863090       1 server_others.go:176 Using ipvs Proxier.
```

Interleaving or time order does not matter much. What is most important is to view related logs in one place.

**Comment by GuessWhoSamFoo** [comment]
The aggregated logs for a given application should go under the workloads view as described in #668. Closing to deduplicate
