### ISSUE TITLE
External plugins not unit testable

### ISSUE THREAD

**Issue by GarySmith** [vmware-tanzu/octant#491]
We are developing an octant plugin that does not reside in the octant source tree and it appears that unit testing portions of it are not feasible. For example, the handleFunc that the plugin supplies (which is returned by router.Match) is invoked with a service.Request object, and service.Request contains private fields (dashboardClient, baseRequest) that cannot be assigned to or even mocked out.

The basic problem is that interfaces and types that are part of the plugin API need to be completely public so that they can be developed and tested outside of the octant source tree.

**Comment by GarySmith** [comment]
The most immediate problem then is to fix the dashboard field in `service.Request` so that it is public. Simply renaming it to `Dashboard` conflicts with an existing function with the same name. I'm not sure whether the octant team would prefer to rename that function (and possibly break existing callers) or to rename the field to something else. Which would you prefer?

**Comment by GarySmith** [comment]
Upon further re-inspection, the private `baseRequest` struct in contained in `service.Request` is even more problematic. Plugins that use the context in order to do meaningful work obtain it via `request.Context()`, and that `Context` function in turn is implemented by `baseRequest`. So writing a unit test also will require the ability to instantiate base request or somehow override the `Context()` to return a mock.
Note that `baseRequest` is also a private member of all of the other `*Request` structs in service.go.

**Comment by bryanl** [comment]
After some deliberation, I've decided our current implementation of plugins is untenable. Going to look at a re-write and include a method to make them testable in the very near future.

**Comment by GarySmith** [comment]
Thanks @bryanl for your attention on this; it is most appreciated. As a verification step, it would be good to create a sample plugin (much like the existing one) that is separate from the octant repository so that there are not any hidden dependencies on private/internal data or types.

**Comment by GuessWhoSamFoo** [comment]
Partially addressed by #645. We should consider moving the sample plugin to a separate repo in the near future/

**Comment by wwitzel3** [comment]
Sample plugins now located at https://github.com/vmware-tanzu/octant-example-plugins
