### ISSUE TITLE
Make volume in PVC and PVC list printer a link.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#503]
Volume should be a link.

https://github.com/vmware-tanzu/octant/blob/e19d377eee854fd8f611c2400f098be1c697c5a2/internal/printer/persistentvolumeclaim.go#L50

https://github.com/vmware-tanzu/octant/blob/e19d377eee854fd8f611c2400f098be1c697c5a2/internal/printer/persistentvolumeclaim.go#L157

**Comment by aschiefe** [comment]
Should volume be a navigation link as well along side persistent volume claims?

**Comment by wwitzel3** [comment]
Yes. I think it makes sense for volume as well.

**Comment by aschiefe** [comment]
Ok, would you be so kind as to assign this to me? I don't believe I have the permissions to self assign.

**Comment by wwitzel3** [comment]
Hey @aschiefe wanted to check in and see how things were going with this one? Need any assistance or have any questions?

**Comment by aschiefe** [comment]
I got pulled off to work on other things, just got back to it today.  I'm having to walk through the code with delve to try to figure out how to get data up from k8 and out to the browser.  Now that I have a working good working local env setup I may get a little further but could always use help fixing my nascent understanding of both octant and working in a large go project.

**Comment by wwitzel3** [comment]
hey @aschiefe how's this coming along?

**Comment by aschiefe** [comment]
Bad news I'm not making progress.  But good news @dotNomad is.  I believe he's going to take this issue over due to my inability to make progress.

**Comment by dotNomad** [comment]
Things are going well here. Lot of learning to be done on printers and connecting them to the rest of Octant, but am mostly there. If you could assign this to me @wwitzel3 that would be great.

**Comment by wwitzel3** [comment]
@dotNomad will you be at the community meeting tomorrow? we can use the last half of the meeting to do a Printer walk-through if you think that would be helpful.

**Comment by dotNomad** [comment]
> @dotNomad will you be at the community meeting tomorrow? we can use the last half of the meeting to do a Printer walk-through if you think that would be helpful.

I will be. That sounds helpful. I think I have a decent idea of how to setup these printers, but more information could shine some light on things I've missed or maybe misunderstand. Thanks!
