### ISSUE TITLE
Show a better loading screen.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#506]
We should show a loading screen while we wait for content response length to be greater than 0.

https://github.com/vmware-tanzu/octant/blob/d48f76ced7939d837c1995f6b43acebf3d54bd47/web/src/app/modules/overview/overview.component.ts#L148

**Comment by rossfenrick** [comment]
imo it should just be the Large 72px × 72px Clarity Spinner component, centered in the page. 
![octant-loading](https://user-images.githubusercontent.com/7506366/71851167-c5c71480-308a-11ea-9c38-3b2ca0f90922.png)

**Comment by wwitzel3** [comment]
related #362
