### ISSUE TITLE
Running a Dockerized version 

### ISSUE THREAD

**Issue by dyennam** [vmware-tanzu/octant#507]
Hi, I am trying to create a dockerized version of octant so that we can host it on a VM.
 I created a docker image which runs without errors, but i am unable to access the dashboard.
`    
  
    FROM ubuntu:18.04
    USER root

    # Install octant v0.9.1s
    RUN apt-get update && \
        apt-get install -y --no-install-recommends wget ca-certificates && \
        wget -q https://github.com/vmware-tanzu/octant/releases/download/v0.9.1/octant_0.9.1_Linux-64bit.deb && \
        dpkg -i octant_0.9.1_Linux-64bit.deb && \
        apt-get remove -y wget ca-certificates && \
        rm -rf octant_0.9.1_Linux-64bit.deb /var/cache/apt/* /var/lib/apt/lists/*

    # EXPOSE 7777

    # COPY the KubeConfig File into container
    RUN mkdir ~/kube
    COPY kubecfg ~/.kube

    ENV OCTANT_DISABLE_OPEN_BROWSER="TRUE"
    # ENV OCTANT_LISTENER_ADDR="8081"
    ENV OCTANT_ACCEPTED_HOSTS="localhost, 127.0.0.1, 0.0.0.0, 172.17.0.2" 
    ENTRYPOINT ["/usr/local/bin/octant", "--kubeconfig=/usr/local/bin/config-full"]

    # docker run radon.swf-artifactory.lab.phx.axway.int/metrics/metrics-octant:v1`

Its says that the dashboard is available at 777 port but no matter how I try to access it, I am unable to access it.
![image](https://user-images.githubusercontent.com/4074631/71297947-ce0d1900-2342-11ea-8ab3-4f41d22d8d95.png)

I tried to follow this Issue: https://github.com/vmware-tanzu/octant/pull/450
But i am not able to understand it. As in does it say that "Octant" its not meant to be hosted remotely?
Please let me know if I am going about this the wrong way.

**Comment by wwitzel3** [comment]
We are in the process of moving Octant to run using Electron. Once we have completed that work we will update our documentation around running Octant via a docker container. It will involve passing in the proper environment variable to set the DISPLAY so the proper X server is used.

**Comment by wwitzel3** [comment]
As mentioned in #450 Octant is a desktop application. To run it in docker, you would package Octant with a kubeconfig and ensure the correct DISPLAY was set. The DISPLAY would be an X server that allows remote connections.

**Comment by dsiebel** [comment]
@dyennam just stumbled upon this issue while trying to figure out how to run octant in a docker container on mac. This did the trick for me:
Run `octant` with `--disable-open-browser --listener-addr "0.0.0.0:7777"` and make sure to publish the port when using `docker run`, i.e. `docker run -p 7777:7777`. Works like a charm!

**Comment by dyennam** [comment]
@dsiebel Quick Question.
What directory did you copy your kubecfg file to?

**Comment by dsiebel** [comment]
Since my container is running with root I mount it to /root/.kube/config.
But you can also use octant‘s —kubeconfig option to set it to wherever you
copied the config to.

**Comment by dsiebel** [comment]
Looks like I was a bit too enthusiastic with my solution: switching contexts and namespaces doesn't work in my docker container (yet!)

**Comment by dyennam** [comment]
@dsiebel Thanks for the feedback, i thought i was doing it incorrectly when it wasn't able to pickup my KUBECONFIG file.
Another thing is, i couldn't get it to run with the scratch image. I had to use CENTOS. Not sure of the reason.
https://gist.github.com/dyennam/9fabc8f35929f9ca3de9c79ee3d54d31

**Comment by dsiebel** [comment]
Hey @dyennam, I don't want to spam this issue any further. I am neither a maintainer of this repository nor a support engineer for docker 😉 
I will move the discussion to your gist to point out a couple of things I noticed.

**Comment by aleveille** [comment]
For what it's worth, I've made a ready-to-use published Docker image and Helm chart to deploy to Kubernetes: https://github.com/aleveille/octant-dashboard-turnkey

For anyone looking to deploy to Kubernetes, you can hop over there as I will likely maintain that repo for a couple months/years.
