### ISSUE TITLE
Add method to copy secret values into the clipboard

### ISSUE THREAD

**Issue by alexbrand** [vmware-tanzu/octant#512]
When viewing a secret, it would be useful to have a way to copy the base64 decoded value of a secret into the clipboard.

Maybe something like this:

![image](https://user-images.githubusercontent.com/545723/71311952-74b0f280-23f3-11ea-9f72-f8692e724fef.png)

**Comment by rossfenrick** [comment]
I'd recommend using Clarity's copy-to-clipboard icon here
![octant-copy](https://user-images.githubusercontent.com/7506366/71851522-9d8be580-308b-11ea-8971-bcd256396e96.png)

**Comment by tylerphelan** [comment]
we'd life this as well!

**Comment by sampeinado** [comment]
build service folks would appreciate this - especially if the button can give a bit of feedback to the user after its pressed! like a little "copied!" toast pops up for a second

**Comment by GuessWhoSamFoo** [comment]
Adding this to 0.20 as it seems fairly trivial

**Comment by pivotal-mikegresham** [comment]
ref: tdc 
ref: tbs
