### ISSUE TITLE
Create editor component for Octant based on Monaco

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#522]

**Comment by wwitzel3** [comment]
Current monaco-editor uses typescript 3.7
Angular 8 is <3.6

We would have to go back to a version of Monaco from almost a year ago to find one that uses typescript 3.5.

Angular 9 which is currently in RC phase, supports typescript 3.7.

**Comment by GuessWhoSamFoo** [comment]
We should prioritize move to angular 9 once it is released. The ivy rendering engine offers a lot

**Comment by GuessWhoSamFoo** [comment]
Closed via 33ead6107c1969fff5bbd1ac1456bfa7547222eb
