### ISSUE TITLE
Replace YAML viewer with editor component

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#525]

**Comment by wwitzel3** [comment]
replace the existing YAML viewer with the Monaco editor in read-only mode

**Comment by wwitzel3** [comment]
Ran in to a bunch of dep issues yesterday and threw my hands up. Reset my branch from master to day and just started over and it seems to be going much smoother. Hoping to have a PR up for this soon.

**Comment by wwitzel3** [comment]
I'm working through some examples I found at https://github.com/microsoft/monaco-editor-samples

**Comment by wwitzel3** [comment]
Progress. I need to work on the styling of it all and ensure it switches styles on Dark/Light switching.

![image](https://user-images.githubusercontent.com/27317/74971006-5cf2ec00-53ed-11ea-800a-4b43578b2832.png)
