### ISSUE TITLE
Stop informers for the custom resource definitions

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#534]
When a CRD is removed from the cluster, the informer that backs the CRD does not stop the watch

https://github.com/kubernetes/kubernetes/issues/79610

It looks like this in the logs 

```
0114 14:05:14.335682   22896 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

Not sure how long it is going to take for an upstream fix, so we will need to figure out what to do while the upstream process works itself out.

**Comment by geerlingguy** [comment]
@bryanl - Did you ever figure out a solution?

**Comment by wwitzel3** [comment]
We moved to 0.19 beta of client-go which provides an error handler for informers, so now we close the stop channel when that error is encountered.

**Comment by wwitzel3** [comment]
Though I actually don't no if calling the stop channel unregisters event handlers, so this issue might still be happening even with the lastest client-go.

**Comment by geerlingguy** [comment]
@wwitzel3 - Okay thanks! Just wanted to see if there was any other workaround that didn't involve reworking K8s internal code; but in any case, I was able to overcome the issue by rebuilding my cluster (I'm glad this didn't happen in production!).
