### ISSUE TITLE
drain / uncordon for nodes

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#538]
currently we just have delete for nodes, we should have proper action representations for nodes

- [x] cordon/uncordon
- [ ] ~drain~

**Comment by wwitzel3** [comment]
Hey @GuessWhoSamFoo , you want me to pick this up? I'd like to get it in to the 0.12 release.

**Comment by GuessWhoSamFoo** [comment]
sure, feel free to grab it if you'd like

**Comment by wwitzel3** [comment]
Closing this as done and opening a new issue for drain.
