### ISSUE TITLE
Convert Octant to application (Project Denali)

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#550]
Currently, Octant is invoked from the command line. To extend the reach of the project, Octant will be converted to an application.

This Epic will track the process of this conversion

The goal is to develop the web and electron applications at the same time. Denali will be built up until its capabilities equal the existing web application.

**Comment by jmichelgarcia** [comment]
Hi folks, has there been any traction on this topic?

**Comment by wwitzel3** [comment]
Yes, we are working our way through the blocking issues, you can see what we have left here:
 - https://app.zenhub.com/workspaces/octant-5ba2bc534b5806bc2be8fa8d/board?epics=192779991_550&filterLogic=any&repos=192779991

We've got most of the foundational work completed.

**Comment by 06kellyjac** [comment]
Will octant still have the option of being ran with the CLI or will you be mandating the use of electron?
I'm open to octant being an electron app for those who want it. But personally I'd like to reduce the ever increasing amount of electron tools invading my machine when I have a perfectly good terminal and browser.

**Comment by wwitzel3** [comment]
You will still be able to run Octant from master or nightly builds using the CLI but eventually official releases will be Electron only.

**Comment by wwitzel3** [comment]
Tracking this work here now: https://github.com/vmware-tanzu/octant/projects/5
