### ISSUE TITLE
Move pkg/icon into web

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#575]
Front end assets should live with the others and not create potentially confusing code generation logic

**Comment by mklanjsek** [comment]
After almost completing work on this, I am having second thoughts.  Icon files are used only on server side and there is even icon loader there - `icon.go`.  It looks like the icon files are never directly referenced on client side, so maybe they should stay where they are.

@GuessWhoSamFoo thoughts?

**Comment by bryanl** [comment]
@mklanjsek Yes. This is correct and why they were not put in `web` originally.

**Comment by wwitzel3** [comment]
I think we can close this.

**Comment by mklanjsek** [comment]
Closed based on above comments.
