### ISSUE TITLE
Octant doesn't load plugins on Windows

### ISSUE THREAD

**Issue by vitjok27** [vmware-tanzu/octant#580]
Hello
Need help. 
I have %LocalAppData%\octant\plugins folder created on Windows 10 with plugin's binary inside but Octant doesn't load it on the dashboard. Nothing in logs about registering plugin either. Tried almost everything. Any thoughts what I may be missing? Thanks.

**Comment by GuessWhoSamFoo** [comment]
There is a bug in OS-specific path handling that is related to this. #628 should fix this

**Comment by wwitzel3** [comment]
Took a look, this was not fixed by #628. Investigating now.
