### ISSUE TITLE
Implement issue and PR templates

### ISSUE THREAD

**Issue by jonasrosland** [vmware-tanzu/octant#594]
The project could benefit from simple issue and PR templates, see examples:
https://github.com/vmware-tanzu/velero/blob/master/.github/ISSUE_TEMPLATE/feature-enhancement-request.md
https://github.com/vmware-tanzu/sonobuoy/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Do you see any concerns with this?

**Comment by wwitzel3** [comment]
No, it is a good idea, just something that we haven't got around to.
