### ISSUE TITLE
It should be possible to add a logo to the title of a card

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#597]

**Comment by mklanjsek** [comment]
@bryanl I assume by logo you are thinking about arbitrary svg or image resource?

**Comment by bryanl** [comment]
@mklanjsek anything that can be loaded by the icon service initially. In the future, we could experiment with images from base64 data.

**Comment by mklanjsek** [comment]
Discussed this with @rossfenrick and he raised some valid points:

**Comment by mklanjsek** [comment]
@bryanl @rossfenrick are we OK closing this?
