### ISSUE TITLE
FR: Allow plugins to handle forms and create resources

### ISSUE THREAD

**Issue by ImJasonH** [vmware-tanzu/octant#599]
Tekton has an [experimental Octant plugin](https://github.com/tektoncd/experimental/tree/master/octant-plugin) that's able to display information about Tekton resources like Tasks, TaskRuns (executions), etc. It's pretty great!

It would be great if the plugin also presented users with the ability to run Tekton workloads. Tekton's data model would make this easy, since most of the time we expect only a few users to create/manage Tasks and Pipelines which are parameterized, and expect the majority of users to invoke those and pass in the parameters. The form wouldn't have to be very complex, and could be generated from the Task definition and look up available resource instances.

The experimental plugin actually already has support for generating the form, but once it's submitted there's no way to synthesize this into a request to create resources on the cluster. It's unclear from godoc and examples how the form's `action` can be mapped to a handler, and even if it could, [the `Dashboard` client has no `Create` method](https://godoc.org/github.com/vmware-tanzu/octant/pkg/plugin/service#Dashboard).

<img width="489" alt="Screen Shot 2020-01-29 at 1 57 12 PM" src="https://user-images.githubusercontent.com/210737/73387913-47335080-429f-11ea-8116-24dc028535cd.png">

**Comment by wwitzel3** [comment]
related #421

**Comment by wwitzel3** [comment]
This is very much something we want to enable for plugins.

**Comment by wwitzel3** [comment]
@ImJasonH I create https://github.com/wwitzel3/octant-actions-plugin so show how you map action handlers in plugins. We'll do some more work around documentation for this as well.

We'll also be ensuring that plugins have a standard set of CRUD methods.

**Comment by GuessWhoSamFoo** [comment]
Need to add unmarshal for forms before this can move forward

**Comment by GuessWhoSamFoo** [comment]
Closed via #803
