### ISSUE TITLE
Octant permissions should be documented

### ISSUE THREAD

**Issue by jhgoodwin** [vmware-tanzu/octant#606]
Maybe I didn't look hard enough, but in my cluster at work, I can't run octant due to permissions issues.

Would it be possible to provide a list of permissions required to run octant?

Thanks,

John

**Comment by wwitzel3** [comment]
Hi John, Octant is intended to work with your local kubeconfig. We did just recently fix an issue that prevented Octant from starting if you did not have watch permissions to CRDs.

If you will, try downloading the bug fix release we cut just today https://github.com/vmware-tanzu/octant/releases/tag/v0.10.1

If that still isn't working for you please include the error output from the terminal.

**Comment by jhgoodwin** [comment]
I'll try it tomorrow, thanks for your work on this project!

**Comment by wwitzel3** [comment]
@jhgoodwin did you ever get a chance to retry this with the latest Octant?

**Comment by jhgoodwin** [comment]
I tried it just now. You're right! This does seem to allow it to work. I'll see if I can provide more information about non-resolved issues, next time :)
