### ISSUE TITLE
FR: Logs component defaults to all containers

### ISSUE THREAD

**Issue by ImJasonH** [vmware-tanzu/octant#637]
**Describe the problem/challenge you have**
Using the [`Logs` component](https://godoc.org/github.com/vmware-tanzu/octant/pkg/view/component#Logs) (via [`NewLogs`](https://godoc.org/github.com/vmware-tanzu/octant/pkg/view/component#NewLogs)) seems to require me to enumerate all of a pod's containers.

**Describe the solution you'd like**

I'd like to be able to leave that up to Octant, and just request logs for all containers.

Extra-ideally, those logs could be combined/collated into one stream, as if I'd called `kubectl logs <pod> --all-containers`, but just being able to have all containers listed in the dropdown by default would be fine.

`NewLogs` could take container names as an option, or could take a `component.AllContainers` sentinel value, or just always show all logs -- I'm not sure if there's a use case for a `Logs` component that only shows allows logs from some containers.

**Environment:**

- Octant version (use `octant version`): 02/05/2020 nightly
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.4-gke.22", GitCommit:"a6ba43f5a24ac29e631bb627c9b2a719c4e93638", GitTreeState:"clean", BuildDate:"2019-11-26T00:40:25Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.14.6 (18G2022)

**Comment by wwitzel3** [comment]
Yeah, that seems reasonable. Thanks @ImJasonH

**Comment by mklanjsek** [comment]
Changed the `NewLogs` signature to accept only a single argument: `pod` for which logs are collected.  That way caller will get all logs ant they can later be filtered through dropdown in the UI or additional metadata that will be available after #668 is completed.

**Comment by wwitzel3** [comment]
After the initial investigation and the work that Milan did, I think this feature is large enough that it deserves some thought. I will write a proper proposal for this work today and get it up as a PR so folks can have some time to review it and discuss.

**Comment by wwitzel3** [comment]
@GuessWhoSamFoo pointed out https://github.com/wercker/stern which is a tool that does work around joining multiple log streams together.
