### ISSUE TITLE
Update light theme header background color

### ISSUE THREAD

**Issue by rossfenrick** [vmware-tanzu/octant#639]
Currently we use quite a dark background color for the header while using the light theme. We should use one of the new colors in Clarity v3, `#0079AD`. It's easy on the eyes ✨ 

![Screen Shot 2020-02-05 at 3 08 26 PM](https://user-images.githubusercontent.com/7506366/73891575-6561f900-4829-11ea-9d06-cf2fe6b41d50.png)

![Screen Shot 2020-02-05 at 3 21 01 PM](https://user-images.githubusercontent.com/7506366/73892220-2765d480-482b-11ea-9465-d2e397d63486.png)

*Note that the filter & cluster selector text, filter line, namespace selector text,icon,border should now be `#FFFFFF` for better readability/accessibility

**Comment by wwitzel3** [comment]
I merged this but my browser cache hiding a bug. The namespace dropdown in light mode is all white and hard to see. @GuessWhoSamFoo noticed this.


![](https://files.slack.com/files-pri/T09NY5SBT-FTVA86CEQ/image.png)

**Comment by wwitzel3** [comment]
![image](https://user-images.githubusercontent.com/27317/74287085-26cfb100-4cf7-11ea-9604-aa9d1c533ecd.png)

**Comment by wwitzel3** [comment]
@nfarruggiagl please adjust the CSS on the dropdown border in light mode.
