### ISSUE TITLE
Use Vertical Nav component and design style

### ISSUE THREAD

**Issue by rossfenrick** [vmware-tanzu/octant#640]
Currently the main, left navigation is using the [Clarity Sidenav component](https://clarity.design/documentation/sidenav). We should use [Clarity's Vertical Nav component ](https://clarity.design/documentation/vertical-nav/basic-structure/project-pokemon) instead and follow their design style.

![Screen Shot 2020-02-05 at 3 32 39 PM](https://user-images.githubusercontent.com/7506366/73892824-c6d79700-482c-11ea-9445-083b0c3a8326.png)

Issues:
- By putting Workloads, Discovery and Load Balancing, Config and Storage, etc.. under Overview it creates an unnecessary level of navigation.
- Various incorrect or inconsistent margin/padding sizes
- Using the same icon for different navigation items
- Not using the new(ish) Kubernetes specific Clarity icons
- Using the k8s open source icons which clash with Clarity's visual language
- Not an obvious distinction between Namespace level objects and Cluster level objects (no dividers or labels)

![Screen Shot 2020-02-05 at 3 33 36 PM](https://user-images.githubusercontent.com/7506366/73892878-ec64a080-482c-11ea-9ee4-2f0d0f1cbc60.png)
![Screen Shot 2020-02-05 at 4 03 38 PM](https://user-images.githubusercontent.com/7506366/73894375-233cb580-4831-11ea-8081-2b8c7988b7fc.png)

All nav items should be collapsed by default

Icons used* [Nav item | Clarity icon]:
- Applications | application
- Overview | dashboard
- Workloads | applications
- Discovery and Load Balancing | network-globe
- Config and Storage | storage
- Custom Resourecs | file-group
- RBAC | assign-user
- Events | event

- Overview | dashboard
- Namespaces | namespace
- Custom Resources | file-group
- RBAC | assign-user
- Nodes | nodes
- Port Forwards | router
- Plugin | plugin 

All icons are in line format

**Comment by rossfenrick** [comment]
@nfarruggiagl Small update: we should also move the dark/light theme switcher to the bottom of the left nav & also have the nav be collapsible.

**Comment by nfarruggiagl** [comment]
UI code has been pushed to https://github.com/nfarruggiagl/octant/tree/640-use-vertical-nav-component-and-design-style .. It needs some back end work now to re-organize navigation items.

Progress:
![Screen Shot 2020-02-17 at 11 24 42](https://user-images.githubusercontent.com/53268844/74670598-40a24580-5188-11ea-9017-2a04c93bc650.png)

**Comment by rossfenrick** [comment]
cc @wwitzel3 @GuessWhoSamFoo  ^^

**Comment by GuessWhoSamFoo** [comment]
Going to work on this now to unblock. I think #677 will be resolved naturally as well.

**Comment by wwitzel3** [comment]
We going to continue this work and track it on #340
