### ISSUE TITLE
Unmarshal components for plugins

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#646]
These are components that are missing from `pkg/view/unmarshal.go`. 

 - [x] button/button group #647 
 - [x] code
 - [x] donut chart
 - [x] ~extension - can a plugin add a tab to the extension?~
 - [x] error
 - [x] ~form~ - n/a in this case
 - [x] ~port? - requires a port forward state~
 - [x] single stat
 - [x] ~terminal~
 - [x] ~vertical bullet~ removed
 - [x] ~yaml~ - considered deprecated as it will be an editor soon

Some of these components such as terminal or port requires knowledge of octant's internal state which might not be good developer experience in the context of plugins.

**Comment by wwitzel3** [comment]
Port and Terminal we won't be doing as part of this pass.

**Comment by wwitzel3** [comment]
This is really a tracking issue, please add new issues and link to them in the list as we address each component.

**Comment by GuessWhoSamFoo** [comment]
Is vertical bullet chart supported anymore? I can't find the frontend for it anymore. iirc, the donut chart is used instead for workloads
