### ISSUE TITLE
Expose the octant command line options so that if you want to launch octant from another go program you can interface / extend with the existing octant options

### ISSUE THREAD

**Issue by aschiefe** [vmware-tanzu/octant#652]
**Describe the problem/challenge you have**
The product we are developing on is launching octant as a sub process programmatically.  It would be nice to be able to reference the command line arguments that are inside octant without needing to replicate the structure within our code.

**Describe the solution you'd like**
Be able to reference a struct or class that contains all available command line options and related accoutrement from an external program.

**Anything else you would like to add:**
I believe this would would live somewhere in the internal/commands module

**Environment:**

- Octant version:  Version:  (dev-version)
                                            Git commit:  cd7390dc
                                            Built:  2020-02-06T20:43:05Z 
- Kubernetes version:          1.17.0
- OS:                                     Windows 10 / Ubuntu 18.04

**Comment by aschiefe** [comment]
I may have found what I was looking for in pkg/dash/dash.go so this may or may not be needed after all

**Comment by wwitzel3** [comment]
I'm going to close this out as fixed, feel free to re-open if the command struct from dash.go ends up not being what you needed.
