### ISSUE TITLE
Move delete button to page header

### ISSUE THREAD

**Issue by rossfenrick** [vmware-tanzu/octant#658]
Currently in Octant when you go to an "individual view" (Daemon Set, Deployment, etc..) there is a delete button underneath the header/tabs area. This should be moved up into the view header/tabs area, vertically aligned with the view title

As-is:
![Screen Shot 2020-02-11 at 11 31 54 AM](https://user-images.githubusercontent.com/7506366/74271868-7b0c6e00-4cc2-11ea-9cd6-7b97d193d07e.png)

To-be:
![Screen Shot 2020-02-11 at 11 31 21 AM](https://user-images.githubusercontent.com/7506366/74271887-8364a900-4cc2-11ea-9b57-e713b2792fb4.png)

This gives better visual alignment to the object you are deleting & gets rid of some extraneous whitespace in the view beneath the tabs.

**Comment by wwitzel3** [comment]
The current placement has to do with where buttonGroups are inserted in to the FlexLayout. This may require both API and UI changes, but I don't know off the top of my head.
