### ISSUE TITLE
It should be possible to pause the logger

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#669]
The logger can stream by too fast. It should be possible to pause the logger. When the logger is paused, it should indicate how many messages have not been seen.

**Comment by mklanjsek** [comment]
@bryanl you can 'pause' logger scrolling if you scroll away from the bottom of the log view. In that case, log view is not scrolled to the bottom as new log messages arrive and in the same time scrollbar gives indication that new log messages have been added. Isn't this sufficient enough?

**Comment by bryanl** [comment]
Yes. This should be sufficient.

**Comment by mklanjsek** [comment]
Makes sense, closing.
