### ISSUE TITLE
Current namespace should always be visible

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#690]
Since the namespace selector moved to the navigation section, the current namespace is not always visible. The current namespace should always be visible.

**Comment by GuessWhoSamFoo** [comment]
For 0.11, we decided during the community meeting that it is fine to leave the namespace selector in navigation even if it can scroll out of view and solve this along with navigation update.

**Comment by wwitzel3** [comment]
Fixed by #812
