### ISSUE TITLE
Multiple plugin tabs overwrite

### ISSUE THREAD

**Issue by johnharris85** [vmware-tanzu/octant#691]
**What steps did you take and what happened:**
When running _n_ plugins with tabs, only one plugin is printed (title and content), however it's printed _n_ times.

Reproduction is to take the sample plugin, change the plugin name, tab name and tab content (in my case appended "2") and add both the original and the new one to the plugins directory.

![Screenshot from 2020-02-16 11-11-36](https://user-images.githubusercontent.com/746221/74611071-88a06a00-50ad-11ea-8c65-12c028cc86ea.png)

Octant displays the "2" plugin twice instead of the original and the "2".

**What did you expect to happen:**
Both different plugins tabs to appear.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 0.10.2
- Kubernetes version (use `kubectl version`): N / A
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 16.04

**Comment by GuessWhoSamFoo** [comment]
This is similar to https://github.com/vmware-tanzu/octant/issues/46

Are the registered plugin names different?

**Comment by johnharris85** [comment]
Yup, different names, different descriptions, different tab titles and different content. I cloned the sample plugin and changed those 4 things.

**Comment by wwitzel3** [comment]
Confirmed this behavior using the sample plugin. We will look in to it.

![image](https://user-images.githubusercontent.com/27317/74765965-79a6ec80-5252-11ea-834e-f9b2e1f15b7d.png)
