### ISSUE TITLE
Enhancements for Log Filtering

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#701]
- [ ] Show total matches
- [ ] Allow forward and back buttons to wrap back to top or down to bottom
- [x] Case sensitive searching (see: https://github.com/vmware-tanzu/octant/issues/702)
- [x] ~Allow glob search/regex support~

**Comment by mklanjsek** [comment]
Regex should already work.  I'll work on other issues together with implementation of design that @rossfenrick is working right now.
