### ISSUE TITLE
Timestamp hover hidden under table bounds

### ISSUE THREAD

**Issue by dotNomad** [vmware-tanzu/octant#727]
**What steps did you take and what happened:**
A small table with a timestamp (Age) column is sufficient to see this problem. The problem is most apparent when Age is the right most column. It can also be seen on the last item on a table.

![Timestamp Small Table Issue](https://user-images.githubusercontent.com/19917631/75183315-22dc5f80-56f7-11ea-81f9-1d85ab561482.png)

For example, if you have a single Pod in a namespace and try to hover over the age it isn't visible, instead it expands the table with a scrollbar. This makes the timestamp not really visible. On the last item of a table a similar thing happens, but most of the hover effect is visible.

**What did you expect to happen:**
I expect to be able to read the timestamp hover.

**Environment:**

- Octant version (use `octant version`):
Version:  (dev-version)
Git commit:  86e95729
Built:  2020-02-24T18:44:39Z
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 18.04
- Browser: Firefox 73.0

**Comment by GuessWhoSamFoo** [comment]
xref: https://github.com/vmware/clarity/issues/1559

**Comment by GuessWhoSamFoo** [comment]
Fixed via #759 by switching over to signposts
