### ISSUE TITLE
Octant goes into backoff mode and overview update is delayed.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/octant#736]
**What steps did you take and what happened:**

I am running Octant with a service account which has restricted RBAC. It is able to list resources (as admin role in the namespace) for a single namespace, but has no access to namespaced resources of any other namespaces. The service account does have sufficient RBAC to list and get namespaces (so that list of namespaces in Octant is at least populated).

When Octant starts up the overview page for the namespace the service account does have access to, displays blank for some time. It can take minutes to update in some cases. Doesn't make a difference if using ``--namespace`` on startup, or the namespace is set in the context of kubeconfig setup.

**What did you expect to happen:**

I expect the list of resources in the namespace to be displayed promptly, not after an indeterminate delay.

**Anything else you would like to add:**

The problem is possibly due to the API backoff. I suspect what is happening is that Octant is trying to query namespaced resources from every namespace (one namespace at a time) and not just the current one. Because it can't query namespaced resources in other namespaces, it fails and backoff mode kicks in. For example:

```
│ 2020-02-27T23:25:11.684Z    ERROR    describer/describer.go:97    load object    {"err": "list: Cache │
│ Key[APIVersion='batch/v1beta1', Kind='CronJob']"}                                                     │
│ github.com/vmware-tanzu/octant/internal/describer.LoadObjects                                         │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/describer.go:97                         │
│ github.com/vmware-tanzu/octant/internal/describer.(*ObjectLoaderFactory).LoadObjects                  │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/describer.go:45                         │
│ github.com/vmware-tanzu/octant/internal/describer.(*List).Describe                                    │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/list.go:74                              │
│ github.com/vmware-tanzu/octant/internal/describer.(*Resource).Describe                                │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/resource.go:52                          │
│ github.com/vmware-tanzu/octant/internal/describer.(*Section).Component                                │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/section.go:53                           │
│ github.com/vmware-tanzu/octant/internal/describer.(*Section).Describe                                 │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/section.go:36                           │
│ github.com/vmware-tanzu/octant/internal/describer.(*Section).Component                                │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/section.go:53                           │
│ github.com/vmware-tanzu/octant/internal/describer.(*Section).Describe                                 │
│     /go/src/github.com/vmware-tanzu/octant/internal/describer/section.go:36                           │
│ github.com/vmware-tanzu/octant/internal/generator.(*Generator).Generate                               │
│     /go/src/github.com/vmware-tanzu/octant/internal/generator/generator.go:108                        │
│ github.com/vmware-tanzu/octant/internal/modules/overview.(*Overview).Content                          │
│     /go/src/github.com/vmware-tanzu/octant/internal/modules/overview/overview.go:258                  │
│ github.com/vmware-tanzu/octant/internal/api.(*ContentManager).generateContent                         │
│     /go/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:139                        │
│ github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1                         │
│     /go/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:99                         │
│ github.com/vmware-tanzu/octant/internal/api.(*job).run.func1                                          │
│     /go/src/github.com/vmware-tanzu/octant/internal/api/poller.go:111                                 │
│ 2020-02-27T23:25:11.686Z    INFO    objectstore/dynamic_cache.go:203    backing off for batch/v1beta1 │
│ , Kind=CronJob (1.065676647s)
```

Eventually as it keeps trying after backoff period delay, if finally gets to the current namespace one actually cares about and the overview is able to be populated. How quickly it gets to the current namespace thus depends on the order in which namespaces are returned when listing or getting the namespaces initially.

If for some reason one can't just avoid querying all namespaces up front on startup, can Octant at least query the namespace in the current context, or as supplied on command line first. That way the overview page will populate quickly. It can then go onto other namespaces and for those doesn't matter if not delayed, although could still if need to work with multiple namespaces which you do have access to.

Octant perhaps thus needs to be more tolerant or able to detect when access to namespaced resources in a namespace is not allowed, and so handle it better. Maybe it can do a quick scan looking for a single resource type in all namespaces, rather than all resource types, and if that succeeds, do all for the namespace. If the initial resource couldn't be queried, then go back and try all resources in that namespace later. Question would be witch resource type to query first as an indicator that one can query stuff in the namespace okay. Maybe do a get on serviceaccount since even view role can do that.

**Environment:**

- Octant version (use `octant version`): 

```
$ octant version
Version:  0.10.2
Git commit:  438ce3d52088c1e3e15aaf9817ba71e3c85255f5
Built:  2020-02-14T23:12:26Z
```

- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634
cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce6182
13", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

```
$ uname -a
Linux workshop-s001-6d9f899c5f-wsbtz 4.19.94 #1 SMP Thu Feb 20 00:37:50 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wwitzel3** [comment]
I'm able to reproduce this behavior. We will need to take a look at some options. I'm not exactly sure how we will handle this.

We maybe able to scope backoffs to namespaces. We also can look in to having a backlog per type.

**Comment by jijojv** [comment]
+1 i'm also in a very restricted k8s environment as a user.  It takes a few mins to load the page with  any data.

**Comment by wwitzel3** [comment]
An idea of working on to solve this goes something like this:

Instead of backing off and retrying resources, or trying to crawl every single permission a user might have, Octant would attempt to access a resource one time. If the response is Unauthorized, mark that resource unavailable. The message presented in the UI should be explicit that the resource is Unavailable due to being unauthoried e.g. "Unable to list Pods, unauthorized"

If the response was successful, also mark it as such. So that is we later get an unauthorized response we can be smart about informing the user their access has changed (think expiring rotating client certs).

The unavailable marker will be cleared when ever context is updated. A context can be updated manually when the user switches contexts. Provide a manual mechanism for reloading the current context and clear the markers.

**Comment by wwitzel3** [comment]
Octant no longer has backoff code and should no longer delay the update view.
