### ISSUE TITLE
Duplicate entries in list of current port forwarding sessions.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/octant#739]
**What steps did you take and what happened:**

Go to a pod, and start a port forwarding session.

Then go to the `Port Frowards` page by selecting down bottom left on the menu. Details on the port forwarding session are duplicated.

![image](https://user-images.githubusercontent.com/507637/75500487-318d8400-5a21-11ea-8b92-191001ebcab8.png)

**What did you expect to happen:**

No duplicate.

**Anything else you would like to add:**

Nope.

**Environment:**

- Octant version (use `octant version`): 

```
$ octant version
Version:  0.10.2
Git commit:  438ce3d52088c1e3e15aaf9817ba71e3c85255f5
Built:  2020-02-15T02:33:23Z
```

- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

```
$ uname -a
Darwin grumpy-at-home.fritz.box 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

Also affects separate web browser when accessing Octant as web service.

**Comment by GuessWhoSamFoo** [comment]
Fixed via 8cc63095b08c82a299b751cfd07a26189b969241
