### ISSUE TITLE
Resource viewer not working for deployment as resources missing.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/octant#741]
**What steps did you take and what happened:**

Created a deployment of a frontend web application using resources in:

* https://github.com/eduk8s-tests/lab-octant-testing/tree/master/frontend

When viewing the visualization for the workload by using the **Workloads** menu entry on left side, you get a full view of set of related resources.

![image](https://user-images.githubusercontent.com/507637/75515323-e9d12180-5a4d-11ea-97c8-45e48e3d8fd5.png)

If you drill down to the deployment details from the overview page or deployments category of left hand side menu, and select the **Resource Viewer** tab, it is only showing the deployment, and not the related resources.

![image](https://user-images.githubusercontent.com/507637/75515413-1c7b1a00-5a4e-11ea-8201-cd41eff03129.png)

**What did you expect to happen:**

Would have assumed all the same resources could have been displayed.

**Anything else you would like to add:**

Nope.

**Environment:**

- Octant version (use `octant version`): 

```
$ octant version
Version:  0.10.2
Git commit:  438ce3d52088c1e3e15aaf9817ba71e3c85255f5
Built:  2020-02-15T02:33:23Z
```

- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

```
$ uname -a
Darwin grumpy-at-home.fritz.box 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

Also affects separate web browser when accessing Octant as web service.

**Comment by GuessWhoSamFoo** [comment]
Fixed in #698
