### ISSUE TITLE
 Proper onboarding for new users

### ISSUE THREAD

**Issue by francisdb** [vmware-tanzu/octant#750]
**What steps did you take and what happened:**

> brew install octant
> octant

🤮

> 2020-03-04T09:10:46.824+0100	ERROR	commands/dash.go:109	dashboard failed	{"err": "failed to init cluster client: invalid configuration: no configuration has been provided"}
github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1.2
	/private/tmp/octant-20200215-54834-lxnkt8/src/github.com/vmware-tanzu/octant/internal/commands/dash.go:109

**What users expect**

To see the octant user interface or a proper help message indicating what they should do

**What most users do**

> brew remove octant

**Comment by GuessWhoSamFoo** [comment]
Sorry you had a bad initial experience. Octant currently requires a valid kubeconfig to start, and the UI isn't clear about that. #362 should clear up confusion in a future release.

**Comment by wwitzel3** [comment]
I the short term we can add a better message to the console output instructing users that a `KUBECONFIG` env var must be set or `--kubeconfig` must be provided.

**Comment by wwitzel3** [comment]
I spoke to @jonasrosland about setting up a step by step getting started guide for https://octant.dev - we will use this issue to track that work.
