### ISSUE TITLE
Remove replace statement in go.mod

### ISSUE THREAD

**Issue by antoninbas** [vmware-tanzu/octant#766]
**Describe the problem/challenge you have**
If a project implements an Octant plugin and imports both Octant and the K8s client-go, it is very easy to run into this "ambiguous import" issue: https://github.com/Azure/go-autorest/issues/414.

**Describe the solution you'd like**
I am not sure why a `replace` directive was added to the go.mod in the first place, as this commit (https://github.com/vmware-tanzu/octant/commit/849fd9573f8a967fdcee92a56bd135eabd7089fb) does not give an explanation, but maybe it is not required any more? I tries removing it from go.mod and running `go mod tidy` and it was able to pick up a more recent version of client-go which resolves the issue (thanks to this commit https://github.com/kubernetes/client-go/commit/cca417f1ca13e54821c825de76c4e1de28f028dd).

**Anything else you would like to add:**
I'm happy to open the corresponding PR if people are fine with this change.

**Comment by GuessWhoSamFoo** [comment]
related #432

**Comment by wwitzel3** [comment]
@bryanl is there any reason we can not remove the replace directive here?

**Comment by GuessWhoSamFoo** [comment]
Closed via #931
