### ISSUE TITLE
Watch KUBECONFIG for changes

### ISSUE THREAD

**Issue by marmelin** [vmware-tanzu/octant#768]
**Describe the problem/challenge you have**
We have a multi-tenant and multi-cluster environment in which we use different kubeconfig files to dynamically change between clusters. You can think of different regions (CHINA, AMERICA, EUROPE, etc.). I successfully installed Octant on a jump server (!) and connecting to it via browser with SSH-Tunnel (which is the most common way - as I know - in big companies, where the different Divisions do not have direct access to each others data centers.
So whenever I change the KUBECONFIG env variable to a new config file, otctant stays the same as before. As KUBECONFIG is unique for each bash-session. The SSH-Tunnel-session (a separate session) would not reflect the changes of KUBECONFIG  in my current session.

**Describe the solution you'd like**
Maybe Octant could have its own settings file, which I could change. So I could set a new config file and Octant can update. Maybe for several user/login-profiles. 

**Anything else you would like to add:**
I working on a solution with gdb debbuging tool. Attach to process of octant and change variable, but this is not the way it should be done , right :) 

**Environment:**

- Octant version (`
Version:  0.10.2 
Git commit:  438ce3d52088c1e3e15aaf9817ba71e3c85255f5
Built:  2020-02-14T23:12:26Z
): 
- Kubernetes version (
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-dhc", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"dirty", BuildDate:"2020-01-22T06:25:41Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
):
- OS (
SUSE Linux Enterprise Server 12 SP4  (x86_64) - 
Linux 4.12.14-95.32-default #1 SMP Wed Sep 18 05:00:42 UTC 2019 (5fbcb00) x86_64 x86_64 x86_64 GNU/Linux
):

**Comment by marmelin** [comment]
# [SOLVED] using multi-definition kubeconfig

We are using a multi-context kubeconfig and starting octant with that: 
`OCTANT_LISTENER_ADDR=0.0.0.0:7777 ~/tools/octant_0.10.2_Linux-64bit/octant --kubeconfig /home/lochmar/.kube/multi_tenants.kubeconfig  &`

**Comment by wwitzel3** [comment]
We avoid having Octant reload the kubeconfig when the environment variable changes because we don't want to reload because some other tool has changed the kubeconfig. We do how ever watch the file itself for changes.

So as you've discovered you can point Octant to a multi-context kubeconfig and you can append / remove entries from it and Octant should reload when that file changes, without the need to restart Octant.
