### ISSUE TITLE
Cannot see network policies

### ISSUE THREAD

**Issue by marmelin** [vmware-tanzu/octant#769]
I would like to see the network policies of kubernetes namespace. I cannot find it in current version of octant. Is there a reason, why ?

#### VERSIONS: 
```
Linux sfseal000204 4.12.14-95.32-default #1 SMP Wed Sep 18 05:00:42 UTC 2019 (5fbcb00) x86_64 x86_64 x86_64 GNU/Linux
```
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-dhc", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"dirty", BuildDate:"2020-01-22T06:25:41Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
Version:  0.10.2 
Git commit:  438ce3d52088c1e3e15aaf9817ba71e3c85255f5
Built:  2020-02-14T23:12:26Z
```

**Comment by GuessWhoSamFoo** [comment]
This isn't in the list of supported GVKs yet. Adding a printer should not be too difficult. There is also #430 for visualizations

**Comment by marmelin** [comment]
I see the problem with the connections to resolve, but simply looking at the yamls or the values as a tree would be great in the first place. And as you said ... this is not a hard task to do. Is there a chance that you implement this in near future?

PS: You mean a plugin ? I don´t know how to do this and not even have the time to do it.
