### ISSUE TITLE
Resource Viewer should navigate to views associated with clicked items

### ISSUE THREAD

**Issue by mklanjsek** [vmware-tanzu/octant#773]
Based on feedback from Slack:
`Hi Team, How hard would it be to get the items in the resource view diagrams clickable. You know if you are in a deployment and click a pod how about if that take you to the Pod Page?`

**Comment by wwitzel3** [comment]
So the items are clickable, but maybe that just isn't clear enough. I think this leads to a bigger issue of making the resource viewer more useful as both the source of truth for a workload and its structure and status as well as navigating the details of that workload.

**Comment by mklanjsek** [comment]
There should be an action that will take you from each object directly to its page - so for example if click opens properties view on the right, maybe double click should take you directly to that object page.  We also need tooltips with condensed summary about each object.

This will also give us ability to provide visual navigation.

**Comment by wwitzel3** [comment]
You can now double click on resources in the Resource Viewer to go to their view.
