### ISSUE TITLE
Timestamps can appear outside of viewport

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#779]
**What steps did you take and what happened:**
A timestamp on the right most columns in list views will be cut off. We could add logic to see if the signpost should appear on the left side or move the age columns from the backend.

**What did you expect to happen:**
Seeing the full time stamp

**Environment:**

- Octant version (use `octant version`): 944def0b00c20ab35e95e335c1f3fa5fcc58484b
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by mklanjsek** [comment]
@GuessWhoSamFoo screenshot please

**Comment by GuessWhoSamFoo** [comment]
![Screenshot_20200319_175750](https://user-images.githubusercontent.com/10288252/77127890-629f1a00-6a0b-11ea-8998-c18ae7980912.png)

**Comment by mklanjsek** [comment]
Addressed by #784
