### ISSUE TITLE
Improve component reference documentation

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#790]
Component reference documentation should contain:

1. Brief description of what the component does
1. An example of what the UI looks like
1. A JSON representation of the component object
1. Code sample for generating the component on the backend

**Comment by wwitzel3** [comment]
WIP branch here: https://github.com/vmware-tanzu/octant/tree/component-docs

**Comment by wwitzel3** [comment]
replaced by #971
