### ISSUE TITLE
Save user preferences in browser local storage

### ISSUE THREAD

**Issue by mklanjsek** [vmware-tanzu/octant#824]
For better usability Octant should store some of the user specific configuration info inside the browser local storage. This information should contain, but it's not limited to: 

- color theme (light/dark),
- vertical navigation state (collapsed/expanded),

Something like [this module](https://github.com/grevory/angular-local-storage) should be a good help in implementation

**Comment by wwitzel3** [comment]
#657 and #472 are existing issues that overlap with this.

**Comment by wwitzel3** [comment]
Will angular local storage work well in Electron?

**Comment by mklanjsek** [comment]
@wwitzel3 I don't see a reason why it should not work with Electron, but we need to test it.

**Comment by mklanjsek** [comment]
Duplicate with #657 and #472
