### ISSUE TITLE
terminal to pod results in error

### ISSUE THREAD

**Issue by abelal83** [vmware-tanzu/octant#827]
upgraded octant from 0.11.0 to 0.11.1
ran octant.exe
in browser attempted to terminal to pod using terminal tab but got nothing, checked console window which is constantly throwing this error

```
2020-04-08T17:25:59.730+0100    ERROR   terminal/manager.go:158 streaming: pods "actions-function-58b864686d-5lm4p" not found   {"Terminal Viewer": "context.Background.WithCancel.WithValue(type log.key, val <not Stringer>).WithCancel.WithValue(type log.key, val <not Stringer>).WithCancel.WithValue(type log.key, val <not Stringer>).WithCancel.WithValue(type log.key, val <not Stringer>).WithValue(type trace.contextKey, val span 3f79ad5d8829f846)"}
github.com/vmware-tanzu/octant/internal/terminal.(*manager).Create.func1
        /__w/octant/octant/internal/terminal/manager.go:158
```

**What did you expect to happen:**
To be able to terminal to pod without error

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 0.11.1
- Kubernetes version (use `kubectl version`): 1.15.7
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10

**Comment by wwitzel3** [comment]
Is the image you are using a public one? Asking because I'll be sure to test directly with it.

**Comment by abelal83** [comment]
@wwitzel3 I'm using the image provided by chocolatey.org (https://chocolatey.org/packages/octant)

**Comment by abelal83** [comment]
I just tried terminal again and it appears to be working. Other than a reboot I'm pretty sure nothing else has changed. Can close this issue unless @wwitzel3 would still like to investigate in which can I'm happy to assist in whatever way I can?

**Comment by wwitzel3** [comment]
Ok, thank you for the update we will close it, but please reopen if you
find this to be a common issue.
