### ISSUE TITLE
Navigation cleanup

### ISSUE THREAD

**Issue by mklanjsek** [vmware-tanzu/octant#835]
There are still a few small things in new navigation that should be fixed and/or improved:
 
- [x] Initial update does not always accurately refresh namespace dropdown, 
- [x] flyout sometimes stays opened after moving away,
- [x] add more unit tests,
- [x] when collapsed, indication about currently selected item is sometimes not accurate,
- [ ] flyout should be separate component,

**Comment by wwitzel3** [comment]
Do we want to make an issue out of the last item? or is it not worth the time investment right now?

**Comment by wwitzel3** [comment]
last item being, flyout should be a separate component

**Comment by mklanjsek** [comment]
I mentioned the flyout refactor in PR - it just didn't work out as well as I hoped, so I don't think it's worth more effort.
