### ISSUE TITLE
Using --namespace displays namespace does not exist

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#838]
**What steps did you take and what happened:**
When starting Octant and providing the namespace at runtime, with no access to list namespaces, Octant displays information but shows a warning that the namespace does not exist.

<img width="1179" alt="Screen Shot 2020-04-10 at 3 23 52 PM" src="https://user-images.githubusercontent.com/27317/79028879-e1492c00-7b5f-11ea-8a0e-3d8645fb9714.png">

**Comment by jaimegag** [comment]
I'm experiencing the same issue, when user only has access to a single namespace different than the `default` namespace, and no access to list namespaces.

**Comment by wwitzel3** [comment]
@GuessWhoSamFoo pointed out that you may be able to work around this issues by also setting the `--namespace-list` flag. In this caes, you would provide it with the single namespace the user has access to.

**Comment by jaimegag** [comment]
Using `--namespace-list` solved the problem for me testing with the Mac client on a chrome browser.

FYI I was using `--namespace` all the time before. Without it, no information was displayed at all in any section

**Comment by wwitzel3** [comment]
If we fail to list namespaces, but namespace is provided, lets set namespace-list to namespace.
