### ISSUE TITLE
highlighting and line numbers in log messages

### ISSUE THREAD

**Issue by michmike** [vmware-tanzu/octant#845]
today, logging in Octant has seen significant improvements and changes. this is great!

key features include:
* filtering by text/regex, including the ability to only show filtered lines
* filtering by container or all containers
* enable/disable timestamp

i would like to ask for a new set of features in logging that will aid in troubleshooting. 
1. sometimes it is useful to not only see the timestamps and text, but also see line numbers. Line numbers are easier to remember as you go back and forth in troubleshooting
2. sometimes it is incredibly useful to be able to highlight certain terms as you troubleshoot. Imagine having a text box where a user can enter one or more words which will be highlighted in the logs. The collection of words are logical-OR'ed and highlighted as independent words. Up to us if we want to pick a new color her word or use the same highlighting color for all the words.

**Comment by bryanl** [comment]
1 might not be possible. The log buffer has a fixed size, so there is no way to know what line a log is in on.

**Comment by michmike** [comment]
thanks @bryanl , the line number would be relative to what is being displayed in the octant log view. with that in mind, is this not possible?

**Comment by wwitzel3** [comment]
> sometimes it is incredibly useful to be able to highlight certain terms as you troubleshoot. Imagine having a text box where a user can enter one or more words which will be highlighted in the logs. The collection of words are logical-OR'ed and highlighted as independent words. Up to us if we want to pick a new color her word or use the same highlighting color for all the words.

This can be done now using regular expressions. For example if you were looking for 500 errors for a specific endpoint: `(?=500)(?=.*/api/v1/orders)`. We can create an issue to document some more common regex for log filtering on octant.dev

**Comment by wwitzel3** [comment]
related #879

**Comment by bryanl** [comment]
Thinking about this. #1 is not possible and not a feature that any of the popular logging tools have. Highlighting is still valid.

**Comment by wwitzel3** [comment]
#879 and #1355 address all of these.
