### ISSUE TITLE
Terminal messages on stream even if there is no subscriber

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#848]
**What steps did you take and what happened:**
View the Terminal tab of a Pod.

1. Open the Terminal tab of a Pod.
2. exit the terminal sessions
3. Switch to another tab of the Pod, for example, Summary.

**What did you expect to happen:**
No console warning about Terminal stream data.

![image](https://user-images.githubusercontent.com/27317/79592211-ab4c0080-80a7-11ea-8d81-b128b0fffd41.png)

**Comment by wwitzel3** [comment]
will probably end up being fixed by #842

**Comment by GuessWhoSamFoo** [comment]
Closed via f49e3cc42ba5f20ee6aa3893d17b6d441b483a6b
