### ISSUE TITLE
Improve performance, allow manually fetch only

### ISSUE THREAD

**Issue by tmpm697** [vmware-tanzu/octant#853]
**Describe the problem/challenge you have**
This app consumes too much resources especially cpu and ram.

**Describe the solution you'd like**
cpu average of 230%, consuming ram.

**Anything else you would like to add:**
Do not continually fetch metrics kubernete's api, let allow users to use it manually, e.g: I only need get new logs of this container so I click on "refresh" button to get it.

**Environment:**

- Octant version (use `octant version`): 
```
Version:  (dev-version)
Git commit:  e4331f6
Built:  2020-04-21T15:36:15Z
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"archive", BuildDate:"2020-04-19T14:21:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Archlinux up-to-date

**Comment by wwitzel3** [comment]
Sorry you are running in to performance issues. This is not normal for Octant to consume large amounts of CPU and memory.

Are you able to provide a little more detail about your usage of Octant? Things that would be very helpful in identifying what might be causing this problem for you:

- Number of contexts
- Size of the cluster (number of total resources, number of namespaces)
- Do you see the high CPU/Mem usage right at startup?
  - Do you see if only when viewing the logs (as you mentioned).
  - Is there a pattern that of navigating within the application that always produces the high CPU/Mem usage?

**Comment by wwitzel3** [comment]
Also are you running any plugins?

**Comment by wwitzel3** [comment]
@tmpm697 are you able to provide any more details on your running environment for Octant?

**Comment by tmpm697** [comment]
I'm running with archlinux up-to-date, hardware the same power as macbook pro 2015 with 2 cores cpus. This seems a unclear question I'll check more and give feedback.

**Comment by wwitzel3** [comment]
Hi @tmpm697, here are the questions I had previously:

- Number of contexts
- Size of the cluster (number of total resources, number of namespaces)
- Do you see the high CPU/Mem usage right at startup?
- Do you see if only when viewing the logs (as you mentioned).
- Is there a pattern that of navigating within the application that always produces the high CPU/Mem usage?

**Comment by wwitzel3** [comment]
Just wanted to check and see if you were still having performance issues with Octant and if so, could you provide any of the added details I asked about previously?

**Comment by tmpm697** [comment]
Thanks @wwitzel3 , I'll check and gives feedback later as I'm not currently on local kubernetes.

**Comment by wwitzel3** [comment]
Please try the latest version of Octant https://github.com/vmware-tanzu/octant/releases/latest

We've added a number of performance improvements including how we stream logs and Octant now sends content to the stream when something has changed.

If the problem still persists please feel free to re-open or create a new issue.
