### ISSUE TITLE
Custom resource bread crumbs do not render correctly

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#855]
**What steps did you take and what happened:**

bread crumbs in custom resource definitions do not render correctly

![Screen Recording 2020-04-21 at 1 54 46 PM mov](https://user-images.githubusercontent.com/240/79897861-4c082c00-83d8-11ea-9cdd-0b56192b6e2c.gif)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): master as of 1400 ET on April 21, 2020

**Comment by wwitzel3** [comment]
@mklanjsek please take a look
