### ISSUE TITLE
Enable line highlighting even when using assertions.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#856]
When filtering logs with regular expressions the counts are correct and the only show matching lines toggle works correctly, but line highlighting is broken.

![log-filtering-regex.gif](https://images.zenhubusercontent.com/5b4e34e5c417015bdfbef7b1/b0957ebb-6378-4e16-81bb-b89e4eac17a2)

**Comment by mklanjsek** [comment]
@wwitzel3 problem here is that the regex you are using is positive lookahead regex that can be used only for assertions and not pattern matching. You can see the same behavior [here](https://regexr.com/5319f) and compare that after replacing the regex expression with just `posts` string.

So, I don't think we can do much here. Basically result of that regex search is two assertions that do not select any text and that is exactly what we are indicating in the UI.

**Comment by wwitzel3** [comment]
Can we default to entire line? highlighting the line with the match when we are unable to find a specific match highlight?

Maybe we can add a gutter to the log viewer so it can show which line you are on?

Trying to think of ways to make this a bit more usable given the technical constraint you mentioned.

**Comment by mklanjsek** [comment]
I like the idea of highlighting the whole line, let's try that!

**Comment by mklanjsek** [comment]
At the end, I was able to find the start of the match, however here is a catch from the PR:

> Note on lookahead regex support: since lookahead regex expressions only assert the existence and start of the matched block, there is a difficulty in determining the end of the selection, so it will highlight text to the end of the current section.

I think that is totally acceptable, just a not how it behaves.
