### ISSUE TITLE
Breadcrumb links not working as expected.

### ISSUE THREAD

**Issue by wwitzel3** [vmware-tanzu/octant#866]
**What did you expect to happen:**
Above the header on the pages of Octant the breadcrumbs should be clickable when there is more than one.

![image](https://user-images.githubusercontent.com/27317/80026064-842e6e00-84af-11ea-9a30-1113cdcef318.png)

- Octant version (use `octant version`): 
```
Version:  0.12.0
Git commit:  f232c1880427da2f573950895d1a80db177beb03
Built:  2020-04-22T17:05:50Z
```

**Comment by mklanjsek** [comment]
Fixed by #869. There was a merge conflict [here](https://github.com/vmware-tanzu/octant/commit/47a89c6b2747b597e2770f9cdaa53e0885ed5724)
