### ISSUE TITLE
request.DashboardClient().List() ignores Selector

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#876]
I took a stab at migrating the helm plugin to the latest octant + helm releases and kept getting grpc errors listing Secrets...
```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (13036146 vs. 4194304)
```

So I tried tweaking the code to use stricter label selectors to reduce the amount of data returned by `request.DashboardClient().List()` and found the `Selector` is completely ignored; so there's no way to filter via selector.

```go
	client := request.DashboardClient()
	dl, err := client.List(ctx, store.Key{
		APIVersion: "apps/v1",
		Kind:       "Deployment",
		Selector: &labels.Set{
			"app": "something",
		},
	})
```

it doesn't seem to matter what selector is specified; the same data is returned.

Anyone got any ideas of how to use selectors to filter the results; or to avoid grpc message limits from a plugin?

BTW the above is using deployments as every call to list Secrets in my cluster fails so I was using Deployments to test out whether selectors worked from inside a plugin)

**Comment by GuessWhoSamFoo** [comment]
Just realized the `convertFromKey` helper in `conversion.go` doesn't pass the selector. There should be a fix for this shortly
