### ISSUE TITLE
how to find the current namespace from a plugin?

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#886]
**Describe the problem/challenge you have**
The built in views automatically refresh as you switch namespaces (via the top right drop down). E.g. view the Workspaces -> Deployments; switch the namespace and you see a different list of deployments.

I'd like to replicate that behaviour inside a plugin view; by passing in the current namespace context to any query made in the plugin:

```go
	ctx := request.Context()
	client := request.DashboardClient()
        ns := TODO

	dl, err := client.List(ctx, store.Key{
		APIVersion: "apps/v1",
		Kind:       "Deployment",
		Namespace:  ns,
	})
```

At first I assumed there was no need to pass in a namespace as the `client.List()` would do that automatically; but it looks like you need to pass an explicit namespace in to filter by the current namespace otherwise all namespaces are searched. The issue is I don't see a way to find the current namespace from inside a plugin; though I see how to list them all.

I notice the current namespace is passed into the URL paths for the built in components; but couldn't see a way get the current namespace injected into the router paths either. Is there a trick I've missed?

**Describe the solution you'd like**
There's a few ways this could be exposed. Maybe as a method on the DashboardClient interface; or maybe a property on the `service.Request` so that a plugin could encode the current namespace into the path in case a view needs it.

Another option is to specify `CurrentNamespace bool` on the `store.Key` struct so that the `DashboardClient` implementation knows only query with the current namespace in mind.

**Comment by wwitzel3** [comment]
Hi @jstrachan , so currently plugins can access the current namespace by setting up an action handler for the `action.RequestSetNamespace` action. See: https://github.com/vmware-tanzu/octant/blob/master/pkg/action/doc.go for an example.


We have #554 , which is a documentation Epic that will include easier to find plugin documentation and concrete examples of the various plugin capabilities. We that currently this information is not the easiest to find.

**Comment by jstrachan** [comment]
@wwitzel3 many thanks - thats awesome! I'd totally missed that.

BTW minor typo on https://github.com/vmware-tanzu/octant/blob/master/pkg/action/doc.go#L38 it should be `request` not `action`:

```go
namespace, err := request.Payload.String("namespace")
```

**Comment by jstrachan** [comment]
it'd be good to add a link to https://github.com/vmware-tanzu/octant/blob/master/pkg/action/doc.go on the plugin docs page: https://octant.dev/docs/master/plugins/ along with a link to the sample plugin https://github.com/vmware-tanzu/octant/tree/master/cmd/octant-sample-plugin so others can find this a bit easier. I'd do a PR but haven't yet got my head around how to update the website
