### ISSUE TITLE
Allow choosing which container to use for terminal

### ISSUE THREAD

**Issue by deiga** [vmware-tanzu/octant#901]
**Describe the problem/challenge you have**
We have pods with multiple containers and when we want to open a Terminal in Octant it doesn't offer any way to choose which container to open the terminal in and instead opens it in the "default" container.

**Describe the solution you'd like**
Could we have a similar drop-down like in the Logs tab for Terminal tab, where we can choose which container to Terminal into.

**Environment:**

- Octant version (use `octant version`): 0.12.1
- Kubernetes version (use `kubectl version`): v1.15.10
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.15

**Comment by wwitzel3** [comment]
Hi @deiga , thanks for the feedback.

Yes, this is something we've played with in the past, but removed when we refactored how the terminal worked. We weren't sure if folks were even using the feature at the time. Now we know people are :)

**Comment by wwitzel3** [comment]
### Implementation
- If there is only a single container, act the same way the terminal tab acts now and connect by default.
- If there is multiple containers, provide a select dropdown, connect to the first container by default.
- When a new container is selected from the drop down while connected to an existing container, we will disconnect the current session and connect to the new container.
