### ISSUE TITLE
is there a way for a plugin to send an Alert event to the UI

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#902]
**Describe the problem/challenge you have**
plugins can provide actions via the `Button` / `Form` / `Action` mechanism which lets you invoke handlers inside the plugin which is awesome. It would be great to be able to return an Alert to the front end, similar to when you trigger a CronJob or delete a resource or whatever to show if the action completed or failed

**Describe the solution you'd like**
Maybe the `service.ActionRequest` struct could also have an Alerter interface which lets you pass in an alert struct (text/markdown component and duration?)

**Comment by ZhangYW18** [comment]
Same here. If Octant plugin could have an Alerter, that would help a lot.
