### ISSUE TITLE
Context popup window is too narrow for longer contextes

### ISSUE THREAD

**Issue by alekc** [vmware-tanzu/octant#909]
Currently if you have a long context (see attachment) it's truncated and there is now way to determine which one is it without clicking and selecting it. 

Ideally popup should be resized to accommodate longer contexts or have a tooltip coming on hovering (similar to img alt)

**Environment:**
- Octant version (use `octant version`): 
```
Version:  0.12.1
Git commit:  870ee5775b84981ecc8f01e9a90f5182972c56bf
Built:  2020-04-24T10:27:13Z
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

![image](https://user-images.githubusercontent.com/302807/80990734-c0a68600-8e2e-11ea-97db-232afde6c126.png)

**Comment by GuessWhoSamFoo** [comment]
The max size of that dropdown can only be 360px which will show ~40 characters.

Trucating the long context name should move the ellipsis in the middle to show more detail.

**Comment by wwitzel3** [comment]
Adding this one in to our current sprint so it can get in to the next release. Multiple reports on this one being disruptive.

**Comment by GuessWhoSamFoo** [comment]
From clarity slack channel, recommended way to turn of truncating is CSS

```
.dropdown-menu .dropdown-item {
  white-space: normal;
}
```

**Comment by GuessWhoSamFoo** [comment]
Tried an approach that translates longer context names left to right on hover. It would not be a good experience for users with many contexts. An alternate approach could be smarter position of the ellipsis for overflow

**Comment by robjuz** [comment]
It also applies to to the namespaces dropdown.
