### ISSUE TITLE
No Context shown for vSphere with Kubernetes Cluster starting with Octant v0.12.x 

### ISSUE THREAD

**Issue by lamw** [vmware-tanzu/octant#912]
**What steps did you take and what happened:**

1) Enabled Workload Management for vSphere with Kubernetes Cluster and retrieved credentials for vSphere Namespace which was properly exported to ~/.kube/config

2) Download latest Octant (v0.12.1 but issue also observed with v0.12) and ran octant.exe and noticed no contexts were detected 

<img width="1780" alt="Screen Shot 2020-05-05 at 5 51 42 AM" src="https://user-images.githubusercontent.com/602199/81069938-72799d00-8e97-11ea-855c-567a6abfb9e4.png">

**What did you expect to happen:**

Being able to see my K8s Cluster

**Anything else you would like to add:**

I had an older version of Octant (v0.10.x) and I was able to have that worked, so I slowly worked backwards from the latest release (which was not working) and found that v0.11.1 was functional with this exact same environment. 

<img width="1773" alt="Screen Shot 2020-05-05 at 5 52 24 AM" src="https://user-images.githubusercontent.com/602199/81070177-bcfb1980-8e97-11ea-9b5f-23558459f81d.png">

My only conclusion is that something change between v0.11.1 to v0.12.x which caused a regression when attempting to connect to vSphere with Kubernetes Cluster

**Environment:**
```
vSphere 7.0 
* VCSA Build: 15952498
* ESXi Build: 15946738 
* NSX-T Build: 15344619
```

- Octant version (use `octant version`): 
```
Version:  0.12.0
Git commit:  f232c1880427da2f573950895d1a80db177beb03
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2-1+832aa4f47a8aff", GitCommit:"832aa4f47a8aff16cb033f48ccbf2f70d360f93f", GitTreeState:"clean", BuildDate:"2019-11-07T11:08:14Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.7-2+bfe512e5ddaaaa", GitCommit:"bfe512e5ddaaaa7243d602d5d161fa09a57ecf3c", GitTreeState:"clean", BuildDate:"2020-03-03T03:37:44Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
```
Windows Server 2016 Standard x64
```

**Comment by wwitzel3** [comment]
This looks like a caching issue, that is still the old UI in your screenshot. Try hard resetting the browser cache.

**Comment by lamw** [comment]
I initially didn't do a full cache clear, looks like that was needed but not ideal :( 

Do we expect that this is needed for each major update?
