### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by dlaidlaw** [vmware-tanzu/octant#923]
**What steps did you take and what happened:**
Running octant, no command line options. All of the errors are from the console application.

Time passes, about 10 minutes, using various views.

Many occurrences of this, about 2wice per minute:
`W0507 10:46:22.445100   21546 reflector.go:302] github.com/vmware-tanzu/octant/internal/objectstore/informer.go:82: watch of *unstructured.Unstructured ended with: too old resource version: 2448194 (2449322)`

More time passes ...

Get this error message about once per second:
`2020-05-07T10:37:30.780-0300	ERROR	api/context_manager.go:102	generate contexts	{"err": "unable to load kube config: Error loading config file \"/Users/dlaidlaw/.kube/config\": open /Users/dlaidlaw/.kube/config: too many open files"}`

**What did you expect to happen:**
Did not expect to see error messages. Especially the too many open files once per second.

**Anything else you would like to add:**
I have multiple contexts in the .kube/config file, but am using only one of them.
Viewing pod logs a lot.

**Environment:**

- Octant version (use `octant version`): 
```
Version:  0.12.1
Git commit:  870ee5775b84981ecc8f01e9a90f5182972c56bf
Built:  2020-04-24T10:29:28Z
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
macOS 10.15.4

**Comment by wwitzel3** [comment]
Hi @dlaidlaw sorry you've hit this bug.

Looks like we are leaking some file descriptors somewhere, thank you for reporting this, we will take a look.

**Comment by wwitzel3** [comment]
Both @GuessWhoSamFoo and myself have attempted to replicate this issue without any success.

What if any plugins are you running with Octant?

Also can you run this command: `ls -l /proc/`pidof octant`/fd | wc -l`

That should work on both MacOS and Linux and provide a count of the current number of file descriptor being used by Octant. My out for example looks like this.

```
 ~/repos/octant > ls -l /proc/`pidof octant`/fd | wc -l
17
 ~/repos/octant > ls -l /proc/`pidof octant`/fd
total 0
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 0 -> /dev/pts/3
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 1 -> /dev/pts/3
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 10 -> socket:[1042883]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 11 -> socket:[1047652]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 12 -> socket:[1047656]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 13 -> socket:[1045723]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 14 -> socket:[1045725]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 15 -> socket:[1044881]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 2 -> /dev/pts/3
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 3 -> socket:[1040344]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 4 -> anon_inode:[eventpoll]
lr-x------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 5 -> anon_inode:inotify
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 6 -> anon_inode:[eventpoll]
lr-x------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 7 -> pipe:[1040345]
l-wx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 8 -> pipe:[1040345]
lrwx------ 1 wwitzel3 wwitzel3 64 Jun 29 16:28 9 -> socket:[1040347]
```
