### ISSUE TITLE
Graphviz cannot be shown for v0.12.1

### ISSUE THREAD

**Issue by mengdie-song** [vmware-tanzu/octant#948]
**What steps did you take and what happened:**
Graphviz cannot be shown via octant@v0.12.1,
but it can be shown via octant@v0.10.2.

It seems that component.NewGraphviz is currently broken.

**What did you expect to happen:**
The graphviz can be shown on UI.

**Environment:**

- Octant version (use `octant version`): 
0.12.1
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", 
BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
Ubuntu 18.04.3 LTS

**Comment by wwitzel3** [comment]
@mengdie-song Thank you for reporting this, we will take a look.

**Comment by mengdie-song** [comment]
Thanks for fixing this issue.
BTW, I have another graphviz question regarding its resource usage.
https://github.com/vmware-tanzu/octant/issues/951
Could you also help take a look?
