### ISSUE TITLE
octant crash for version 0.13.0 (macOS)

### ISSUE THREAD

**Issue by dhaven** [vmware-tanzu/octant#970]
**What steps did you take and what happened:**
After upgrade 0.12.1 -> 0.13.0 octant crashes when command `octant` is run.
Here are the complete logs

`2020-06-02T15:28:00.841+0100	INFO	dash/watcher.go:116	watching config file	{"component": "config-watcher", "config": "/Users/dhaven/.kube/config-dev"}
2020-06-02T15:28:00.842+0100	INFO	dash/watcher.go:116	watching config file	{"component": "config-watcher", "config": "/Users/dhaven/.kube/config-prod"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/cronJob", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/deploymentConfiguration", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/serviceEditor", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/stopPortForward", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/cordon", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/uncordon", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/update", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/containerEditor", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/startPortForward", "module-name": "overview"}
2020-06-02T15:28:00.843+0100	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "action.octant.dev/deleteObject", "module-name": "configuration"}
2020-06-02T15:28:02.806+0100	INFO	dash/dash.go:415	Dashboard is available at http://127.0.0.1:7777

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15b1877]

goroutine 188 [running]:
k8s.io/apimachinery/pkg/api/resource.(*Quantity).String(0x0, 0x3d73160, 0xc0002210f0)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:601 +0x37
github.com/vmware-tanzu/octant/internal/printer.getCombinedMetrics(0xc000385020, 0x17, 0xc0007f1700, 0xe, 0xc000fd2540, 0x10, 0x0, 0x0, 0xc000fd2560, 0xb, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/printer/horizontalpodautoscaler.go:513 +0xd5f
github.com/vmware-tanzu/octant/internal/printer.HorizontalPodAutoscalerListHandler(0x3d451c0, 0xc00235aa50, 0xc001180e70, 0x0, 0x3d67580, 0xc0010f0960, 0x3d45500, 0xc00169ee08, 0x0, 0x0, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/printer/horizontalpodautoscaler.go:47 +0x490
reflect.Value.call(0x23a6760, 0x3b45e50, 0x13, 0x25c6d84, 0x4, 0xc001a3c9f0, 0x3, 0x3, 0x100be9f, 0x2460920, ...)
	/usr/local/Cellar/go/1.14.3/libexec/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x23a6760, 0x3b45e50, 0x13, 0xc001a3c9f0, 0x3, 0x3, 0xc001a3c901, 0xc000cdb6c0, 0xc001a3c918)
	/usr/local/Cellar/go/1.14.3/libexec/src/reflect/value.go:321 +0xb4
github.com/vmware-tanzu/octant/internal/printer.(*Resource).Print(0xc001190180, 0x3d451c0, 0xc00235aa50, 0x3d126c0, 0xc001180e70, 0x3d45540, 0xc0011125a0, 0xc000cdb6c0, 0x97, 0xb, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/printer/printer.go:77 +0x472
github.com/vmware-tanzu/octant/internal/describer.(*List).Describe(0xc0022bc160, 0x3d451c0, 0xc00235aa50, 0xc0000e2433, 0xb, 0x3d67580, 0xc0010f0960, 0x3d624c0, 0xc00239f340, 0xc00235ab10, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/describer/list.go:104 +0x908
github.com/vmware-tanzu/octant/internal/describer.(*Resource).Describe(0xc00041c410, 0x3d451c0, 0xc00235aa50, 0xc0000e2433, 0xb, 0x3d67580, 0xc0010f0960, 0x3d624c0, 0xc00239f340, 0xc00235ab10, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/describer/resource.go:58 +0xd4
github.com/vmware-tanzu/octant/internal/describer.(*Section).Component(0xc00004dd00, 0x3d451c0, 0xc00235aa50, 0xc0000e2433, 0xb, 0x3d67580, 0xc0010f0960, 0x3d624c0, 0xc00239f340, 0xc00235ab10, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/describer/section.go:54 +0x58e
github.com/vmware-tanzu/octant/internal/describer.(*Section).Describe(0xc00004dd00, 0x3d451c0, 0xc00235aa50, 0xc0000e2433, 0xb, 0x3d67580, 0xc0010f0960, 0x3d624c0, 0xc00239f340, 0xc00235ab10, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/describer/section.go:36 +0xc6
github.com/vmware-tanzu/octant/internal/describer.(*Section).Component(0xc00004de00, 0x3d451c0, 0xc00235aa50, 0xc0000e2433, 0xb, 0x3d67580, 0xc0010f0960, 0x3d624c0, 0xc00239f340, 0xc00235ab10, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/describer/section.go:54 +0x58e
github.com/vmware-tanzu/octant/internal/describer.(*Section).Describe(0xc00004de00, 0x3d451c0, 0xc00235aa50, 0xc0000e2433, 0xb, 0x3d67580, 0xc0010f0960, 0x3d624c0, 0xc00239f340, 0xc00235ab10, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/describer/section.go:36 +0xc6
github.com/vmware-tanzu/octant/internal/generator.(*Generator).Generate(0xc001167a40, 0x3d451c0, 0xc00235aa50, 0xc0000e2428, 0x16, 0xc000398a78, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/generator/generator.go:107 +0x82e
github.com/vmware-tanzu/octant/internal/modules/overview.(*Overview).Content(0xc0001a78f0, 0x3d45100, 0xc001517c00, 0xc0000e2428, 0x16, 0xc000398a78, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/modules/overview/overview.go:265 +0x15a
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).generateContent(0xc0000cad20, 0x3d45100, 0xc001517c00, 0x3d660e0, 0xc0000ea420, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:162 +0x321
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1(0x3d45100, 0xc001517c00, 0x4a0d660)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:116 +0xe0
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1(0x3d45100, 0xc0013c5c80, 0x3d56780, 0xc0013a2060, 0xc003313e77, 0xc00123c8a0, 0xc00036e0f0, 0xc000ed6900, 0x3b9aca00)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86 +0x271
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run(0xc0001256b0, 0x3d45100, 0xc0013c5c80, 0xc00123c8a0, 0xc000ed6900, 0x3b9aca00)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95 +0x2ff
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start(0xc0000cad20, 0x3d45100, 0xc0013c5c80, 0x3d660e0, 0xc0000ea420, 0x3d10a00, 0xc0010eea80)
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:106 +0x1e3
created by github.com/vmware-tanzu/octant/internal/api.(*WebsocketState).Start
	/private/tmp/octant-20200601-33665-1pevx93/src/github.com/vmware-tanzu/octant/internal/api/websocket_state.go:144 +0x9b`

**What did you expect to happen:**

octant should start up

**Anything else you would like to add:**
I use eks authentication in the kubeconfig file
aws version : aws-cli/1.17.9 Python/3.7.5 Darwin/18.7.0 botocore/1.15.1

**Environment:**

- Octant version (use `octant version`): 
0.13.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): 
MacOS Mojave 10.14.6

**Comment by wwitzel3** [comment]
Sorry you are encountering this error. Would you mind sharing the YAML for your HPA? It looks like that is causing the issue. We changed the HPA printer in 0.13, but looks like we missed something in our testing.

**Comment by dhaven** [comment]
It's a HPA based on https://github.com/awslabs/k8s-cloudwatch-adapter

**HPA template**
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: sqs-consumer-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: sqs-consumer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metric:
        name: sqs-helloworld-length
      target:
        type: AverageValue
        averageValue: 30

**external metric template**
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: sqs-helloworld-length
spec:
  name: sqs-helloworld-length
  resource:
    resource: "deployment"
  queries:
    - id: sqs_helloworld_length
      metricStat:
        metric:
          namespace: "AWS/SQS"
          metricName: "ApproximateNumberOfMessagesVisible"
          dimensions:
            - name: QueueName
              value: "helloworld"
        period: 300
        stat: Average
        unit: Count
      returnData: true

**Comment by nipuna-perera** [comment]
I am getting the same. I have many HPAs running on my namespace. Here's the yaml of one of them taken from octant version 0.12.1

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-05-06T09:03:21Z","reason":"ReadyForNewScale","message":"recommended
      size matches current size"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2020-05-22T00:00:25Z","reason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from memory resource
      utilization (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2020-05-06T09:03:21Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"memory","currentAverageUtilization":20,"currentAverageValue":"335716352"}}]'
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory","targetAverageUtilization":80}}]'
  creationTimestamp: "2020-05-06T09:03:06Z"
  name: masked-hpa
  namespace: masked-dev
  resourceVersion: "67092850"
  selfLink: /apis/autoscaling/v1/namespaces/fidcentral-dev/horizontalpodautoscalers/fcs-articlepagevote-hpa
  uid: 663f90fb-8f78-11ea-bf16-12d2c568e1af
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fcs-articlepagevote
status:
  currentReplicas: 1
  desiredReplicas: 1
  lastScaleTime: "2020-06-02T10:21:13Z"
```
