### ISSUE TITLE
kubeconfig permission denied causes Octant to crash

### ISSUE THREAD

**Issue by totallyGreg** [vmware-tanzu/octant#977]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Trying to run Ocant it fails to start.  
❯ octant --klog-verbosity 9
I0603 21:37:33.222350   80709 loader.go:375] Config loaded from file:  /Users/totally/.kube/config
2020-06-03T21:37:33.228-0400    INFO    dash/watcher.go:116     watching config file       {"component": "config-watcher", "config": ""}
unable to start runner: set up config watcher: unable to watch : unable to watch : permission denied
**What did you expect to happen:**
I expected it to start and give me the localhost url. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I just updated to 0.13.1 in hopes it would fix the issue.  First noticed this on 0.13.0

**Environment:**
- Octant version (use `octant version`): 
Version:  0.13.1
Git commit:  72c5ea94283ab48cc6c2b7e91d7c901af031ecb3
Built:  2020-06-04T00:21:32Z

- Kubernetes version (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): MacOS 
10.15.4

**Comment by wwitzel3** [comment]
What are the permissions of the `/Users/totally/.kube/config` file? Is this a file you created or did a tool create it for you?

**Comment by totallyGreg** [comment]
`-rw-------  1 totally  staff  107588 Jun  4 15:47 /Users/totally/.kube/config
`
az aks get-credentials is probably the last tool to modify this.  
I also use kubectx and kubens to switch context and namespaces.

**Comment by wwitzel3** [comment]
I set my local kube config to the same permissions, 0600, and launch Octant, I am unable to replicate this error.

What are the permissions on the `.kube` folder?

**Comment by wwitzel3** [comment]
Also if I understand correctly, you can run 0.12.1 without this error?

**Comment by totallyGreg** [comment]
`drwxr-xr-x`  9 totally  staff  288 Jun  7 20:57 /Users/totally/.kube

I was running it successfully ~two weeks ago.  I updated via brew and didn't realize until next time I tried to run it that it wasn't working.  I believe that was 0.12.1, I tried to rollback but brew does not make that easy if a brew clean was run.

**Comment by totallyGreg** [comment]
This is no longer an issue.  I do not understand why.  Octant 0.13.1 now launches successfully.  The only thing I can think of is that kubectx/kubens are modifying my ~/.kube/config in a way that made it temporarily unreadable by octant.  Nothing else has changed.

**Comment by wwitzel3** [comment]
Interesting, well I'm glad resolved itself, feel free to re-open this if it starts happening again and you are able to notice a pattern / incantation that causes this.
